DocWorks for js-wixcode-sdk - 10 changes detected, but 3 issue detected changes: Service $w.Footer has changed description Service $w.Footer has a new link [Document]($w.Document.html) Service $w.Header has changed description Service $w.Header has a new link [Footer]($w.Footer.html) Service $w.Header has a new link [Document]($w.Document.html) Service $w.Header link [Header]($w.Header.html) was removed Service $w.KeyboardEvent property key has changed description Service $w.Page has changed description Service $w.Page has a new link [Document]($w.Document.html) Service $w.Repeater operation forEachItem.examples[0] has changed body
issues:
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
ERROR: The @snippet tag - file 'examples/State-name.es6' not found. File: State.es6 line: 71
ERROR: The @snippet tag - file 'examples/State-name.es6' not found. File: State.es6 line: 88