DocWorks for wix-store-backend - 20 changes detected, but 22 issue detected changes: Service wix-stores-backend.Events operation onCartCompleted.examples[1] has changed body Service wix-stores-backend.Events message Address.examples[0] has changed body Service wix-stores-backend.Events message BuyerInfo was removed Service wix-stores-backend.Events message CartAbandonedEvent member buyerInfo has changed type Service wix-stores-backend.Events message CartAppliedCoupon was removed Service wix-stores-backend.Events message CartCompletedEvent member buyerInfo has changed type Service wix-stores-backend.Events message CartCompletedEvent member appliedCoupon has changed type Service wix-stores-backend.Events message CartCompletedEvent member currency has changed type Service wix-stores-backend.Events message CartCompletedEvent member totals has changed type Service wix-stores-backend.Events message CartCompletedEvent member shippingInfo has changed type Service wix-stores-backend.Events message CartCompletedEvent.examples[0] has changed body Service wix-stores-backend.Events message CartCreatedEvent member buyerInfo has changed type Service wix-stores-backend.Events message CartCreatedEvent member totals has changed type Service wix-stores-backend.Events message Currency was removed Service wix-stores-backend.Events message NewOrderEvent member buyerInfo has changed type Service wix-stores-backend.Events message NewOrderEvent member totals has changed type Service wix-stores-backend.Events message OrderTotals was removed Service wix-stores-backend.Events message ShippingInfo was removed Service wix-stores-backend has a new operation getMyCart Service wix-stores-backend has a new message Geo
issues:
Message NewOrderEvent has an unknown property type wix-stores-backend.BuyerInfo (events.js (41))
Message NewOrderEvent has an unknown property type wix-stores-backend.OrderTotals (events.js (41))
Message CartAbandonedEvent has an unknown property type wix-stores-backend.BuyerInfo (events.js (73))
Message CartCreatedEvent has an unknown property type wix-stores-backend.BuyerInfo (events.js (133))
Message CartCreatedEvent has an unknown property type wix-stores-backend.Events.Currency (events.js (133))
Message CartCreatedEvent has an unknown property type wix-stores-backend.OrderTotals (events.js (133))
Message CartCompletedEvent has an unknown property type wix-stores-backend.BuyerInfo (events.js (158))
Message CartCompletedEvent has an unknown property type wix-stores-backend.AppliedCoupon (events.js (158))
Message CartCompletedEvent has an unknown property type wix-stores-backend.Currency (events.js (158))
Message CartCompletedEvent has an unknown property type wix-stores-backend.OrderTotals (events.js (158))
Message CartCompletedEvent has an unknown property type wix-stores-backend.ShippingInfo (events.js (158))
Operation getMyCart has an unknown return type wix-stores-backend.Cart (carts.js (166))
Message ProductOptionsAvailability has an unknown property type $w.ProductPage.StoreProductOptions (products.js (26))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.ImageItem (products.js (26))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.VideoItem (products.js (26))
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 6
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 89
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 114
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 123
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 138
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 166
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 178