DocWorks for js-wixcode-sdk - 11 changes detected, but 11 issue detected changes: Service wix-location operation to has changed description Service wix-location operation to.examples[1] has changed title Service wix-location operation to.examples[1] has changed body Service wix-location operation to.examples[1] has changed extra.description Service wix-location operation to.examples[2] has changed title Service wix-location operation to.examples[2] has changed body Service wix-location operation to.examples[3] has changed title Service wix-location operation to.examples[3] has changed body Service wix-location operation to.examples[4] has changed title Service wix-location operation to.examples[4] has changed body Service wix-location operation to.examples has 1 new examples
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 397