DocWorks for mobile-elements - no significant changes detected, but 19 issue detected
issues:
Mixin $w.ContainableMixin not found (MobileContainer.js (1))
Operation onChange has an unknown param type $w.EventHandler (MobilePicker.js (254))
Property validateOnChange is defined two or more times (MobilePicker.js (213, 228))
Property validateOnStart is defined two or more times (MobilePicker.js (234, 248))
Mixin $w.LabelMixin not found (MobilePicker.js (1))
Mixin $w.ValueMixin not found (MobilePicker.js (1))
Mixin $w.Event not found (MobilePressableMixin.js (114))
Mixin $w.LabelMixin not found (MobileTextInput.js (1))
Property parent has an unknown type $w.Node (MobileElement.js (78))
Mixin $w.Element not found (MobileElement.js (1))
Operation onChange has an unknown param type $w.EventHandler (MobileFormElement.js (161))
Property validateOnBlur is defined two or more times (MobileFormElement.js (97, 114))
Property validateOnChange is defined two or more times (MobileFormElement.js (120, 135))
Property validateOnStart is defined two or more times (MobileFormElement.js (141, 155))
Mixin $w.ValueMixin not found (MobileFormElement.js (1))
Mixin $w.CollapsedMixin not found (MobileHiddenCollapsedMixin.js (1))
Mixin $w.HiddenMixin not found (MobileHiddenMixin.js (1))
ERROR: The @description tag requires a value. File: MobilePicker.js, line: 97
ERROR: The @description tag requires a value. File: MobilePicker.js, line: 117