DocWorks for wix-secrets-backend - 13 changes detected, but 2 issue detected changes: Service wix-secrets-backend has changed summary Service wix-secrets-backend has changed description Service wix-secrets-backend operation createSecret was removed Service wix-secrets-backend operation deleteSecret was removed Service wix-secrets-backend operation getSecret.examples[0] has changed body Service wix-secrets-backend operation getSecret.examples[1] has changed body Service wix-secrets-backend operation getSecret.examples[2] has changed body Service wix-secrets-backend operation getSecret.examples has 1 examples removed Service wix-secrets-backend operation getSecret has changed extra.notes Service wix-secrets-backend operation listSecretInfo was removed Service wix-secrets-backend operation updateSecret was removed Service wix-secrets-backend message Secret was removed Service wix-secrets-backend message SecretInfo was removed
issues:
ERROR: The @snippet tag - file 'corvid-docs/examples/billing-invoices-getInvoice.es6' not found. File: secrets.js line: 30
ERROR: The @snippet tag - file 'corvid-docs/examples/billing-invoices-createInvoice.es6' not found. File: secrets.js line: 30