DocWorks for wix-stores-backend - 12 changes detected, but 3 issue detected changes: Service wix-stores-backend operation getProductVariants has changed param options doc Service wix-stores-backend operation getProductVariants has changed return type Service wix-stores-backend operation getProductVariants has changed summary Service wix-stores-backend operation getProductVariants has changed description Service wix-stores-backend operation getProductVariants.examples[0] has changed body Service wix-stores-backend operation getProductVariants.examples[1] has changed body Service wix-stores-backend operation getProductVariants.examples has 1 examples removed Service wix-stores-backend message PagingOptions.examples has 1 examples removed Service wix-stores-backend message ProductVariantOptions member paging was removed Service wix-stores-backend message ProductVariantOptions.examples has 1 examples removed Service wix-stores-backend message VariantInfo.examples[0] has changed body Service wix-stores-backend message Variants.examples[0] has changed body
issues:
Message ProductCreatedEvent has an unknown property type $w.Gallery.VideoItem (events.js (223))
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-getProductVariants_paging.es6' not found. File: products.js line: 257
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-getProductVariants_paging.es6' not found. File: products.js line: 267