DocWorks for wixstore-client-worker - 3 changes detected, but 1 issue detected changes: Service $w.CartIcon was removed Service $w.ProductPage was removed Service $w.ThankYouPage was removed
issues:
ERROR: Unable to find the source file or directory /Users/dori/projects/docworks-fixes/ecom/client/wixstores-client/wixstores-client-worker/dist/src/wixCodeDocs.js