DocWorks for wixstore-client-worker - 2 changes detected, but 1 issue detected changes: Service $w.CartIcon was removed Service $w.ProductPage was removed
issues:
ERROR: Unable to find the source file or directory /home/builduser/agent00/work/8a28ec87a8a0f583/client/wixstores-client/wixstores-client-worker/dist/src/viewer-script/controllers