DocWorks for js-wixcode-sdk - 4 changes detected, but 16 issue detected changes: Service $w has a new callback CommentEventCallback Service $w has a new message CommentBoxOptions Service $w has a new message WidgetComment Service $w.CommentsWidget is new
issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Property locked is missing a type annotation (CommentsWidget.js (14))
Operation postMessage has an unknown param type * (HtmlComponent.js (97))
Property data has an unknown type * (HtmlComponentMessageEvent.js (16))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window-frontend.js (201))
Operation get has an unknown return type * (window-frontend.js (234))
Operation set has an unknown param type * (window.js (235))
Operation get has an unknown return type * (window.js (269))
Callback ViewChangeOperation is defined two or more times (AppointmentField.js (347), DatePicker.js (472))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Callback ViewChangeEventHandler is defined two or more times (AppointmentField.js (362), DatePicker.js (466))
Callback Validator has an unknown param type * (ValidatableMixin.js (143))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))
ERROR: The @summary tag requires a value. File: CommentsWidget.js, line: 124