DocWorks for js-wixcode-sdk - 25 changes detected, but 3 issue detected changes: Service wix-window.multilingual property siteLanguages.examples has 1 new examples Service wix-window.trackingParameters message AddPaymentInfoEvent has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message AddPaymentInfoEvent link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message AddProductImpressionEvent has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message AddProductImpressionEvent link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message AddProductImpressionEventContents has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message AddProductImpressionEventContents link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message AddToCartEvent has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message AddToCartEvent link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message ClickProductEvent has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message ClickProductEvent link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message CustomEvent has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message CustomEvent link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message InitiateCheckoutEvent has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message InitiateCheckoutEvent link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message InitiateCheckoutEventContents has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message InitiateCheckoutEventContents link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message PurchaseEvent has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message PurchaseEvent link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message PurchaseEventContents has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message PurchaseEventContents link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message RemoveFromCartEvent has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message RemoveFromCartEvent link [trackEvent( )](#trackEvent) was removed Service wix-window.trackingParameters message ViewContentEvent has a new link [trackEvent( )](wix-window.html#trackEvent) Service wix-window.trackingParameters message ViewContentEvent link [trackEvent( )](#trackEvent) was removed
issues:
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (98))
ERROR: The @snippet tag - file 'examples/Multilingual-siteLanguages.es6' not found. File: window.es6 line: 1179
ERROR: The @snippet tag - file 'examples/Multilingual-siteLanguages.es6' not found. File: window.es6 line: 1205