DocWorks for wix-members-backend - 8 changes detected, but 3 issue detected changes: Service wix-members-backend.Events operation on was removed Service wix-members-backend.Events operation onMemberApproved has changed param name from members to event Service wix-members-backend.Events operation onMemberApproved has changed param event type Service wix-members-backend.Events operation onMemberBlocked was removed Service wix-members-backend.Events operation onMemberCreated was removed Service wix-members-backend.Events message BlockedMemberEvent was removed Service wix-members-backend.Events message CreatedMemberEvent was removed Service wix-members-backend message Events~ was removed
issues:
Message ApprovedMemberEvent has an unknown property type Members (events.js (50))
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberApproved.es6' not found. File: events.js line: 31
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberApproved.es6' not found. File: events.js line: 47