DocWorks for wix-pay-backend - 5 changes detected, but 6 issue detected changes: Service wix-pay-backend.Events operation onPaymentUpdate.examples[0] has changed body Service wix-pay-backend.Events message PaymentUpdateEvent.examples[0] has changed body Service wix-pay-backend operation createPayment.examples[1] has changed body Service wix-pay-backend message PaymentUserInfo member country was removed Service wix-pay-backend message PaymentUserInfo has a new member countryCode
issues:
Message PaymentUpdateEvent has an unknown property type wix-pay-backend.Payment (events.js (43))
Message PaymentUpdateEvent has an unknown property type wix-pay.PaymentUserInfo (events.js (43))
Operation createPayment has an unknown return type wix-pay.Payment (create-payment.js (104))
Message PaymentRequest has an unknown property type wix-pay.PaymentItem (create-payment.js (69))
ERROR: The @snippet tag - file 'examples/Pay-backend-createPayment.es6' not found. File: create-payment.js line: 104
ERROR: The @snippet tag - file 'examples/Pay-backend-createPayment.es6' not found. File: create-payment.js line: 147