DocWorks for wix-ui-santa - 38 changes detected, but 66 issue detected changes: Service $w.AddressInput has a new mixes $w.FormElement Service $w.AddressInput has a new mixes $w.DisabledMixin Service $w.AddressInput has a new mixes $w.RequiredMixin Service $w.AddressInput has a new mixes $w.ReadOnlyMixin Service $w.AddressInput has a new mixes $w.HiddenCollapsedMixin Service $w.AddressInput has a new mixes $w.FocusMixin Service $w.AddressInput has a new mixes $w.ClickableMixin Service $w.AddressInput has changed summary Service $w.AddressInput property filter has changed type Service $w.AddressInput property filter has changed description Service $w.AddressInput property filter.examples has 2 new examples Service $w.AddressInput property googleMapsApiKey has changed type Service $w.AddressInput property googleMapsApiKey has changed getter Service $w.AddressInput property googleMapsApiKey has changed description Service $w.AddressInput property googleMapsApiKey.examples has 2 new examples Service $w.AddressInput property locale has changed type Service $w.AddressInput property locale has changed getter Service $w.AddressInput property locale has changed description Service $w.AddressInput property locale.examples has 2 new examples Service $w.AddressInput property placeholder has changed type Service $w.AddressInput property placeholder has changed getter Service $w.AddressInput property placeholder has changed description Service $w.AddressInput property placeholder.examples has 2 new examples Service $w.AddressInput property sorting was removed Service $w.AddressInput has a new property value Service $w.AddressInput has a new property bias Service $w.AddressInput has a new message Address Service $w.AddressInput has a new message AddressLocation Service $w.AddressInput has a new message AddressStreetNumber Service $w.AddressInput has a new message AddressRoute Service $w.AddressInput has a new message AddressLocality Service $w.AddressInput has a new message AddressAdminArea1 Service $w.AddressInput has a new message AddressAdminArea2 Service $w.AddressInput has a new message AddressCountry Service $w.AddressInput has a new message AddressPostalCode Service $w.AddressInput has a new message AddressFilter Service $w.AddressInput has a new message AddressBias Service $w.AddressInput has changed extra.notes
issues:
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (35))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (4))
Mixin $w.ValueMixin not found (Slider.js (4))
Mixin $w.DisabledMixin not found (Slider.js (4))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (4))
Mixin $w.FocusMixin not found (Slider.js (4))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (473))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (512))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (551))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (588))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (10))
Mixin $w.DisabledMixin not found (TimePicker.js (10))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (10))
Mixin $w.RequiredMixin not found (TimePicker.js (10))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (10))
Mixin $w.FormElement not found (TimePicker.js (10))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (24))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Property placeholder is missing a type annotation (AddressInput.js (220))
Property locale is missing a type annotation (AddressInput.js (266))
Property googleMapsApiKey is missing a type annotation (AddressInput.js (332))
Property filter has an unknown type AddressInput.AddressFilter (AddressInput.js (377))
Mixin $w.FormElement not found (AddressInput.js (126))
Mixin $w.DisabledMixin not found (AddressInput.js (126))
Mixin $w.RequiredMixin not found (AddressInput.js (126))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (126))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (126))
Mixin $w.FocusMixin not found (AddressInput.js (126))
Mixin $w.ClickableMixin not found (AddressInput.js (126))
ERROR: The @snippet tag - file 'examples/[AddressInput-bias_get.es6=Get a preferred geographic area
for suggested address results]' not found. File: AddressInput.js line: 154
ERROR: Unable to parse a tag's type expression for source file /Users/samm/Documents/repos/wix-ui-santa/src/components/AddressInput/wixcode/AddressInput.js with tag title "type" and text "{external: String}": Invalid type expression "external: String": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter or [1-9] but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/samm/Documents/repos/wix-ui-santa/src/components/AddressInput/wixcode/AddressInput.js with tag title "type" and text "{external: String}": Invalid type expression "external: String": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter or [1-9] but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/samm/Documents/repos/wix-ui-santa/src/components/AddressInput/wixcode/AddressInput.js with tag title "type" and text "{external: String}": Invalid type expression "external: String": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter or [1-9] but " " found.
ERROR: The @snippet tag - file 'examples/[AddressInput-bias_get.es6=Get a preferred geographic area
for suggested address results]' not found. File: AddressInput.js line: 518
ERROR: The @snippet tag - file 'examples/[AddressInput-bias_set.es6=Set a preferred geographic area
for suggested address results]' not found. File: AddressInput.js line: 518