DocWorks for wix-crm-backend - 25 changes detected, but 10 issue detected changes: Service wix-crm-backend.Events has changed description Service wix-crm-backend.Events operation onCardCreated has changed extra.notes Service wix-crm-backend.Events operation onCardMoved has changed extra.notes Service wix-crm-backend.Events operation onFormSubmit has changed extra.notes Service wix-crm-backend.Events operation onInvoiceCreated has changed extra.notes Service wix-crm-backend.Events operation onInvoiceOverdue has changed extra.notes Service wix-crm-backend.Events operation onInvoicePaid has changed extra.notes Service wix-crm-backend.Events operation onInvoiceSent has changed extra.notes Service wix-crm-backend.Events operation onPriceQuoteAccepted has changed extra.notes Service wix-crm-backend.Events operation onPriceQuoteCreated has changed extra.notes Service wix-crm-backend.Events operation onPriceQuoteExpired has changed extra.notes Service wix-crm-backend.Events operation onPriceQuoteSent has changed extra.notes Service wix-crm-backend.invoices has a new operation sendInvoiceToCustomer Service wix-crm-backend.invoices has a new operation voidInvoice Service wix-crm-backend.invoices has a new operation createInvoicePreviewLink Service wix-crm-backend.priceQuotes has a new operation sendPriceQuoteToCustomer Service wix-crm-backend.workflows operation getCard has changed return type Service wix-crm-backend.workflows operation getPhase has changed return type Service wix-crm-backend.workflows operation getWorkflow has changed return type Service wix-crm-backend.workflows message Card member createdAt was removed Service wix-crm-backend.workflows message Card member updatedAt was removed Service wix-crm-backend.workflows message Card has a new member createdDate Service wix-crm-backend.workflows message Card has a new member updatedDate Service wix-crm-backend.workflows message Workflow member createdAt was removed Service wix-crm-backend.workflows message Workflow has a new member createdDate
issues:
Operation emailContact has an unknown param type wix-users.TriggeredEmailOptions (contacts.js (90))
Operation sendInvoiceToCustomer has an unknown param type wix-crm-backend.invoices.ISendInvoiceToCustomerRequest (invoices.js (209))
Operation sendPriceQuoteToCustomer has an unknown param type wix-crm-backend.priceQuotes.ISendPriceQuoteToCustomerRequest (price-quotes.js (221))
Operation getCard has an unknown return type wix-crm-backend.workflow.Card (cardsApi.js (59))
Operation getPhase has an unknown return type wix-crm-backend.workflow.Phase (phasesApi.js (57))
Operation getWorkflow has an unknown return type crm-backend.workflows.Workflow (workflowsApi.js (43))
Message Card is defined two or more times (types.js (2), typesDocs.js (2))
Message Phase is defined two or more times (types.js (12), typesDocs.js (14))
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-sendPriceQuoteToCustomer.es6' not found. File: price-quotes.js line: 221
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-sendPriceQuoteToCustomer.es6' not found. File: price-quotes.js line: 236