DocWorks for mobile-elements - no significant changes detected, but 22 issue detected
issues:
Mixin $w.ContainableMixin not found (MobileContainer.js (1))
Operation onChange has an unknown param type $w.EventHandler (MobilePicker.js (254))
Property validateOnChange is defined two or more times (MobilePicker.js (213, 228))
Property validateOnStart is defined two or more times (MobilePicker.js (234, 248))
Mixin $w.LabelMixin not found (MobilePicker.js (1))
Mixin $w.ValueMixin not found (MobilePicker.js (1))
Mixin $w.Event not found (MobilePressableMixin.js (113))
Operation onItemRemoved has an unknown return type $w.Repeater (MobileRepeater.js (378))
Mixin $w.LabelMixin not found (MobileTextInput.js (1))
Property parent has an unknown type $w.Node (MobileElement.js (77))
Operation onChange has an unknown param type $w.EventHandler (MobileFormElement.js (161))
Property validateOnBlur is defined two or more times (MobileFormElement.js (97, 114))
Property validateOnChange is defined two or more times (MobileFormElement.js (120, 135))
Property validateOnStart is defined two or more times (MobileFormElement.js (141, 155))
Mixin $w.ValueMixin not found (MobileFormElement.js (1))
Mixin $w.CollapsedMixin not found (MobileHiddenCollapsedMixin.js (1))
Mixin $w.HiddenMixin not found (MobileHiddenMixin.js (1))
ERROR: The @snippet tag - file 'velo-docs/examples/DisabledMixin-disable.es6' not found. File: MobileDisabledMixin.js line: 43
ERROR: The @snippet tag - file 'velo-docs/examples/DisabledMixin-disable_then.es6' not found. File: MobileDisabledMixin.js line: 43
ERROR: The @snippet tag - file 'velo-docs/examples/DisabledMixin_toggle_enabled.es6' not found. File: MobileDisabledMixin.js line: 43
ERROR: The @description tag requires a value. File: MobilePicker.js, line: 97
ERROR: The @description tag requires a value. File: MobilePicker.js, line: 117