DocWorks for wix-members-backend - 4 changes detected, but 7 issue detected changes: Service wix-members-backend.Events operation onMemberBlocked has changed description Service wix-members-backend.Events operation onMemberBlocked has a new link [BlockMember( )](wix-members-backend/blockmember) Service wix-members-backend.Events operation onMemberBlocked link [BlockedMember( ) (wix-members-backend/blockmember) was removed Service wix-members-backend.Events has a new message BlockMemberEvent
issues:
Message ApprovedMemberEvent has an unknown property type Members (events.js (47))
Message BlockMemberEvent has an unknown property type Members (events.js (72))
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberApproved.es6' not found. File: events.js line: 31
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberApproved.es6' not found. File: events.js line: 47
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberBlocked.es6' not found. File: events.js line: 55
ERROR: Unable to parse a tag's type expression for source file /Users/michaelho/Desktop/repos/velo-docs/wix-members-backend/velo-docs/api/events.js with tag title "param" and text "{wix-members-backend.Events~} event Information about the  site member that was blocked.": Invalid type expression "wix-members-backend.Events~": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but en ...