DocWorks for wix-data-core - 4 changes detected, but 5 issue detected changes: Service wix-data.WixDataQuery operation distinct was removed Service wix-data has a new operation bulkRemove Service wix-data message WixDataBulkResult has a new member removed Service wix-data message WixDataBulkResult has a new member removedItemIds
issues:
Operation eq has an unknown param type * (filterMixin.es6 (19))
Operation onFailure has an unknown param type Error (hooks.es6 (499))
Operation eq has an unknown param type * (filterMixin.es6 (19))
Message WixDataBulkResult has an unknown property type Error (data-api.es6 (871))
ERROR: The @snippet tag - file 'examples/WixData-bulkRemove_id.es6' not found. File: data-api.es6 line: 871