DocWorks for wix-members-backend - 5 changes detected, but 31 issue detected changes: Service wix-members-backend.Events operation on was removed Service wix-members-backend.Events has a new operation onMemberUnmuted Service wix-members-backend.Events has a new operation onMemberUpdated Service wix-members-backend.Events has a new message UpdatedMemberEvent Service wix-members-backend message Events~ was removed
issues:
Message ApprovedMemberEvent has an unknown property type Members (events.js (47))
Message BlockMemberEvent has an unknown property type Members (events.js (72))
Message CreatedMemberEvent has an unknown property type Members (events.js (96))
Message MemberDeletedEvent has an unknown property type Members (events.js (120))
Message JoinedMemberEvent has an unknown property type Members (events.js (143))
Message LeftMemberEvent has an unknown property type Members (events.js (167))
Message MutedMemberEvent has an unknown property type Members (events.js (192))
Message MutedMemberEvent is defined two or more times (events.js (192, 216))
Message UpdatedMemberEvent has an unknown property type Members (events.js (241))
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberApproved.es6' not found. File: events.js line: 31
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberApproved.es6' not found. File: events.js line: 47
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberBlocked.es6' not found. File: events.js line: 55
ERROR: Unable to parse a tag's type expression for source file /Users/michaelho/Desktop/repos/velo-docs/wix-members-backend/velo-docs/api/events.js with tag title "param" and text "{wix-members-backend.Events~} event Information about the  site member that was blocked.": Invalid type expression "wix-members-backend.Events~": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default",  ...