DocWorks for wix-members-backend - 12 changes detected, but 27 issue detected changes: Service wix-members-backend.Events operation onMemberBlocked has changed param name from undefined to event Service wix-members-backend.Events operation onMemberBlocked has changed param event type Service wix-members-backend.Events operation onMemberBlocked has changed param event doc Service wix-members-backend.Events operation onMemberMuted has changed param name from undefined to event Service wix-members-backend.Events operation onMemberMuted has changed param event type Service wix-members-backend.Events operation onMemberMuted has changed param event doc Service wix-members-backend.Events operation onMemberUnmuted has changed param name from undefined to event Service wix-members-backend.Events operation onMemberUnmuted has changed param event type Service wix-members-backend.Events operation onMemberUnmuted has changed param event doc Service wix-members-backend.Events operation onMemberUpdated has changed param name from undefined to event Service wix-members-backend.Events operation onMemberUpdated has changed param event type Service wix-members-backend.Events operation onMemberUpdated has changed param event doc
issues:
Message ApprovedMemberEvent has an unknown property type Members (events.js (47))
Message BlockMemberEvent has an unknown property type Members (events.js (72))
Message CreatedMemberEvent has an unknown property type Members (events.js (96))
Message MemberDeletedEvent has an unknown property type Members (events.js (120))
Message JoinedMemberEvent has an unknown property type Members (events.js (143))
Message LeftMemberEvent has an unknown property type Members (events.js (167))
Message MutedMemberEvent has an unknown property type Members (events.js (192))
Message MutedMemberEvent is defined two or more times (events.js (192, 216))
Message UpdatedMemberEvent has an unknown property type Members (events.js (241))
ERROR: The @snippet tag - file 'velo-do ...