DocWorks for wix-users-backend - 1 change detected, but 3 issue detected changes: Service wix-users-backend.Badges operation updateBadge has changed description
issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (537))
Message RegistrationResult has an unknown property type wix-users.User (users.js (34))
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 65