DocWorks for js-wixcode-sdk - 38 changes detected, but 11 issue detected changes: Service $w.CheckboxGroup has changed summary Service $w.GoogleMap has a new property center Service $w.GoogleMap has a new property zoom Service $w.GoogleMap has a new property markers Service $w.PlayableMixin operation onPause has changed extra.notes Service $w.PlayableMixin operation pause has changed extra.notes Service $w.PlayableMixin operation play has changed extra.notes Service $w.Repeater property data has changed description Service $w.Repeater operation forEachItem has changed description Service $w.Repeater operation forItems has changed description Service $w.Repeater operation onItemReady has changed description Service $w.Slideshow operation onChange has changed extra.notes Service $w.StyleMixin has changed description Service $w.Table operation onRowSelect has changed description Service $w.TextInputMixin operation onKeyPress has changed extra.notes Service $w.TextInputMixin has a new operation onInput Service $w.UploadButton.examples[0] has changed body Service $w.UploadButton property value.examples[1] has changed body Service $w.UploadButton operation startUpload.examples[1] has changed body Service $w.UploadButton message UploadedFile member mediaId was removed Service $w.UploadButton message UploadedFile member title was removed Service $w.UploadButton message UploadedFile member width was removed Service $w.UploadButton message UploadedFile member height was removed Service $w operation at has changed description Service $w operation at.examples has 1 examples removed Service wix-site message StructurePage member name has changed doc Service wix-storage.Storage has changed summary Service wix-storage.Storage operation setItem has changed extra.notes Service wix-storage has changed summary Service wix-storage has changed description Service wix-window operation copyToClipboard param toCopy was removed Service wix-window operation copyToClipboard has changed return doc Service wix-window operation copyToClipboard has changed summary Service wix-window operation copyToClipboard has changed description Service wix-window operation copyToClipboard.examples[0] has changed body Service $w.HoverBox is new Service $w.VideoBox is new Service wix-events is new
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 381
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389