DocWorks for wix-pricing-plans-backend - 6 changes detected, but 4 issue detected changes: Service wix-pricing-plans-backend operation createPlan has changed param planInfo type Service wix-pricing-plans-backend operation createPlan has changed description Service wix-pricing-plans-backend operation queryPublicPlans has changed description Service wix-pricing-plans-backend operation queryPublicPlans.examples[0] has changed body Service wix-pricing-plans-backend message CreatePlanInfo was removed Service wix-pricing-plans-backend has a new message CreatePlanOptions
issues:
Operation eq has an unknown param type * (PublicPlansQueryBuilder.js (43))
Operation ne has an unknown param type * (PublicPlansQueryBuilder.js (63))
ERROR: Unable to parse a tag's type expression for source file /Users/martab/Repositories/velo-docs/wix-pricing-plans-backend/velo-docs/api/shared.js with tag title "property" and text "{Array<wix-pricing-plans-backend~Plan} plans List of public and hidden pricing plans.": Invalid type expression "Array<wix-pricing-plans-backend~Plan": Expected "!", "#", "$", "(", ",", "-", ".", "/", "0", ":", "<", "=", ">", "?", "@", "[]", "\\", "_", "|", "~", "‌", "‍", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but end of input found.
ERROR: Unable to parse a tag's type expression for source file /Users/martab/Repositories/velo-docs/wix-pricing-plans-backend/velo-docs/api/shared.js with tag title "property" and text "{Array<wix-pricing-plans-backend~PublicPlan} publicPlans List of public pricing plans.": Invalid type expression "Array<wix-pricing-plans-backend~PublicPlan": Expected "!", "#", "$", "(", ",", "-", ".", "/", "0", ":", "<", "=", ">", "?", "@", "[]", "\\", "_", "|", "~", "‌", "‍", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowerc ...