DocWorks for js-wixcode-sdk - 2 changes detected, but 17 issue detected changes: Service $w.DatePicker operation onCustomValidation.examples has 3 new examples Service $w.DatePicker operation onViewChange.examples has 3 examples removed
issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (97))
Property data has an unknown type * (HtmlComponentMessageEvent.js (16))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window-frontend.js (201))
Operation get has an unknown return type * (window-frontend.js (234))
Operation set has an unknown param type * (window.js (235))
Operation get has an unknown return type * (window.js (269))
Callback ViewChangeOperation is defined two or more times (AppointmentField.js (347), DatePicker.js (473))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Callback ViewChangeEventHandler is defined two or more times (AppointmentField.js (362), DatePicker.js (467))
Callback Validator has an unknown param type * (ValidatableMixin.js (143))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))
ERROR: The @snippet tag - file 'velo-docs/examples/DatePicker-onViewChange_get_month_dates.es6' not found. File: DatePicker.js line: 420
ERROR: The @snippet tag - file 'velo-docs/examples/DatePicker-onViewChange_set_disabled_date_ranges_holidays.es6' not found. File: DatePicker.js line: 420
ERROR: The @snippet tag - file 'velo-docs/examples/DatePicker-onViewChange_set_disabled_date_ranges_unavailable.es6' not found. File: DatePicker.js line: 420