DocWorks for js-wixcode-sdk - 2 changes detected, but 2 issue detected changes: Service wix-window.multilingual has a new message SiteLanguages Service wix-window message SiteLanguages was removed
issues:
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (98))
ERROR: The @snippet tag - file 'examples/Multilingual-siteLanguages.es6' not found. File: window.es6 line: 1179