DocWorks for payment-provider-spi - 7 changes detected, but 2 issue detected changes: Service payment-provider-spi operation createAccount has changed param options doc Service payment-provider-spi operation createAccount has changed description Service payment-provider-spi has a new operation createTransaction Service payment-provider-spi message createAccountOptions member Credentials was removed Service payment-provider-spi message createAccountOptions has a new member credentials Service payment-provider-spi has a new message createTransactionOptions Service payment-provider-spi has a new message createTransactionResponse
issues:
Message createTransactionOptions has an unknown property type object (payment-provider-spi.js (77))
ERROR: The @description tag requires a value. File: payment-provider-spi.js, line: 58