DocWorks for payment-provider-spi - 6 changes detected, but 4 issue detected changes: Service payment-provider-spi operation createAccount was removed Service payment-provider-spi has a new operation connectAccount Service payment-provider-spi message CreateAccountOptions was removed Service payment-provider-spi message CreateAccountResponse was removed Service payment-provider-spi has a new message ConnectAccountOptions Service payment-provider-spi has a new message ConnectAccountResponse
issues:
Message CreateTransactionOptions has an unknown property type object (payment-provider-spi.js (73))
Message CreateRefundOptions has an unknown property type object (payment-provider-spi.js (187))
ERROR: The @description tag requires a value. File: payment-provider-spi.js, line: 58
ERROR: The @description tag requires a value. File: payment-provider-spi.js, line: 164