DocWorks for wix-store-backend - 2 changes detected, but 1 issue detected changes: Service wix-stores-backend.Events was removed Service wix-stores-backend was removed
issues:
ERROR: Unable to find the source file or directory /Users/samm/Documents/repos/elementory-dynamic-modules/wix-stores-backend/dist/src