DocWorks for wix-members - 2 changes detected, but 3 issue detected changes: Service wix-members.CurrentMember message ContactDetails member customFields was removed Service wix-members.CurrentMember message ContactDetails has a new member undefined
issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (161))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: Unable to parse a tag's type expression for source file /Users/imnotashrimp/gitRepos/velo-docs/wix-members/velo-docs/api/members_shared.js with tag title "property" and text "{[wix-members.CurrentMember.CustomField]} customFields Set of key-value pairs.
Custom fields,
where each key is the field key,
and each value is the field's value for the member.": Invalid type expression "[wix-members.CurrentMember.CustomField]": Expected "!", "$", "'", "(", "*", ".", "...", "0", "?", "@", "Function", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "null", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "true", "try", "typeof", "undefined", "var", "void", "while", "with", "yield", "{", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but "[" found.