DocWorks for wix-data - 11 changes detected, but 26 issue detected changes: Service DataHooks was removed Service wix-data.Hooks operation afterAggregate has changed return doc Service wix-data.Hooks operation beforeAggregate has changed param context type Service wix-data.Hooks operation beforeAggregate has changed return type Service wix-data.Hooks operation beforeAggregate has changed description Service wix-data.Hooks has a new operation afterDistinct Service wix-data.Hooks has a new operation beforeDistinct Service wix-data operation get has changed description Service wix-data operation query has changed description Service wix-data operation queryReferenced has changed description Service wix-data.WixDataDistinct is new
issues:
Operation filter has an unknown param type WixDataFilter (distinct.js (44))
Operation eq has an unknown param type * (filterMixin.js (33))
Operation ne has an unknown param type * (filterMixin.js (59))
Operation hasSome has an unknown param type * (filterMixin.js (342))
Operation hasAll has an unknown param type * (filterMixin.js (378))
Operation beforeAggregate is defined two or more times (hooks.js (313, 337))
Operation beforeAggregate has an unknown return type WixDataAggregate (hooks.js (313))
Operation beforeAggregate has an unknown return type WixDataAggregate (hooks.js (313))
Operation beforeDistinct has an unknown return type WixDataDistinct (hooks.js (395))
Operation beforeDistinct has an unknown return type WixDataDistinct (hooks.js (395))
Operation onFailure has an unknown param type Error (hooks.js (608))
Operation truncate has an unknown return type null (data-api.js (451))
Message WixDataBulkRemoveResult has an unknown property type Error (data-api.js (485))
Message WixDataBulkResult has an unknown property type Error (data-api.js (877))
ERROR: The @snippet tag - file 'velo-docs/examples/WixDataDistinct-getFilter.es6' not found. File: distinct.js line: 29
ERROR: The @snippet tag - file 'velo-docs/examples/WixDataDistinct ...