Ran updated version of docworks to enable scopes
* DocWorks for wixcode-crm - 1 change detected
changes:
Service wix-crm has changed extra.scopes

* DocWorks for wix-crm-backend - 1 change detected, but 3 issue detected
changes:
Service wix-crm-backend has changed extra.scopes

issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

* DocWorks for wix-data - no significant changes detected, but 7 issue detected

issues:
Operation eq has an unknown param type * (filterMixin.js (33))
Operation ne has an unknown param type * (filterMixin.js (59))
Operation hasSome has an unknown param type * (filterMixin.js (342))
Operation hasAll has an unknown param type * (filterMixin.js (380))
Operation onFailure has an unknown param type Error (hooks.js (490))
Message WixDataBulkRemoveResult has an unknown property type Error (data-api.js (363))
Message WixDataBulkResult has an unknown property type Error (data-api.js (723))

* DocWorks for wixcode-users - 1 change detected, but 1 issue detected
changes:
Service wix-users has changed extra.scopes

issues:
Message RegistrationOptions has an unknown property type wix-crm.ContactInfo (users.js (743))

* DocWorks for wix-users-backend - no significant changes detected, but 3 issue detected

issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (537))
Message RegistrationResult has an unknown property type wix-users.User (users.js (34))
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 65

* DocWorks for wix-members-backend - 1 change detected
changes:
Service wix-members-backend.CurrentMember operation getMember has changed return doc

Co-authored-by: Tova Rosenstein <talyaro@wix.com>