DocWorks for wix-ui-santa - 14 changes detected, but 80 issue detected changes: Service $w.AddressInput property filter has changed description Service $w.AddressInput property filter.examples[0] has changed body Service $w.AddressInput property value link [value](#value) was removed Service $w.AddressInput property value.examples[0] has changed body Service $w.AddressInput property value.examples[2] has changed title Service $w.AddressInput property value.examples[2] has changed body Service $w.AddressInput property value.examples[2] has changed extra.description Service $w.AddressInput property value.examples has 1 new examples Service $w.AddressInput message Address member addressLine was removed Service $w.AddressInput message Address.examples[0] has changed body Service $w.AddressInput message AddressFilter.examples[0] has changed body Service $w.AddressInput message AddressLocation.examples[0] has changed body Service $w.AddressInput message StreetAddress.examples[0] has changed body Service $w.Captcha has a new mixes $w.HiddenCollapsedMixin
issues:
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (37))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (6))
Mixin $w.ValueMixin not found (Slider.js (6))
Mixin $w.DisabledMixin not found (Slider.js (6))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (6))
Mixin $w.FocusMixin not found (Slider.js (6))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (568))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (607))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (646))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (683))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (10))
Mixin $w.DisabledMixin not found (TimePicker.js (10))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (10))
Mixin $w.RequiredMixin not found (TimePicker.js (10))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (10))
Mixin $w.FormElement not found (TimePicker.js (10))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (26))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Mixin $w.FormElement not found (AddressInput.js (59))
Mixin $w.DisabledMixin not found (AddressInput.js (59))
Mixin $w.RequiredMixin not found (AddressInput.js (59))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (59))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (59))
Mixin $w.FocusMixin not found (AddressInput.js (59))
Mixin $w.ClickableMixin not found (AddressInput.js (59))
Mixin $w.StyleMixin not found (AddressInput.js (59))
Operation onPlay has an unknown param type $w.EventHandler (MusicPlayer.js (587))
Operation onPause has an unknown param type $w.EventHandler (MusicPlayer.js (626))
Operation onEnded has an unknown param type $w.EventHandler (MusicPlayer.js (665))
Operation onProgress has an unknown param type $w.EventHandler (MusicPlayer.js (702))
Mixin $w.Element not found (MusicPlayer.js (9))
Mixin $w.HiddenCollapsedMixin not found (MusicPlayer.js (9))
Callback VerifiedHandler has an unknown return type Void (Captcha.js (205))
Mixin $w.Element not found (Captcha.js (6))
Mixin $w.FocusMixin not found (Captcha.js (6))
Mixin $w.HiddenCollapsedMixin not found (Captcha.js (6))
Property style has an unknown type $w.Style (ProgressBar.js (42))
Mixin $w.Element not found (ProgressBar.js (17))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (17))
Mixin $w.StyleMixin not found (ProgressBar.js (17))
Operation setAttribute param value has a name but no type. Did you forget the {} around the type? (CustomElement.js (16))
Mixin $w.Element not found (CustomElement.js (5))
Mixin $w.HiddenCollapsedMixin not found (CustomElement.js (5))
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-wix.es6' not found. File: VideoPlayer.js line: 663
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-youtube.es6' not found. File: VideoPlayer.js line: 663
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-vimeo.es6' not found. File: VideoPlayer.js line: 663
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-twitch.es6' not found. File: VideoPlayer.js line: 663
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-dailymotion.es6' not found. File: VideoPlayer.js line: 663
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-mp4.es6' not found. File: VideoPlayer.js line: 663