DocWorks for wix-crm-backend - 4 changes detected, but 1 issue detected changes: Service wix-crm-backend.invoices was removed Service wix-crm-backend.price-quotes was removed Service wix-crm-backend.tasks was removed Service wix-crm-backend was removed
issues:
ERROR: Unable to find the source file or directory /Users/samm/Documents/repos/elementory-dynamic-modules/wix-crm-backend/dist/src