Scopes added for Velodocs modules
* DocWorks for wix-events - no significant changes detected

* DocWorks for wix-captcha-backend - 1 change detected
changes:
Service wix-captcha-backend has changed extra.scopes

* DocWorks for wix-configs-backend - no significant changes detected, but 1 issue detected

issues:
Operation getPackageConfig has an unknown return type * (config.js (21))

* DocWorks for wix-bookings-backend - no significant changes detected, but 3 issue detected

issues:
Operation eq has an unknown param type * (SessionQueryBuilder.js (121))
Operation ne has an unknown param type * (SessionQueryBuilder.js (146))
Operation eq has an unknown param type * (WixBookingsQueryBuilder.js (50))

* DocWorks for dbsm-viewer-app - 1 change detected, but 3 issue detected
changes:
Service wix-dataset has changed extra.scopes

issues:
Operation setFieldValue has an unknown param type * (datasetApi.js (390))
Operation setSort has an unknown param type wix-data.WixDataSort (datasetApi.js (934))
Operation setFilter has an unknown param type wix-data.WixDataFilter (datasetApi.js (993))

* DocWorks for wix-events-backend - 1 change detected, but 2 issue detected
changes:
Service wix-events-backend has changed extra.scopes

issues:
Operation eq has an unknown param type * (event-query.js (34))
Operation ne has an unknown param type * (event-query.js (63))

* DocWorks for wix-media-manager-backend - 1 change detected, but 1 issue detected
changes:
Service wix-media-backend has changed extra.scopes

issues:
Operation upload has an unknown param type Buffer (upload.js (1))

* DocWorks for wix-members - 1 change detected, but 1 issue detected
changes:
Service wix-members has changed extra.scopes

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (154))

* DocWorks for wix-members-backend - no significant changes detected

* DocWorks for wix-paid-plans - 2 changes detected
changes:
Service wix-paid-plans-backend has changed extra.scopes
Service wix-paid-plans has changed extra.scopes

* DocWorks for wix-pricing-plans-backend - 1 change detected, but 2 issue detected
changes:
Service wix-pricing-plans-backend has changed extra.scopes

issues:
Operation eq has an unknown param type * (plan-queries.js (43))
Operation ne has an unknown param type * (plan-queries.js (73))

* DocWorks for wix-realtime-backend - no significant changes detected, but 1 issue detected

issues:
Operation publish has an unknown param type * (publisher.js (78))

* DocWorks for wixcode-stores - no significant changes detected

* DocWorks for wix-users-backend - no significant changes detected, but 2 issue detected

issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (538))
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 66

* DocWorks for js-wixcode-sdk - 4 changes detected, but 10 issue detected
changes:
Service wix-location has changed extra.scopes
Service wix-site has changed extra.scopes
Service wix-storage has changed extra.scopes
Service wix-window has changed extra.scopes

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (101))
Property data has an unknown type * (HtmlComponentMessageEvent.js (20))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (227))
Operation get has an unknown return type * (window.js (261))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.js (88))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

* DocWorks for js-wixcode-sdk - no significant changes detected, but 10 issue detected

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (101))
Property data has an unknown type * (HtmlComponentMessageEvent.js (20))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (227))
Operation get has an unknown return type * (window.js (261))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.js (88))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

* DocWorks for wix-pay - 1 change detected
changes:
Service wix-pay has changed extra.scopes

Co-authored-by: Gita Stern <gitas@wix.com>