DocWorks for wix-ui-santa - 112 changes detected, but 93 issue detected changes: Service $w.AddressInput has changed summary Service $w.AddressInput property filter has changed setter Service $w.AddressInput property filter has changed summary Service $w.AddressInput property filter has changed description Service $w.AddressInput property filter.examples[0] has changed title Service $w.AddressInput property filter.examples[0] has changed body Service $w.AddressInput property filter.examples[1] has changed title Service $w.AddressInput property filter.examples[1] has changed body Service $w.AddressInput property placeholder has changed setter Service $w.AddressInput property placeholder has changed description Service $w.AddressInput property placeholder.examples[0] has changed body Service $w.AddressInput property value has changed setter Service $w.AddressInput property value has changed description Service $w.AddressInput property value.examples[0] has changed body Service $w.AddressInput property value.examples[1] has changed body Service $w.AddressInput property value.examples has 2 examples removed Service $w.AddressInput message Address member formatted has changed doc Service $w.AddressInput message Address member streetAddress was removed Service $w.AddressInput message Address member city was removed Service $w.AddressInput message Address member subdivision was removed Service $w.AddressInput message Address member country has changed type Service $w.AddressInput message Address member postalCode has changed type Service $w.AddressInput message Address has a new member streetNumber Service $w.AddressInput message Address has a new member route Service $w.AddressInput message Address has a new member locality Service $w.AddressInput message Address has a new member adminArea1 Service $w.AddressInput message Address has a new member adminArea2 Service $w.AddressInput message Address.examples[0] has changed body Service $w.AddressInput message Address.examples[1] has changed body Service $w.AddressInput message AddressFilter member country has changed doc Service $w.AddressInput message AddressFilter member country has changed optional Service $w.AddressInput message AddressFilter has changed summary Service $w.AddressInput message AddressFilter link [filter](#filter) was removed Service $w.AddressInput message AddressFilter.examples[0] has changed title Service $w.AddressInput message AddressFilter.examples[0] has changed body Service $w.AddressInput message AddressFilter.examples has 1 examples removed Service $w.AddressInput message AddressLocation link [value](#value) was removed Service $w.AddressInput message AddressLocation.examples[0] has changed body Service $w.AddressInput message StreetAddress was removed Service $w.AddressInput has a new message AddressStreetNumber Service $w.AddressInput has a new message AddressRoute Service $w.AddressInput has a new message AddressLocality Service $w.AddressInput has a new message AddressAdminArea1 Service $w.AddressInput has a new message AddressAdminArea2 Service $w.AddressInput has a new message AddressCountry Service $w.AddressInput has a new message AddressPostalCode Service $w.AddressInput has a new message AddressBias Service $w.AddressInput has changed extra.queryable Service $w.Captcha mixes $w.Element was removed Service $w.Captcha mixes $w.FocusMixin was removed Service $w.Captcha mixes $w.HiddenCollapsedMixin was removed Service $w.Captcha has changed summary Service $w.Captcha has changed description Service $w.Captcha property token was removed Service $w.Captcha operation onError has changed param name from handler to cb Service $w.Captcha operation onError has changed param cb type Service $w.Captcha operation onError has changed param cb doc Service $w.Captcha operation onError has changed return type Service $w.Captcha operation onError has changed return doc Service $w.Captcha operation onError has changed summary Service $w.Captcha operation onError has changed description Service $w.Captcha operation onError has a new link [onError( )](#onError) Service $w.Captcha operation onError.examples has 1 examples removed Service $w.Captcha operation onTimeout has changed param name from handler to cb Service $w.Captcha operation onTimeout has changed param cb type Service $w.Captcha operation onTimeout has changed param cb doc Service $w.Captcha operation onTimeout has changed return type Service $w.Captcha operation onTimeout has changed return doc Service $w.Captcha operation onTimeout has changed summary Service $w.Captcha operation onTimeout has changed description Service $w.Captcha operation onTimeout has a new link [onTimeout( )](#onTimeout) Service $w.Captcha operation onTimeout.examples has 1 examples removed Service $w.Captcha operation onVerified has changed param name from handler to cb Service $w.Captcha operation onVerified has changed param cb type Service $w.Captcha operation onVerified has changed param cb doc Service $w.Captcha operation onVerified has changed return type Service $w.Captcha operation onVerified has changed return doc Service $w.Captcha operation onVerified has changed summary Service $w.Captcha operation onVerified has changed description Service $w.Captcha operation onVerified has a new link [onVerified( )](#onVerified) Service $w.Captcha operation onVerified.examples has 2 examples removed Service $w.Captcha operation reset was removed Service $w.Captcha callback ErrorHandler was removed Service $w.Captcha callback TimeoutHandler was removed Service $w.Captcha callback VerifiedHandler was removed Service $w.Captcha has changed extra.notes Service $w.Captcha has changed extra.queryable Service $w.CustomElement has changed summary Service $w.CustomElement has changed description Service $w.CustomElement property seoMarkup has changed summary Service $w.CustomElement property seoMarkup has changed description Service $w.CustomElement property seoMarkup.examples has 1 examples removed Service $w.CustomElement operation on has changed param name from callBackFunction to callback Service $w.CustomElement operation on has changed param callback doc Service $w.CustomElement operation on has changed summary Service $w.CustomElement operation on has changed description Service $w.CustomElement operation on.examples has 1 examples removed Service $w.CustomElement operation setAttribute has changed summary Service $w.CustomElement operation setAttribute has changed description Service $w.CustomElement operation setAttribute.examples has 1 examples removed Service $w.Slider has changed description Service $w.Slider property value was removed Service $w.TimePicker property value was removed Service $w.VideoPlayer operation mute.examples has 1 examples removed Service $w.VideoPlayer operation pause.examples has 1 examples removed Service $w.VideoPlayer operation play.examples has 1 examples removed Service $w.VideoPlayer operation seek.examples has 1 examples removed Service $w.VideoPlayer operation stop has changed description Service $w.VideoPlayer operation stop.examples has 1 examples removed Service $w.VideoPlayer operation togglePlay.examples has 1 examples removed Service $w.VideoPlayer operation unmute.examples has 1 examples removed Service $w.SignatureInput is new
issues:
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (37))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (6))
Mixin $w.ValueMixin not found (Slider.js (6))
Mixin $w.DisabledMixin not found (Slider.js (6))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (6))
Mixin $w.FocusMixin not found (Slider.js (6))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (604))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (643))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (682))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (719))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (10))
Mixin $w.DisabledMixin not found (TimePicker.js (10))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (10))
Mixin $w.RequiredMixin not found (TimePicker.js (10))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (10))
Mixin $w.FormElement not found (TimePicker.js (10))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (26))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Mixin $w.FormElement not found (AddressInput.js (123))
Mixin $w.DisabledMixin not found (AddressInput.js (123))
Mixin $w.RequiredMixin not found (AddressInput.js (123))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (123))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (123))
Mixin $w.FocusMixin not found (AddressInput.js (123))
Mixin $w.ClickableMixin not found (AddressInput.js (123))
Property value has an unknown type $w.Value (SignatureInput.js (74))
Property style has an unknown type $w.Style (SignatureInput.js (50))
Mixin $w.HiddenCollapsedMixin not found (SignatureInput.js (27))
Mixin $w.Element not found (SignatureInput.js (27))
Mixin $w.FormElement not found (SignatureInput.js (27))
Mixin $w.DisabledMixin not found (SignatureInput.js (27))
Mixin $w.FocusMixin not found (SignatureInput.js (27))
Mixin $w.StyleMixin not found (SignatureInput.js (27))
Mixin $w.RequiredMixin not found (SignatureInput.js (27))
Operation onPlay has an unknown param type $w.EventHandler (MusicPlayer.js (587))
Operation onPause has an unknown param type $w.EventHandler (MusicPlayer.js (626))
Operation onEnded has an unknown param type $w.EventHandler (MusicPlayer.js (665))
Operation onProgress has an unknown param type $w.EventHandler (MusicPlayer.js (702))
Mixin $w.Element not found (MusicPlayer.js (9))
Mixin $w.HiddenCollapsedMixin not found (MusicPlayer.js (9))
Operation onError has an unknown param type $w.EventHandler (Captcha.js (28))
Operation onError has an unknown return type $w.captcha (Captcha.js (28))
Operation onTimeout has an unknown param type $w.EventHandler (Captcha.js (52))
Operation onTimeout has an unknown return type $w.captcha (Captcha.js (52))
Operation onVerified has an unknown param type $w.EventHandler (Captcha.js (80))
Operation onVerified has an unknown return type $w.captcha (Captcha.js (80))
Property style has an unknown type $w.Style (ProgressBar.js (42))
Mixin $w.Element not found (ProgressBar.js (17))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (17))
Mixin $w.StyleMixin not found (ProgressBar.js (17))
Operation setAttribute param value has a name but no type. Did you forget the {} around the type? (CustomElement.js (16))
Mixin $w.Element not found (CustomElement.js (5))
Mixin $w.HiddenCollapsedMixin not found (CustomElement.js (5))
ERROR: The @snippet tag - file 'examples/VideoPlayer-description_get.es6' not found. File: VideoPlayer.js line: 503
ERROR: The @snippet tag - file 'examples/VideoPlayer-description_set.es6' not found. File: VideoPlayer.js line: 503
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-wix.es6' not found. File: VideoPlayer.js line: 703
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-youtube.es6' not found. File: VideoPlayer.js line: 703
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-vimeo.es6' not found. File: VideoPlayer.js line: 703
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-twitch.es6' not found. File: VideoPlayer.js line: 703
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-dailymotion.es6' not found. File: VideoPlayer.js line: 703
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-mp4.es6' not found. File: VideoPlayer.js line: 703
ERROR: The @snippet tag - file 'examples/Captcha-onTimeout.es6' not found. File: Captcha.js line: 93