DocWorks  - 1 change detected, but 2 issue detected changes: Service wix-dataset was removed
issues:
ERROR: Unable to parse /Users/yoava/work/wix/git/cloud/dbsm/dbsm-viewer-app/src/dataset-controller/controller.js: Unexpected token function
ERROR: Unable to parse /Users/yoava/work/wix/git/cloud/dbsm/dbsm-viewer-app/src/dataset-controller/datasetApi.js: Unexpected token function