DocWorks for js-wixcode-sdk - 32 changes detected, but 13 issue detected changes: Service $w.MultiStateBox has a new mixes $w.PlayableMixin Service $w.MultiStateBox has changed summary Service $w.MultiStateBox has changed description Service $w.MultiStateBox property currentState has changed summary Service $w.MultiStateBox property currentState.examples has 1 examples removed Service $w.MultiStateBox property states has changed summary Service $w.MultiStateBox property states has changed description Service $w.MultiStateBox property states.examples has 1 examples removed Service $w.MultiStateBox operation changeState has changed param stateReference doc Service $w.MultiStateBox operation changeState has changed return doc Service $w.MultiStateBox operation changeState has changed summary Service $w.MultiStateBox operation changeState has changed description Service $w.MultiStateBox operation changeState.examples has 5 examples removed Service $w.MultiStateBox operation onChange has changed param eventHandler doc Service $w.MultiStateBox operation onChange has changed return doc Service $w.MultiStateBox operation onChange has changed summary Service $w.MultiStateBox operation onChange has changed description Service $w.MultiStateBox operation onChange has a new link [changeState( )](#changeState) Service $w.MultiStateBox operation onChange link [`changeState( )`](#changeState) was removed Service $w.MultiStateBox operation onChange.examples has 1 examples removed Service $w.MultiStateBox operation onChange has changed extra.notes Service $w.Page has changed description Service $w.Slideshow operation onChange has changed description Service $w.Slideshow operation onChange.examples[0] has changed title Service $w.State has changed summary Service $w.State property id was removed Service $w operation onReady has changed description Service npm-modules has changed description Service wix-site operation prefetchPageResources was removed Service wix-site message PrefetchItems was removed Service wix-site message PrefetchResult was removed Service wix-site message PrefetchResultError was removed
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 346
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 354
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_set.es6' not found. File: ForegroundColorMixin.es6 line: 54
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_get.es6' not found. File: ForegroundColorMixin.es6 line: 54