DocWorks for wix-events-backend - 8 changes detected, but 3 issue detected changes: Service wix-events-backend.WixEvents has changed description Service wix-events-backend.WixEvents operation cancelEvent has changed return type Service wix-events-backend.WixEvents operation cancelEvent has changed summary Service wix-events-backend.WixEvents operation cancelEvent has changed description Service wix-events-backend.WixEvents operation cancelEvent has a new link [onEventCreated( )](#onEventCreated) Service wix-events-backend.WixEvents operation cancelEvent.examples[0] has changed body Service wix-events-backend.WixEvents message CancelEventResult_292957908554 was removed Service wix-events-backend.WixEvents message WixEvent member form has changed doc
issues:
Operation eq has an unknown param type * (wix_events_EventManagement_QueryV2_queryEvents.js (28))
Operation ne has an unknown param type * (wix_events_EventManagement_QueryV2_queryEvents.js (68))
ERROR: The @description tag requires a value. File: shared.js, line: 75