DocWorks for wix-bookings-backend - 9 changes detected, but 3 issue detected changes: Service wix-bookings-backend.resources operation updateResource has changed param name from resourceUpdateInfo to undefined Service wix-bookings-backend.resources operation updateResource has changed param undefined type Service wix-bookings-backend.resources message ResourceUpdateInfo was removed Service wix-bookings-backend.resources has a new message <TODO> Service wix-bookings-backend.schedules operation updateSchedule has changed param name from scheduleUpdateInfo to undefined Service wix-bookings-backend.schedules operation updateSchedule has changed param undefined type Service wix-bookings-backend.schedules operation updateSchedule has a new param undefined Service wix-bookings-backend.schedules message ScheduleUpdateInfo was removed Service wix-bookings-backend.schedules has a new message <TODO>
issues:
ERROR: Unable to parse a tag's type expression for source file /Users/idana/git_repos/edm-autogen-docs/wix-bookings-backend/corvid-docs/api/com.wix.bookings.schedules.api.v1.Schedules.js with tag title "param" and text "{wix-bookings-backend.schedules~<TODO>} <TODO> <TODO>": Invalid type expression "wix-bookings-backend.schedules~<TODO>": Expected "!", "#", "$", "(", "-", ".", "0", "<", "=", "?", "@", "[]", "\\", "_", "|", "‌", "‍", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter, [1-9], or end of input but "~" found.
ERROR: Unable to parse a tag's type expression for source file /Users/idana/git_repos/edm-autogen-docs/wix-bookings-backend/corvid-docs/api/com.wix.bookings.schedules.api.v1.Schedules.js with tag title "param" and text "{wix-bookings-backend.schedules~<TODO>} <TODO> <TODO>": Invalid type expression "wix-bookings-backend.schedules~<TODO>": Expected "!", "#", "$", "(", "-", ".", "0", "< ...