DocWorks for wix-realtime-backend - 31 changes detected, but 8 issue detected changes: Service wix-realtime-backend.PermissionsRouter has changed summary Service wix-realtime-backend.PermissionsRouter has changed description Service wix-realtime-backend.PermissionsRouter operation add has changed param channel doc Service wix-realtime-backend.PermissionsRouter operation add has changed param handler doc Service wix-realtime-backend.PermissionsRouter operation add has changed summary Service wix-realtime-backend.PermissionsRouter operation add has changed description Service wix-realtime-backend.PermissionsRouter operation add.examples has 2 new examples Service wix-realtime-backend.PermissionsRouter operation default has changed param handler doc Service wix-realtime-backend.PermissionsRouter operation default has changed summary Service wix-realtime-backend.PermissionsRouter operation default has changed description Service wix-realtime-backend.PermissionsRouter operation default.examples has 2 new examples Service wix-realtime-backend has changed summary Service wix-realtime-backend has changed description Service wix-realtime-backend has a new property permissionsRouter Service wix-realtime-backend operation realtime_check_permission has changed description Service wix-realtime-backend operation realtime_check_permission.examples[0] has changed body Service wix-realtime-backend operation realtime_check_permission.examples[1] has changed body Service wix-realtime-backend operation realtime_check_permission.examples[2] has changed body Service wix-realtime-backend operation realtime_check_permission.examples has 1 examples removed Service wix-realtime-backend message ChannelPermissions has a new link [default( )](wix-realtime-backend.PermissionsRouter.html#default) Service wix-realtime-backend message ChannelPermissions has a new link [add( )](wix-realtime-backend.PermissionsRouter.html#add) Service wix-realtime-backend message ChannelPermissions has a new link [realtime_check_permission( )](#realtime_check_permission) Service wix-realtime-backend message ChannelPermissions link [XXXX( )](#XXXX) was removed Service wix-realtime-backend message ChannelPermissions.examples has 3 new examples Service wix-realtime-backend message Subscriber member type has changed doc Service wix-realtime-backend message Subscriber has a new link [default( )](wix-realtime-backend.PermissionsRouter.html#default) Service wix-realtime-backend message Subscriber has a new link [add( )](wix-realtime-backend.PermissionsRouter.html#add) Service wix-realtime-backend message Subscriber has a new link [check( )](wix-realtime-backend.PermissionsRouter.html#check) Service wix-realtime-backend message Subscriber has a new link [realtime_check_permission( )](#realtime_check_permission) Service wix-realtime-backend message Subscriber link [XXXX( )](#XXXX) was removed Service wix-realtime-backend message Subscriber.examples has 2 new examples
issues:
Callback PermissionsHandler has an unknown param type wix-realtime.Channel (permissions-router.js (28))
Callback PermissionsHandler has an unknown param type wix-realtime.Subscriber (permissions-router.js (28))
Operation publish has an unknown param type * (publisher.js (62))
ERROR: The @snippet tag - file 'corvid-docs/examples/realtime-permission_check-users-router .es6' not found. File: permissions-router.js line: 13
ERROR: The @snippet tag - file 'corvid-docs/examples/realtime-permission_check-users-router .es6' not found. File: permissions-router.js line: 39
ERROR: The @snippet tag - file 'corvid-docs/examples/realtime-permission_check-users-router .es6' not found. File: permissions-router.js line: 61
ERROR: The @snippet tag - file 'corvid-docs/examples/realtime-permission_check-users-router .es6' not found. File: permissions-router.js line: 77
ERROR: The @snippet tag - file 'corvid-docs/examples/realtime-permission_check-users-router .es6' not found. File: permissions-router.js line: 148