DocWorks for mobile-elements - 15 changes detected, but 18 issue detected changes: Service $w.MobileButton is new Service $w.MobileContainer is new Service $w.MobileImage is new Service $w.MobilePicker is new Service $w.MobileRepeater is new Service $w.MobileSwitch is new Service $w.MobileText is new Service $w.MobileTextInput is new Service $w.MobileDisabledMixin is new Service $w.MobileElement is new Service $w.MobileFormElementMixin is new Service $w.MobileHiddenCollapsedMixin is new Service $w.MobileHiddenMixin is new Service $w.MobilePressableMixin is new Service $w.MobileValueMixin is new
issues:
Mixin $w.ContainableMixin not found (MobileContainer.js (1))
Operation onChange has an unknown param type $w.EventHandler (MobilePicker.js (164))
Mixin $w.LabelMixin not found (MobilePicker.js (1))
Mixin $w.LabelMixin not found (MobileTextInput.js (1))
Property parent has an unknown type $w.Node (MobileElement.js (77))
Property validateOnBlur is defined two or more times (MobileFormElement.js (48, 65))
Mixin $w.CollapsedMixin not found (MobileHiddenCollapsedMixin.js (1))
Mixin $w.HiddenMixin not found (MobileHiddenMixin.js (1))
Operation onPress has an unknown param type $w.EventHandler (MobilePressableMixin.js (61))
Operation onLongPress has an unknown param type $w.EventHandler (MobilePressableMixin.js (75))
Operation onPressIn has an unknown param type $w.EventHandler (MobilePressableMixin.js (88))
Operation onPressOut has an unknown param type $w.EventHandler (MobilePressableMixin.js (104))
Operation onChange has an unknown param type $w.EventHandler (MobileValueMixin.js (31))
Property value has an unknown type * (MobileValueMixin.js (151))
Property value has an unknown type * (MobileValueMixin.js (178))
Property validateOnChange is defined two or more times (MobileValueMixin.js (110, 125))
Property validateOnStart is defined two or more times (MobileValueMixin.js (131, 145))
ERROR: The @description tag requires a value. File: MobilePicker.js, line: 117