DocWorks for wix-members-frontend - 7 changes detected, but 3 issue detected changes: Service wix-members-frontend.Authentication operation changePassword has changed param newPassword doc Service wix-members-frontend.Authentication operation changePassword has changed param token doc Service wix-members-frontend.Authentication operation changePassword has changed description Service wix-members-frontend.Authentication operation resendVerificationCodeEmail has changed description Service wix-members-frontend.Authentication operation sendForgotPasswordEmail was removed Service wix-members-frontend.Authentication operation verifyEmail has changed param code doc Service wix-members-frontend.Authentication has a new operation sendResettPasswordEmail
issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (162))
Message ContactDetails has an unknown property type object (members_shared.js (18))
ERROR: The @snippet tag - file 'velo-docs/examples/authentication/sendResettPasswordEmail.es6' not found. File: sendResetPasswordEmail.js line: 2