DocWorks for wix-stores-backend - 8 changes detected, but 7 issue detected changes: Service wix-stores-backend operation bulkAdjustProductProperty has changed return type Service wix-stores-backend operation bulkAdjustProductProperty has changed description Service wix-stores-backend operation bulkAdjustProductProperty.examples[0] has changed body Service wix-stores-backend has a new operation bulkUpdateProductProperty Service wix-stores-backend message BulkAdjustProperties member cost has changed doc Service wix-stores-backend message BulkAdjustResponse was removed Service wix-stores-backend has a new message BulkUpdateProperties Service wix-stores-backend has a new message BulkUpdateResponse
issues:
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (635))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (635))
ERROR: The @snippet tag - file 'corvid-docs/examples/Gallery-items_set.es6' not found. File: events.js line: 245