DocWorks for wix-file-sharing-backend - 4 changes detected, but 1 issue detected changes: Service wix-file-sharing-backend has changed summary Service wix-file-sharing-backend operation getDownloadUrl was removed Service wix-file-sharing-backend message DownloadUrl was removed Service wix-file-sharing-backend message LibraryItems was removed
issues:
ERROR: Unable to parse /Users/talyaro/Documents/Repos/catalyst-server/file-sharing-server/wix-file-sharing-backend/dist/get-download-url.js: Line 59: Unexpected token function