DocWorks for wix-users-backend - 5 changes detected, but 3 issue detected changes: Service wix-users-backend operation emailUser has changed param options type Service wix-users-backend operation register has changed param options type Service wix-users-backend has a new message RegistrationOptions Service wix-users-backend has a new message ContactInfo Service wix-users-backend has a new message TriggeredEmailOptions
issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (537))
Message RegistrationResult has an unknown property type wix-users.User (users.js (34))
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 65