DocWorks for blocks-elements - 19 changes detected, but 20 issue detected changes: Service $w.Avatar has changed description Service $w.Avatar has a new property firstName Service $w.Avatar has a new property lastName Service $w.Avatar has a new property src Service $w.AvatarGroup mixes $w.DisabledMixin was removed Service $w.AvatarGroup has changed summary Service $w.AvatarGroup has changed description Service $w.AvatarGroup has a new property avatarSize Service $w.AvatarGroup has a new property maxAvatars Service $w.AvatarGroup has a new property showHiddenAvatarCount Service $w.AvatarGroup has a new property lastName Service $w.AvatarGroup has a new property src Service $w.AvatarGroup has a new property rel Service $w.AvatarGroup has a new property skin Service $w.AvatarGroup has a new property size Service $w.AvatarGroup has a new property stretched Service $w.AvatarGroup has a new property divider Service $w.AvatarGroup has a new operation onClick Service $w.AvatarGroup has a new message icon
issues:
Mixin $w.HiddenCollapsedMixin not found (Avatar.js (1))
Mixin $w.Element not found (Avatar.js (1))
Operation onClick has an unknown param type $w.EventHandler (AvatarGroup.js (273))
Operation onClick has an unknown return type $w.Element (AvatarGroup.js (273))
Property rel is defined two or more times (AvatarGroup.js (138, 174))
Mixin $w.HiddenCollapsedMixin not found (AvatarGroup.js (1))
Mixin $w.Element not found (AvatarGroup.js (1))
ERROR: The @snippet tag - file 'velo-docs/examples/AvatarGroup-size_get.es6' not found. File: AvatarGroup.js line: 27
ERROR: The @snippet tag - file 'velo-docs/examples/AvatarGroup-lastName_get.es6' not found. File: AvatarGroup.js line: 92
ERROR: The @snippet tag - file 'velo-docs/examples/AvatarGroup-lastName_set.es6' not found. File: AvatarGroup.js line: 92
ERROR: The @snippet tag - file 'velo-docs/examples/AvatarGroup-src_set.es6' not found. File: AvatarGroup.js line: 110
ERROR: The @snippet tag - file 'velo-docs/examples/AvatarG ...