DocWorks for wix-media-manager-backend - 3 changes detected, but 1 issue detected changes: Service wix-media-backend.Events was removed Service wix-media-backend.mediaManager was removed Service wix-media-backend was removed
issues:
ERROR: Unable to find the source file or directory /Users/dori/projects/docworks-fixes/elementory-dynamic-modules/wix-media-manager-backend/lib