DocWorks for wix-ui-santa - 1 change detected, but 89 issue detected changes: Service $w.RichTextBox operation onInput was removed
issues:
Operation onChange has an unknown param type $w.EventHandler (SignatureInput.js (139))
Property style has an unknown type $w.Style (SignatureInput.js (67))
Mixin $w.HiddenCollapsedMixin not found (SignatureInput.js (16))
Mixin $w.FormElement not found (SignatureInput.js (16))
Mixin $w.DisabledMixin not found (SignatureInput.js (16))
Mixin $w.FocusMixin not found (SignatureInput.js (16))
Mixin $w.StyleMixin not found (SignatureInput.js (16))
Mixin $w.RequiredMixin not found (SignatureInput.js (16))
Mixin $w.Element not found (CustomElement.js (5))
Mixin $w.HiddenCollapsedMixin not found (CustomElement.js (5))
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (37))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (6))
Mixin $w.ValueMixin not found (Slider.js (6))
Mixin $w.DisabledMixin not found (Slider.js (6))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (6))
Mixin $w.FocusMixin not found (Slider.js (6))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (622))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (661))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (700))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (737))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (12))
Mixin $w.DisabledMixin not found (TimePicker.js (12))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (12))
Mixin $w.RequiredMixin not found (TimePicker.js (12))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (12))
Mixin $w.FormElement not found (TimePicker.js (12))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (26))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Mixin $w.FormElement not found (AddressInput.js (62))
Mixin $w.DisabledMixin not found (AddressInput.js (62))
Mixin $w.RequiredMixin not found (AddressInput.js (62))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (62))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (62))
Mixin $w.FocusMixin not found (AddressInput.js (62))
Mixin $w.ClickableMixin not found (AddressInput.js (62))
Operation onPlay has an unknown param type $w.EventHandler (MusicPlayer.js (596))
Operation onPause has an unknown param type $w.EventHandler (MusicPlayer.js (635))
Operation onEnded has an unknown param type $w.EventHandler (MusicPlayer.js (674))
Operation onProgress has an unknown param type $w.EventHandler (MusicPlayer.js (711))
Mixin $w.Element not found (MusicPlayer.js (10))
Mixin $w.HiddenCollapsedMixin not found (MusicPlayer.js (10))
Mixin $w.Element not found (Captcha.js (8))
Mixin $w.FocusMixin not found (Captcha.js (8))
Mixin $w.HiddenCollapsedMixin not found (Captcha.js (8))
Property style has an unknown type $w.Style (ProgressBar.js (42))
Mixin $w.Element not found (ProgressBar.js (17))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (17))
Mixin $w.StyleMixin not found (ProgressBar.js (17))
Property style has an unknown type $w.Style (SelectionTagsList.js (228))
Mixin $w.FormElement not found (SelectionTagsList.js (44))
Mixin $w.HiddenCollapsedMixin not found (SelectionTagsList.js (44))
Mixin $w.DisabledMixin not found (SelectionTagsList.js (44))
Mixin $w.ClickableMixin not found (SelectionTagsList.js (44))
Mixin $w.StyleMixin not found (SelectionTagsList.js (44))
Mixin $w.RequiredMixin not found (SelectionTagsList.js (44))
Mixin $w.ValidatableMixin not found (SelectionTagsList.js (44))
ERROR: The @snippet tag - file 'examples/TextInputElement-onInput.es6' not found. File: RichTextBox.js line: 65
ERROR: The @snippet tag - file 'examples/TextInputElement-onInput.es6' not found. File: RichTextBox.js line: 92