DocWorks  - 29 changes detected, but 22 issue detected changes: Service $w.HiddenMixin operation hide has changed param name from animationName to effectName Service $w.HiddenMixin operation hide has changed param effectName doc Service $w.HiddenMixin operation hide has a new param effectOptions Service $w.HiddenMixin operation hide has changed return doc Service $w.HiddenMixin operation hide has changed summary Service $w.HiddenMixin operation hide has changed description Service $w.HiddenMixin operation show has changed param name from animationName to effectName Service $w.HiddenMixin operation show has changed param effectName doc Service $w.HiddenMixin operation show has a new param effectOptions Service $w.HiddenMixin operation show has changed return doc Service $w.HiddenMixin operation show has changed summary Service $w.HiddenMixin operation show has changed description Service $w.HiddenMixin has a new message ArcEffectOptions Service $w.HiddenMixin has a new message BounceEffectOptions Service $w.HiddenMixin has a new message DropEffectOptions Service $w.HiddenMixin has a new message ExpandEffectOptions Service $w.HiddenMixin has a new message FadeEffectOptions Service $w.HiddenMixin has a new message FlipEffectOptions Service $w.HiddenMixin has a new message FloatEffectOptions Service $w.HiddenMixin has a new message FlyEffectOptions Service $w.HiddenMixin has a new message FoldEffectOptions Service $w.HiddenMixin has a new message GlideEffectOptions Service $w.HiddenMixin has a new message RevealEffectOptions Service $w.HiddenMixin has a new message SlideEffectOptions Service $w.HiddenMixin has a new message SpinEffectOptions Service $w.HiddenMixin has a new message TurnEffectOptions Service $w.ToggleSwitch was removed Service wix-users operation emailUser has changed description Service wix-users message TransactionalEmailOptions member variables has changed doc
issues:
Property background is defined two or more times (document.es6 (74), Columns.es6 (61))
Operation onItemClicked is defined two or more times (BaseGallery.es6 (368), ProGallery.es6 (53))
Property scrolling is missing a type annotation (HtmlComponent.es6 (67))
Property dataFetcher is missing a type annotation (Table.es6 (428))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (95))
Callback ReadyHandler has an unknown return type void (wixCode.es6 (81))
Operation promptForgotPassword has an unknown return type void (users.es6 (332))
Operation emailUser has an unknown return type void (users.es6 (431))
Operation scrollTo has an unknown return type void (window.es6 (323))
Operation scrollBy has an unknown return type void (window.es6 (369))
Property value is defined two or more times (DropDown.es6 (227), FormElement.es6 (25))
Operation scrollTo has an unknown return type void (Node.es6 (163))
Operation collapse has an unknown return type void (CollapsedMixin.es6 (16))
Operation expand has an unknown return type void (CollapsedMixin.es6 (111))
Operation disable has an unknown return type void (DisabledMixin.es6 (10))
Operation enable has an unknown return type void (DisabledMixin.es6 (41))
Operation hide has an unknown return type void (HiddenMixin.es6 (38))
Operation show has an unknown return type void (HiddenMixin.es6 (182))
ERROR: The @snippet tag - file 'examples/HiddenMixin-FadeOptions-hide.es6' not found. File: HiddenMixin.es6 line: 71
ERROR: The @snippet tag - file 'examples/HiddenMixin-FadeOptions-hide.es6' not found. File: HiddenMixin.es6 line: 127
ERROR: The @snippet tag - file 'examples/HiddenMixin-FadeOptions.es6' not found. File: HiddenMixin.es6 line: 218
ERROR: The @snippet tag - file 'examples/HiddenMixin-FadeOptions.es6' not found. File: HiddenMixin.es6 line: 267