DocWorks for wixcode-paid-plans - 6 changes detected, but 7 issue detected changes: Service wix-paid-plans-backend.Events operation onPlanPurchased has changed param event type Service wix-paid-plans-backend.Events operation onPlanPurchased has changed description Service wix-paid-plans-backend.Events message PlanPurchaseEvent was removed Service wix-paid-plans-backend.Events has a new message PlanPurchasedEvent Service wix-paid-plans-backend.Events has a new message Price Service wix-paid-plans-backend.Events has a new message ValidFor
issues:
Operation onPlanPurchased has an unknown param type wix-crm-backend.Events.PlanPurchasedEvent (events.js (43))
Message PlanPurchasedEvent has an unknown property type wix-paid-plans-backend.Price (events.js (56))
Message PlanPurchasedEvent has an unknown property type wix-paid-plans-backend.ValidFor (events.js (56))
ERROR: The @snippet tag - file 'examples/crm-backend-Events-onPlanPurchase.es6' not found. File: events.js line: 43
ERROR: The @snippet tag - file 'examples/wix-paid-plans-backend~Events-onPlanPurchased.es6' not found. File: events.js line: 56
ERROR: The @snippet tag - file 'examples/wix-paid-plans-backend~Events-onPlanPurchased.es6' not found. File: events.js line: 76
ERROR: The @snippet tag - file 'examples/cwix-paid-plans-backend~Events-onPlanPurchased.es6' not found. File: events.js line: 86