confirmator and external calendars in
* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Bookings - removing extra modules

* Bookings - Removing the extra query folders

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Publishing Bookings Services

Publishing Bookings Services

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* new wix routers intro

* DocWorks for wix-router - 6 changes detected, but 2 issue detected
changes:
Service wix-router.WixRouterSitemapEntry is new
Service wix-router.WixRouterUser is new
Service wix-router.WixRouterRequest is new
Service wix-router.WixRouterResponse is new
Service wix-router is new
Service wix-router.WixRouterSitemapRequest is new

issues:
Operation customizeQuery has an unknown param type wix-data.WixDataQuery (router.js (300))
Operation customizeQuery has an unknown return type wix-data.WixDataQuery (router.js (300))

* Published by the Tech Writer Single Sourcing Tool

* Delete wix-router-sdk directory

* DocWorks for wix-router - no significant changes detected, but 2 issue detected

issues:
Operation customizeQuery has an unknown param type wix-data.WixDataQuery (router.js (300))
Operation customizeQuery has an unknown return type wix-data.WixDataQuery (router.js (300))

* DocWorks for wix-router - no significant changes detected, but 2 issue detected

issues:
Operation customizeQuery has an unknown param type wix-data.WixDataQuery (router.js (300))
Operation customizeQuery has an unknown return type wix-data.WixDataQuery (router.js (300))

---------

Co-authored-by: Adam Friedmann <adamfri@wix.com>
Co-authored-by: Wix Tech Writers <twsinlgesource@wix.com>
Co-authored-by: adamfri <89579857+adamfri@users.noreply.github.com>

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Moved sender-details to email-marketing-v2.

* Auto commit to autodocs-wix-email-marketing-v2 from WixDocs Server

* Auto commit to autodocs-wix-email-marketing-v2 from WixDocs Server

* Auto commit to autodocs-wix-email-marketing-v2 from WixDocs Server

* Auto commit to autodocs-wix-email-marketing-v2 from WixDocs Server

* updated ecom updateCheckout example

* Auto commit to autodocs-wix-ecom-backend from WixDocs Server

* Publishing Bookings Services

Publishing Bookings Services

* Auto commit to autodocs-wix-ecom-backend from WixDocs Server

* Auto commit to autodocs-wix-ecom-backend from WixDocs Server

* Auto commit to autodocs-wix-ecom-backend from WixDocs Server

* Auto commit to autodocs-wix-ecom-backend from WixDocs Server

* Auto commit to autodocs-wix-ecom-backend from WixDocs Server

---------

Co-authored-by: guyofeck <guyo@wix.com>
Co-authored-by: roysha-wix <62389977+roysha-wix@users.noreply.github.com>

* Updated intro for sender-details move to email-marketing.v2

* Deleting sender-details

* #buildall

---------

Co-authored-by: guyofeck <guyo@wix.com>
Co-authored-by: roysha-wix <62389977+roysha-wix@users.noreply.github.com>
Co-authored-by: AriGoldWix <95754543+AriGoldWix@users.noreply.github.com>

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* intro

* intro

* oauth

* s

* elevate

* codetalk

* empty

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* added instructions

* DocWorks for js-wixcode-sdk - 1 change detected, but 9 issue detected
changes:
Service $w.Repeater operation onItemReady has changed description

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (99))
Property data has an unknown type * (HtmlComponentMessageEvent.js (16))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (235))
Operation get has an unknown return type * (window.js (269))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

* DocWorks for js-wixcode-sdk - 1 change detected, but 9 issue detected
changes:
Service $w.Repeater operation onItemReady has changed description

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (99))
Property data has an unknown type * (HtmlComponentMessageEvent.js (16))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (235))
Operation get has an unknown return type * (window.js (269))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

* DocWorks for js-wixcode-sdk - 1 change detected, but 9 issue detected
changes:
Service $w.Repeater operation onItemReady has changed description

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (99))
Property data has an unknown type * (HtmlComponentMessageEvent.js (16))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (235))
Operation get has an unknown return type * (window.js (269))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

---------

Co-authored-by: christopherbWIX <christopherb@wix.com>
Co-authored-by: christopherbWIX <116498462+christopherbWIX@users.noreply.github.com>

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* intro update

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Fixed broken links

* fixed missing links to help center articles

* fixed missing links to help center articles

---------

Co-authored-by: Sam Markowitz <samm@wix.com>

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* flow

* flow

* order

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* update dev preview table based on menu editor changes

Co-authored-by: Adam Friedmann <adamfri@wix.com>

* deleting intro

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* Updated Workflows for doc bug day.

* DocWorks for wix-crm-backend - 73 changes detected, but 4 issue detected
changes:
Service wix-crm-backend.Workflows operation archiveCard.examples[0] has changed body
Service wix-crm-backend.Workflows operation createCard has changed param card type
Service wix-crm-backend.Workflows operation createCard has changed param card doc
Service wix-crm-backend.Workflows operation createPhase has changed param name from phase to phaseInfo
Service wix-crm-backend.Workflows operation createPhase has changed param phaseInfo type
Service wix-crm-backend.Workflows operation createPhase has changed param phaseInfo doc
Service wix-crm-backend.Workflows operation createPhase.examples[0] has changed body
Service wix-crm-backend.Workflows operation createWorkflow has changed param workflowInfo type
Service wix-crm-backend.Workflows operation createWorkflow has changed param workflowInfo doc
Service wix-crm-backend.Workflows operation deleteCard.examples[0] has changed body
Service wix-crm-backend.Workflows operation deletePhase has changed return doc
Service wix-crm-backend.Workflows operation deletePhase has changed summary
Service wix-crm-backend.Workflows operation deletePhase.examples[0] has changed body
Service wix-crm-backend.Workflows operation deleteWorkflow has changed return doc
Service wix-crm-backend.Workflows operation deleteWorkflow has changed summary
Service wix-crm-backend.Workflows operation deleteWorkflow.examples[0] has changed body
Service wix-crm-backend.Workflows operation getCard has changed param cardId doc
Service wix-crm-backend.Workflows operation getCard has changed return doc
Service wix-crm-backend.Workflows operation getCard has changed summary
Service wix-crm-backend.Workflows operation getCard.examples[0] has changed body
Service wix-crm-backend.Workflows operation getPhaseInfo has changed param phaseId doc
Service wix-crm-backend.Workflows operation getPhaseInfo has changed return doc
Service wix-crm-backend.Workflows operation getPhaseInfo has chan ...

* DocWorks for wix-crm-backend - 4 changes detected, but 5 issue detected
changes:
Service wix-crm-backend.Workflows operation listPhasesInfo has changed param options type
Service wix-crm-backend.Workflows message ListOptions.examples[0] has changed body
Service wix-crm-backend.Workflows message ListOptions.examples[1] has changed body
Service wix-crm-backend.Workflows message ListWorkflowsOptions was removed

issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
Operation listWorkflowsInfo has an unknown param type wix-crm-backend.Workflows.ListWorkflowsOptions (workflows.js (125))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

* DocWorks for wix-crm-backend - 1 change detected, but 4 issue detected
changes:
Service wix-crm-backend.Workflows operation listWorkflowsInfo has changed param options type

issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

---------

Co-authored-by: AriGoldWix <95754543+AriGoldWix@users.noreply.github.com>

* deleting intro

* Auto commit to autodocs-wix-bookings-v2 from WixDocs Server

* delete service jsons that shouldn't be published

---------

Co-authored-by: MartaBerman <martab@wix.com>
Co-authored-by: MartaBerman <50321691+MartaBerman@users.noreply.github.com>
Co-authored-by: guyofeck <guyo@wix.com>
Co-authored-by: TWSingleSource <116091643+TWSingleSource@users.noreply.github.com>
Co-authored-by: Adam Friedmann <adamfri@wix.com>
Co-authored-by: Wix Tech Writers <twsinlgesource@wix.com>
Co-authored-by: adamfri <89579857+adamfri@users.noreply.github.com>
Co-authored-by: roysha-wix <62389977+roysha-wix@users.noreply.github.com>
Co-authored-by: AriGoldWix <95754543+AriGoldWix@users.noreply.github.com>
Co-authored-by: FernandoWix <fernandow@wix.com>
Co-authored-by: FernandoWix <112631090+FernandoWix@users.noreply.github.com>
Co-authored-by: christopherbWIX <christopherb@wix.com>
Co-authored-by: christopherbWIX <116498462+christopherbWIX@users.noreply.github.com>
Co-authored-by: arielWix <arielh@wix.com>
Co-authored-by: Sam Markowitz <samm@wix.com>
Co-authored-by: Tova Rosenstein <talyaro@wix.com>
Co-authored-by: imnotashrimp <imnotashrimp@gmail.com>