[users-backend] change xref to backend
changes:
Service wix-users-backend message RegistrationResult member user has changed type

issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (537))
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 65