DocWorks for js-wixcode-sdk - 36 changes detected, but 53 issue detected changes: Service $w.CheckboxGroup property options has changed type Service $w.CheckboxGroup property selectedIndices has changed type Service $w.CheckboxGroup property value has changed type Service $w.ColumnStrip property columns has changed type Service $w.ContainableMixin property children has changed type Service $w.DatePicker property disabledDates has changed type Service $w.DatePicker property disabledDaysOfWeek has changed type Service $w.Document property children has changed type Service $w.Dropdown property options has changed type Service $w.MultiStateBox has changed summary Service $w.MultiStateBox has changed description Service $w.MultiStateBox property states has changed type Service $w.Page property keywords has changed type Service $w.RadioButtonGroup property options has changed type Service $w.Repeater property data has changed type Service $w.Repeater operation forItems has changed param itemIds type Service $w.Slideshow property slides has changed type Service $w.Slideshow operation onChange has changed extra.notes Service $w.Table property columns has changed type Service $w.Table property rows has changed type Service $w.UploadButton property value has changed type Service $w operation onReady has changed description Service npm-modules has changed description Service wix-location property path has changed type Service wix-site operation routerSitemap has changed return type Service wix-site message PrefetchItems member pages has changed type Service wix-site message PrefetchItems member lightboxes has changed type Service wix-site message PrefetchResultError member pages has changed type Service wix-site message PrefetchResultError member lightboxes has changed type Service wix-site message SiteStructure member pages has changed type Service wix-site message SiteStructure member prefixes has changed type Service wix-site message SiteStructure member lightboxes has changed type Service wix-window.multilingual property siteLanguages has changed type Service wix-window.trackingParameters message AddProductImpressionEvent member contents has changed type Service wix-window.trackingParameters message InitiateCheckoutEvent member contents has changed type Service wix-window.trackingParameters message PurchaseEvent member contents has changed type
issues:
Property children has an unknown type [ 'Array' ] (document.es6 (89))
Property options has an unknown type [ 'Array' ] (CheckboxGroup.es6 (56))
Property options has an unknown type [ 'Array' ] (CheckboxGroup.es6 (90))
Property value has an unknown type [ 'Array' ] (CheckboxGroup.es6 (141))
Property value has an unknown type [ 'Array' ] (CheckboxGroup.es6 (171))
Property selectedIndices has an unknown type [ 'Array' ] (CheckboxGroup.es6 (209))
Property selectedIndices has an unknown type [ 'Array' ] (CheckboxGroup.es6 (237))
Property columns has an unknown type [ 'Array' ] (ColumnStrip.es6 (29))
Property disabledDates has an unknown type [ 'Array' ] (DatePicker.es6 (207))
Property disabledDates has an unknown type [ 'Array' ] (DatePicker.es6 (238))
Property disabledDaysOfWeek has an unknown type [ 'Array' ] (DatePicker.es6 (272))
Property disabledDaysOfWeek has an unknown type [ 'Array' ] (DatePicker.es6 (305))
Property options has an unknown type [ 'Array' ] (DropDown.es6 (52))
Property options has an unknown type [ 'Array' ] (DropDown.es6 (91))
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (141))
Property states has an unknown type [ 'Array' ] (MultiStateBox.es6 (209))
Property keywords has an unknown type [ 'Array' ] (Page.es6 (63))
Property options has an unknown type [ 'Array' ] (RadioButtonGroup.es6 (50))
Property options has an unknown type [ 'Array' ] (RadioButtonGroup.es6 (88))
Operation forItems has an unknown param type [ 'Array' ] (Repeater.es6 (647))
Property data has an unknown type [ 'Array' ] (Repeater.es6 (277))
Property data has an unknown type [ 'Array' ] (Repeater.es6 (376))
Property slides has an unknown type [ 'Array' ] (Slideshow.es6 (229))
Property columns has an unknown type [ 'Array' ] (Table.es6 (391))
Property columns has an unknown type [ 'Array' ] (Table.es6 (427))
Property rows has an unknown type [ 'Array' ] (Table.es6 (580))
Property rows has an unknown type [ 'Array' ] (Table.es6 (620))
Property value has an unknown type [ 'Array' ] (UploadButton.es6 (190))
Property value has an unknown type [ 'Array' ] (UploadButton.es6 (221))
Property path has an unknown type [ 'Array' ] (location.es6 (201))
Operation routerSitemap has an unknown return type [ 'Array' ] (site.es6 (102))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Message SiteStructure has an unknown property type [ 'Array' ] (site.es6 (24))
Message SiteStructure has an unknown property type [ 'Array' ] (site.es6 (24))
Message SiteStructure has an unknown property type [ 'Array' ] (site.es6 (24))
Message PrefetchItems has an unknown property type [ 'Array' ] (site.es6 (281))
Message PrefetchItems has an unknown property type [ 'Array' ] (site.es6 (281))
Message PrefetchResultError has an unknown property type [ 'Array' ] (site.es6 (308))
Message PrefetchResultError has an unknown property type [ 'Array' ] (site.es6 (308))
Message AddProductImpressionEvent has an unknown property type [ 'Array' ] (window.es6 (731))
Message InitiateCheckoutEvent has an unknown property type [ 'Array' ] (window.es6 (824))
Message PurchaseEvent has an unknown property type [ 'Array' ] (window.es6 (849))
Property siteLanguages has an unknown type [ 'Array' ] (window.es6 (1247))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property children has an unknown type [ 'Array' ] (ContainableMixin.es6 (18))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 381
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389