DocWorks for js-wixcode-sdk - 5 changes detected, but 13 issue detected changes: Service $w operation onReady has changed description Service wix-site operation prefetchPageResources was removed Service wix-site message PrefetchItems was removed Service wix-site message PrefetchResult was removed Service wix-site message PrefetchResultError was removed
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 381
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_set.es6' not found. File: ForegroundColorMixin.es6 line: 54
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_get.es6' not found. File: ForegroundColorMixin.es6 line: 54