DocWorks for wix-events-backend - 3 changes detected, but 3 issue detected changes: Service wix-events-backend.WixEvents operation cancelEvent has changed description Service wix-events-backend.WixEvents operation cancelEvent has a new link [onEventCreated( )](wix-events-backend/events/oneventcreated) Service wix-events-backend.WixEvents operation cancelEvent link [onEventCreated( )](#onEventCreated) was removed
issues:
Operation eq has an unknown param type * (wix_events_EventManagement_QueryV2_queryEvents.js (28))
Operation ne has an unknown param type * (wix_events_EventManagement_QueryV2_queryEvents.js (68))
ERROR: The @description tag requires a value. File: shared.js, line: 75