DocWorks for wix-store-backend - 3 changes detected, but 4 issue detected changes: Service wix-stores-backend.Events operation onNewOrder has changed description Service wix-stores-backend.Events message CartRecoveredEvent member createdTime was removed Service wix-stores-backend.Events message CartRecoveredEvent has a new member creationTime
issues:
Message ProductOptionsAvailability has an unknown property type $w.ProductPage.StoreProductOptions (products.js (26))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.ImageItem (products.js (26))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.VideoItem (products.js (26))
ERROR: The @snippet tag - file 'examples/Stores-backend-Events-onCartCompleted.es6' not found. File: events.js line: 205