DocWorks for wix-members-backend - no significant changes detected, but 4 issue detected
issues:
Message Counter is defined two or more times (setActivityCounters.js (1), shared.js (9))
ERROR: The @snippet tag - file 'velo-docs/examples/getActivityCounters.es6' not found. File: getActivityCounters.js line: 7
ERROR: The @snippet tag - file 'velo-docs/examples/queryActivityCounters.es6' not found. File: queryActivityCounters.js line: 60
ERROR: The @snippet tag - file 'velo-docs/examples/setActivityCounters.es6' not found. File: setActivityCounters.js line: 25