DocWorks for js-wixcode-sdk - 18 changes detected, but 13 issue detected changes: Service site-monitoring.LogEntry has changed description Service site-monitoring.LogEntry property logName was removed Service site-monitoring.LogEntry property operation has changed extra.notes Service site-monitoring.LogEntry property severity has changed description Service site-monitoring.LogEntry property sourceLocation.examples[0] has changed title Service site-monitoring.LogEntry property sourceLocation.examples[0] has changed body Service site-monitoring.LogEntry property sourceLocation.examples[1] has changed title Service site-monitoring.LogEntry property sourceLocation.examples[1] has changed body Service site-monitoring.LogEntry property sourceLocation.examples has 1 examples removed Service site-monitoring.LogEntry property sourceLocation has changed extra.notes Service site-monitoring.LogEntry message LogEntryOperation has changed extra.notes Service site-monitoring.LogEntry message LogEntrySourceLocation has changed summary Service site-monitoring.LogEntry message LogEntrySourceLocation.examples[0] has changed title Service site-monitoring.LogEntry message LogEntrySourceLocation.examples[0] has changed body Service site-monitoring.LogEntry message LogEntrySourceLocation.examples[1] has changed title Service site-monitoring.LogEntry message LogEntrySourceLocation.examples[1] has changed body Service site-monitoring.LogEntry message LogEntrySourceLocation.examples has 1 examples removed Service site-monitoring has changed description
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (234))
Property center is defined two or more times (GoogleMap.es6 (158, 193))
Property zoom is defined two or more times (GoogleMap.es6 (210, 234))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (106, 141))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (140))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 346
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 354
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_set.es6' not found. File: ForegroundColorMixin.es6 line: 54
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_get.es6' not found. File: ForegroundColorMixin.es6 line: 54