DocWorks for wix-members-backend - 4 changes detected, but 4 issue detected changes: Service wix-activity-counters-backend has changed description Service wix-activity-counters-backend message ActivityCounter_11406213787 was removed Service wix-activity-counters-backend message Counter_2291860331 was removed Service wix-activity-counters-backend has a new message ActivityCounter
issues:
Message Counter is defined two or more times (setActivityCounters.js (1), shared.js (9))
ERROR: The @snippet tag - file 'velo-docs/examples/getActivityCounters.es6' not found. File: getActivityCounters.js line: 7
ERROR: The @snippet tag - file 'velo-docs/examples/queryActivityCounters.es6' not found. File: queryActivityCounters.js line: 60
ERROR: The @snippet tag - file 'velo-docs/examples/setActivityCounters.es6' not found. File: setActivityCounters.js line: 25