DocWorks for doc_stores_cat_write - 28 changes detected, but 11 issue detected changes: Service wix-stores-backend operation createProduct has changed return type Service wix-stores-backend operation getProductOptionsAvailability has changed param choices type Service wix-stores-backend operation updateProductFields has changed return type Service wix-stores-backend operation updateVariantData has changed param variantInfo type Service wix-stores-backend operation updateVariantData has changed return type Service wix-stores-backend operation updateVariantData has changed description Service wix-stores-backend message ProductChoices member optionKey has changed doc Service wix-stores-backend message ProductChoices has changed summary Service wix-stores-backend message ProductChoices link [getProductOptionsAvailability( )](#getProductOptionsAvailability) was removed Service wix-stores-backend message ProductChoices link [getProductVariants( )](#getProductVariants) was removed Service wix-stores-backend message ProductChoices.examples has 2 examples removed Service wix-stores-backend message ProductInfo member discount has changed type Service wix-stores-backend message ProductInfo member productOptions has changed type Service wix-stores-backend message ProductOptionsAvailability member productOptions has changed type Service wix-stores-backend message ProductVariantOptions member choices has changed type Service wix-stores-backend message VariantInfo has changed summary Service wix-stores-backend message VariantInfo.examples has 1 examples removed Service wix-stores-backend message VariantItem has changed summary Service wix-stores-backend message VariantItem.examples has 1 examples removed Service wix-stores-backend message Variants member items has changed type Service wix-stores-backend message Variants link [getProductVariants()](#getProductVariants) was removed Service wix-stores-backend has a new message Product Service wix-stores-backend has a new message ProductVariants Service wix-stores-backend has a new message ProductCustomTextFields Service wix-stores-backend has a new message ProductAdditionalInfoSection Service wix-stores-backend has a new message ProductRibbon Service wix-stores-backend has a new message ProductDiscount Service wix-stores-backend has a new message ProductOptions
issues:
Operation onProductUpdated is defined two or more times (events.js (245, 267))
Message ProductUpdatedEvent is defined two or more times (events.js (259, 281))
Operation updateVariantData has an unknown param type wix-stores-backend.ProductVariantInfo (products.js (422))
Message Product has an unknown property type $w.Gallery.ImageItem (products.js (18))
Message Product has an unknown property type $w.Gallery.VideoItem (products.js (18))
Message ProductVariants has an unknown property type wix-stores-backend.ProductVariantItem (products.js (52))
Message ProductOptions has an unknown property type wix-stores-backend.ProductOption (products.js (120))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.ImageItem (products.js (130))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.VideoItem (products.js (130))
ERROR: The @snippet tag - file 'corvid-docs/examples/ProductPage-getProduct.es6' not found. File: products.js line: 18
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-getProductVariants_choices.es6' not found. File: products.js line: 242