DocWorks for js-wixcode-sdk - 36 changes detected, but 11 issue detected changes: Service $w.CheckboxGroup property options has changed type Service $w.CheckboxGroup property selectedIndices has changed type Service $w.CheckboxGroup property value has changed type Service $w.ColumnStrip property columns has changed type Service $w.ContainableMixin property children has changed type Service $w.DatePicker property disabledDates has changed type Service $w.DatePicker property disabledDaysOfWeek has changed type Service $w.Document property children has changed type Service $w.Dropdown property options has changed type Service $w.MultiStateBox has changed summary Service $w.MultiStateBox has changed description Service $w.MultiStateBox property states has changed type Service $w.Page property keywords has changed type Service $w.RadioButtonGroup property options has changed type Service $w.Repeater property data has changed type Service $w.Repeater operation forItems has changed param itemIds type Service $w.Slideshow property slides has changed type Service $w.Slideshow operation onChange has changed extra.notes Service $w.Table property columns has changed type Service $w.Table property rows has changed type Service $w.UploadButton property value has changed type Service $w operation onReady has changed description Service npm-modules has changed description Service wix-location property path has changed type Service wix-site operation routerSitemap has changed return type Service wix-site message PrefetchItems member pages has changed type Service wix-site message PrefetchItems member lightboxes has changed type Service wix-site message PrefetchResultError member pages has changed type Service wix-site message PrefetchResultError member lightboxes has changed type Service wix-site message SiteStructure member pages has changed type Service wix-site message SiteStructure member prefixes has changed type Service wix-site message SiteStructure member lightboxes has changed type Service wix-window.multilingual property siteLanguages has changed type Service wix-window.trackingParameters message AddProductImpressionEvent member contents has changed type Service wix-window.trackingParameters message InitiateCheckoutEvent member contents has changed type Service wix-window.trackingParameters message PurchaseEvent member contents has changed type
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 397