DocWorks for wix-forum-backend - 2 changes detected, but 23 issue detected changes: Service wix-forum-backend.Events is new Service wix-forum-backend is new
issues:
Operation onCommentDownvoted has an unknown param type wix-forum-backend.Events.DownvotedComment (events.js (619))
Message UpvotedComment is defined two or more times (events.js (634, 634))
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostCreated.es6' not found. File: events.js line: 175
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostUpdated.es6' not found. File: events.js line: 197
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostDeleted.es6' not found. File: events.js line: 219
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostMoved.es6' not found. File: events.js line: 240
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostLiked.es6' not found. File: events.js line: 263
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostUnliked.es6' not found. File: events.js line: 284
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostPinned.es6' not found. File: events.js line: 305
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostUnpinned.es6' not found. File: events.js line: 326
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostOpened.es6' not found. File: events.js line: 347
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostClosed.es6' not found. File: events.js line: 369
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onPostReported.es6' not found. File: events.js line: 391
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onCommentCreated.es6' not found. File: events.js line: 444
ERROR: The @snippet tag - file 'corvid-docs/examples/Forum-backend-Events-onCommentUpd ...