DocWorks for js-wixcode-sdk - 53 changes detected, but 13 issue detected changes: Service $w.AccountNavBar has changed extra.queryable Service $w.Anchor has changed extra.queryable Service $w.Box has changed extra.queryable Service $w.Button has changed extra.queryable Service $w.Checkbox has changed extra.queryable Service $w.CheckboxGroup has changed extra.queryable Service $w.Column has changed extra.queryable Service $w.ColumnStrip has changed extra.queryable Service $w.Container has changed extra.queryable Service $w.DatePicker has changed extra.queryable Service $w.Document has changed extra.queryable Service $w.Dropdown has changed extra.queryable Service $w.Footer has changed extra.queryable Service $w.Gallery has changed extra.queryable Service $w.GoogleMap has changed extra.queryable Service $w.Header has changed extra.queryable Service $w.HtmlComponent has changed extra.queryable Service $w.IFrame has changed extra.queryable Service $w.Image has changed extra.queryable Service $w.MediaBox has changed extra.queryable Service $w.MenuContainer has changed extra.queryable Service $w.Page has changed extra.queryable Service $w.QuickActionBar has changed extra.queryable Service $w.RadioButtonGroup has changed extra.queryable Service $w.Repeater has changed extra.queryable Service $w.Slide has changed extra.queryable Service $w.Slideshow has changed extra.queryable Service $w.Table has changed extra.queryable Service $w.Text has changed extra.queryable Service $w.TextBox has changed extra.queryable Service $w.TextInput has changed extra.queryable Service $w.UploadButton has changed extra.queryable Service $w.VectorImage has changed extra.queryable Service $w.VerticalMenu has changed extra.queryable Service $w.Video has changed extra.queryable Service site-monitoring.LogEntry has changed description Service site-monitoring.LogEntry property logName was removed Service site-monitoring.LogEntry property operation has changed extra.notes Service site-monitoring.LogEntry property severity has changed description Service site-monitoring.LogEntry property sourceLocation.examples[0] has changed title Service site-monitoring.LogEntry property sourceLocation.examples[0] has changed body Service site-monitoring.LogEntry property sourceLocation.examples[1] has changed title Service site-monitoring.LogEntry property sourceLocation.examples[1] has changed body Service site-monitoring.LogEntry property sourceLocation.examples has 1 examples removed Service site-monitoring.LogEntry property sourceLocation has changed extra.notes Service site-monitoring.LogEntry message LogEntryOperation has changed extra.notes Service site-monitoring.LogEntry message LogEntrySourceLocation has changed summary Service site-monitoring.LogEntry message LogEntrySourceLocation.examples[0] has changed title Service site-monitoring.LogEntry message LogEntrySourceLocation.examples[0] has changed body Service site-monitoring.LogEntry message LogEntrySourceLocation.examples[1] has changed title Service site-monitoring.LogEntry message LogEntrySourceLocation.examples[1] has changed body Service site-monitoring.LogEntry message LogEntrySourceLocation.examples has 1 examples removed Service site-monitoring has changed description
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 346
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 354
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_set.es6' not found. File: ForegroundColorMixin.es6 line: 54
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_get.es6' not found. File: ForegroundColorMixin.es6 line: 54