DocWorks  - 53 changes detected, but 22 issue detected changes: Service $w.Box property style was removed Service $w.Footer property style was removed Service $w.Gallery property currentItem has changed type Service $w.Gallery property items has changed type Service $w.Gallery property items has changed description Service $w.Gallery message GalleryCapabilities has a new link [galleryCapabilities](#galleryCapabilities) Service $w.Gallery message GalleryCapabilities link [`galleryCapabilities`](#galleryCapabilities) was removed Service $w.Gallery message GalleryItem was removed Service $w.Gallery has a new message VideoItem Service $w.Gallery has a new message ImageItem Service $w.Gallery has a new message TextItem Service $w.GalleryItemChangedEvent property item has changed type Service $w.Header property style was removed Service $w.HiddenMixin message ArcEffectOptions was removed Service $w.HiddenMixin message BounceEffectOptions was removed Service $w.HiddenMixin message DropEffectOptions was removed Service $w.HiddenMixin message ExpandEffectOptions was removed Service $w.HiddenMixin message FadeEffectOptions was removed Service $w.HiddenMixin message FlipEffectOptions was removed Service $w.HiddenMixin message FloatEffectOptions was removed Service $w.HiddenMixin message FlyEffectOptions was removed Service $w.HiddenMixin message FoldEffectOptions was removed Service $w.HiddenMixin message GlideEffectOptions was removed Service $w.HiddenMixin message RevealEffectOptions was removed Service $w.HiddenMixin message SlideEffectOptions was removed Service $w.HiddenMixin message SpinEffectOptions was removed Service $w.HiddenMixin message TurnEffectOptions was removed Service $w.Pagination property currentPage has changed description Service $w.Shape was removed Service $w.Table property pagination has changed type Service $w.Table property pagination has changed summary Service $w.Table property pagination has changed description Service $w.Table message PaginationParam was removed Service $w.Table has a new message PaginationOptions Service $w.TextBox property inputType was removed Service $w.ToggleSwitch was removed Service wix-users has changed summary Service wix-users has changed description Service wix-users has a new operation register Service wix-users message TransactionalEmailOptions was removed Service wix-users has a new message RegistrationOptions Service wix-users has a new message RegistrationResult Service wix-window message AddPaymentInfoEvent was removed Service wix-window message AddProductImpressionEvent was removed Service wix-window message AddToCartEvent was removed Service wix-window message ClickProductEvent was removed Service wix-window message CustomEvent was removed Service wix-window message InitiateCheckoutEvent was removed Service wix-window message PurchaseEvent was removed Service wix-window message RemoveFromCartEvent was removed Service wix-window message ViewContentEvent was removed Service wix-crm is new Service wix-users-backend is new
issues:
Property background is defined two or more times (document.es6 (69), Columns.es6 (55))
Property scrolling is missing a type annotation (HtmlComponent.es6 (76))
Property dataFetcher is missing a type annotation (Table.es6 (475))
Operation emailContact has an unknown param type wix-crm.TriggeredEmailOptions (crm.es6 (91))
Operation emailContact has an unknown return type void (crm.es6 (91))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (98))
Operation promptForgotPassword has an unknown return type void (users.es6 (380))
Operation emailUser has an unknown return type void (users.es6 (487))
Operation scrollTo has an unknown return type void (window.es6 (321))
Operation scrollBy has an unknown return type void (window.es6 (371))
Operation openModal has an unknown return type void (window.es6 (781))
Callback ReadyHandler has an unknown return type void (wixCode.es6 (77))
Property value is defined two or more times (DropDown.es6 (245), FormElement.es6 (20))
Operation scrollTo has an unknown return type void (Node.es6 (161))
Operation collapse has an unknown return type void (CollapsedMixin.es6 (16))
Operation expand has an unknown return type void (CollapsedMixin.es6 (111))
Operation disable has an unknown return type void (DisabledMixin.es6 (10))
Operation enable has an unknown return type void (DisabledMixin.es6 (41))
Operation hide has an unknown return type void (HiddenMixin.es6 (38))
Operation show has an unknown return type void (HiddenMixin.es6 (187))
ERROR: The @snippet tag - file 'examples/Crm-emailContact.es6' not found. File: crm.es6 line: 109
ERROR: The @snippet tag - file 'examples/Crm-emailContact.es6' not found. File: crm.es6 line: 109