DocWorks for wix-billing-backend - 4 changes detected, but 1 issue detected changes: Service wix-billing-backend.Events was removed Service wix-billing-backend.Invoices was removed Service wix-billing-backend.PriceQuotes was removed Service wix-billing-backend was removed
issues:
ERROR: Unable to find the source file or directory /Users/martab/Repositories/elementory-dynamic-modules/wix-billing-backend/corvid-docs/api