DocWorks for wix-members-backend - no significant changes detected, but 27 issue detected
issues:
Message ApprovedMemberEvent has an unknown property type Members (events.js (47))
Message BlockMemberEvent has an unknown property type Members (events.js (72))
Message CreatedMemberEvent has an unknown property type Members (events.js (96))
Message MemberDeletedEvent has an unknown property type Members (events.js (120))
Message JoinedMemberEvent has an unknown property type Members (events.js (143))
Message LeftMemberEvent has an unknown property type Members (events.js (167))
Message MutedMemberEvent has an unknown property type Members (events.js (192))
Message MutedMemberEvent is defined two or more times (events.js (192, 216))
Message UpdatedMemberEvent has an unknown property type Members (events.js (241))
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberApproved.es6' not found. File: events.js line: 31
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberApproved.es6' not found. File: events.js line: 47
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberBlocked.es6' not found. File: events.js line: 55
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberBlocked.es6' not found. File: events.js line: 71
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberCreated.es6' not found. File: events.js line: 79
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-on.es6' not found. File: events.js line: 95
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberDeleted.es6' not found. File: events.js line: 103
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-on.es6' not found. File: events.js line: 119
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberJoinedCommunity.es6' not found. File: events.js line: 127
ERROR: The @ ...