DocWorks for js-wixcode-sdk - 5 changes detected, but 12 issue detected changes: Service $w.Page has changed description Service $w.Slide has changed description Service $w.Slideshow has changed description Service $w operation $w has changed extra.notes Service npm-modules has changed description
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (234))
Property center is defined two or more times (GoogleMap.es6 (158, 193))
Property zoom is defined two or more times (GoogleMap.es6 (210, 234))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (106, 141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 346
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 354
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_set.es6' not found. File: ForegroundColorMixin.es6 line: 54
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_get.es6' not found. File: ForegroundColorMixin.es6 line: 54