DocWorks for editor-elements - 2 changes detected, but 20 issue detected changes: Service $w.LottieEmbed was removed Service $w.Lottie is new
issues:
Mixin $w.HiddenCollapsedMixin not found (Breadcrumbs.js (1))
Mixin $w.ViewportMixin not found (Breadcrumbs.js (1))
Mixin $w.Element not found (CollapsibleTextBox.js (1))
Mixin $w.HiddenCollapsedMixin not found (CollapsibleTextBox.js (1))
Mixin $w.ClickableMixin not found (CollapsibleTextBox.js (1))
Mixin $w.Element not found (LottieEmbed.js (1))
Mixin $w.FocusMixin not found (LottieEmbed.js (1))
Mixin $w.HiddenCollapsedMixin not found (LottieEmbed.js (1))
Mixin $w.ClickableMixin not found (LottieEmbed.js (1))
Operation onViewportEnter has an unknown param type $w.EventHandler (chatbox.js (261))
Operation onViewportEnter has an unknown return type $w.Element (chatbox.js (261))
Operation onViewportLeave has an unknown param type $w.EventHandler (chatbox.js (285))
Operation onViewportLeave has an unknown return type $w.Element (chatbox.js (285))
Property parent has an unknown type $w.Node (chatbox.js (196))
Mixin $w.Element not found (chatbox.js (121))
Mixin $w.HiddenMixin not found (chatbox.js (121))
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/Lottie-play-consolelog.es6' not found. File: LottieEmbed.js line: 139
ERROR: The @snippet tag - file 'velo-docs/examples/Lottie-pause-consolelog.es6' not found. File: LottieEmbed.js line: 152
ERROR: The @snippet tag - file 'velo-docs/examples/Lottie-stop-consolelog.es6' not found. File: LottieEmbed.js line: 165