DocWorks for mobile-elements - 3 changes detected, but 16 issue detected changes: Service $w.MobilePressEvent was removed Service $w.MobilePressableMixin operation onPress has changed param handler type Service $w.MobilePressableMixin operation onPress has changed description
issues:
Mixin $w.ContainableMixin not found (MobileContainer.js (1))
Operation onChange has an unknown param type $w.EventHandler (MobilePicker.js (165))
Mixin $w.LabelMixin not found (MobilePicker.js (1))
Mixin $w.LabelMixin not found (MobileTextInput.js (1))
Property parent has an unknown type $w.Node (MobileElement.js (77))
Mixin $w.CollapsedMixin not found (MobileHiddenCollapsedMixin.js (1))
Mixin $w.HiddenMixin not found (MobileHiddenMixin.js (1))
Operation onPress has an unknown param type $w.EventHandler (MobilePressableMixin.js (61))
Operation onLongPress has an unknown param type $w.EventHandler (MobilePressableMixin.js (75))
Operation onPressIn has an unknown param type $w.EventHandler (MobilePressableMixin.js (88))
Operation onPressOut has an unknown param type $w.EventHandler (MobilePressableMixin.js (104))
Operation onChange has an unknown param type $w.EventHandler (MobileValueMixin.js (31))
Property value has an unknown type * (MobileValueMixin.js (154))
Property value has an unknown type * (MobileValueMixin.js (181))
ERROR: The @description tag requires a value. File: MobilePicker.js, line: 97
ERROR: The @description tag requires a value. File: MobilePicker.js, line: 117