DocWorks for mobile-elements - 15 changes detected, but 22 issue detected changes: Service $w.MobileButton is new Service $w.MobileContainer is new Service $w.MobileImage is new Service $w.MobilePicker is new Service $w.MobilePressEvent is new Service $w.MobileRepeater is new Service $w.MobileSwitch is new Service $w.MobileText is new Service $w.MobileTextInput is new Service $w.MobileDisabledMixin is new Service $w.MobileElement is new Service $w.MobileFormElementMixin is new Service $w.MobileHiddenCollapsedMixin is new Service $w.MobileHiddenMixin is new Service $w.MobilePressableMixin is new
issues:
Mixin $w.ContainableMixin not found (MobileContainer.js (1))
Operation onChange has an unknown param type $w.EventHandler (MobilePicker.js (254))
Property validateOnChange is defined two or more times (MobilePicker.js (213, 228))
Property validateOnStart is defined two or more times (MobilePicker.js (234, 248))
Mixin $w.LabelMixin not found (MobilePicker.js (1))
Mixin $w.ValueMixin not found (MobilePicker.js (1))
Mixin $w.Event not found (MobilePressableMixin.js (113))
Operation onItemRemoved has an unknown return type $w.Repeater (MobileRepeater.js (378))
Mixin $w.LabelMixin not found (MobileTextInput.js (1))
Property parent has an unknown type $w.Node (MobileElement.js (77))
Operation onChange has an unknown param type $w.EventHandler (MobileFormElement.js (161))
Property validateOnBlur is defined two or more times (MobileFormElement.js (97, 114))
Property validateOnChange is defined two or more times (MobileFormElement.js (120, 135))
Property validateOnStart is defined two or more times (MobileFormElement.js (141, 155))
Mixin $w.ValueMixin not found (MobileFormElement.js (1))
Mixin $w.CollapsedMixin not found (MobileHiddenCollapsedMixin.js (1))
Mixin $w.HiddenMixin not found (MobileHiddenMixin.js (1))
ERROR: The @snippet tag - file 'velo-docs/examples/DisabledMixin-disable.es6' not found. File: MobileDisabledMixin.js line: 43
ERROR: The @snippet tag - file 'velo-d ...