DocWorks for wix-ui-santa - 46 changes detected, but 76 issue detected changes: Service $w.AddressInput has a new mixes $w.StyleMixin Service $w.AddressInput property bias was removed Service $w.AddressInput property filter has changed setter Service $w.AddressInput property filter has changed description Service $w.AddressInput property filter.examples[0] has changed body Service $w.AddressInput property filter.examples[1] has changed body Service $w.AddressInput property googleMapsApiKey was removed Service $w.AddressInput property locale was removed Service $w.AddressInput property placeholder has changed setter Service $w.AddressInput property placeholder has changed description Service $w.AddressInput property value has changed setter Service $w.AddressInput property value has changed description Service $w.AddressInput property value has a new link [value](#value) Service $w.AddressInput property value.examples[0] has changed body Service $w.AddressInput property value.examples[1] has changed body Service $w.AddressInput property value.examples has 1 new examples Service $w.AddressInput message Address member formatted has changed doc Service $w.AddressInput message Address member streetNumber was removed Service $w.AddressInput message Address member route was removed Service $w.AddressInput message Address member locality was removed Service $w.AddressInput message Address member adminArea1 was removed Service $w.AddressInput message Address member adminArea2 was removed Service $w.AddressInput message Address member country has changed type Service $w.AddressInput message Address member postalCode has changed type Service $w.AddressInput message Address has a new member streetAddress Service $w.AddressInput message Address has a new member addressLine Service $w.AddressInput message Address has a new member city Service $w.AddressInput message Address has a new member subdivision Service $w.AddressInput message Address link [value](#value) was removed Service $w.AddressInput message Address.examples[0] has changed body Service $w.AddressInput message Address.examples[1] has changed body Service $w.AddressInput message AddressAdminArea1 was removed Service $w.AddressInput message AddressAdminArea2 was removed Service $w.AddressInput message AddressBias was removed Service $w.AddressInput message AddressCountry was removed Service $w.AddressInput message AddressFilter member country has changed doc Service $w.AddressInput message AddressFilter has changed summary Service $w.AddressInput message AddressFilter.examples[0] has changed body Service $w.AddressInput message AddressFilter.examples has 1 new examples Service $w.AddressInput message AddressLocality was removed Service $w.AddressInput message AddressLocation.examples[0] has changed body Service $w.AddressInput message AddressPostalCode was removed Service $w.AddressInput message AddressRoute was removed Service $w.AddressInput message AddressStreetNumber was removed Service $w.AddressInput has a new message StreetAddress Service $w.Captcha has changed summary
issues:
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (37))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (6))
Mixin $w.ValueMixin not found (Slider.js (6))
Mixin $w.DisabledMixin not found (Slider.js (6))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (6))
Mixin $w.FocusMixin not found (Slider.js (6))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (568))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (607))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (646))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (683))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (10))
Mixin $w.DisabledMixin not found (TimePicker.js (10))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (10))
Mixin $w.RequiredMixin not found (TimePicker.js (10))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (10))
Mixin $w.FormElement not found (TimePicker.js (10))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (26))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Mixin $w.FormElement not found (AddressInput.js (60))
Mixin $w.DisabledMixin not found (AddressInput.js (60))
Mixin $w.RequiredMixin not found (AddressInput.js (60))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (60))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (60))
Mixin $w.FocusMixin not found (AddressInput.js (60))
Mixin $w.ClickableMixin not found (AddressInput.js (60))
Mixin $w.StyleMixin not found (AddressInput.js (60))
Operation onPlay has an unknown param type $w.EventHandler (MusicPlayer.js (587))
Operation onPause has an unknown param type $w.EventHandler (MusicPlayer.js (626))
Operation onEnded has an unknown param type $w.EventHandler (MusicPlayer.js (665))
Operation onProgress has an unknown param type $w.EventHandler (MusicPlayer.js (702))
Mixin $w.Element not found (MusicPlayer.js (9))
Mixin $w.HiddenCollapsedMixin not found (MusicPlayer.js (9))
Callback VerifiedHandler has an unknown return type Void (Captcha.js (204))
Mixin $w.Element not found (Captcha.js (6))
Mixin $w.FocusMixin not found (Captcha.js (6))
Property style has an unknown type $w.Style (ProgressBar.js (42))
Mixin $w.Element not found (ProgressBar.js (17))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (17))
Mixin $w.StyleMixin not found (ProgressBar.js (17))
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-wix.es6' not found. File: VideoPlayer.js line: 663
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-youtube.es6' not found. File: VideoPlayer.js line: 663
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-vimeo.es6' not found. File: VideoPlayer.js line: 663
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-twitch.es6' not found. File: VideoPlayer.js line: 663
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-dailymotion.es6' not found. File: VideoPlayer.js line: 663
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-mp4.es6' not found. File: VideoPlayer.js line: 663