DocWorks for js-wixcode-sdk - 10 changes detected, but 12 issue detected changes: Service $w.HiddenMixin operation hide.examples[2] has changed title Service $w.HiddenMixin operation hide.examples[3] has changed title Service $w.HiddenMixin operation show.examples[3] has changed title Service $w.Image has changed summary Service $w.Image property tooltip has changed summary Service $w.Image property tooltip has changed description Service $w.ValueMixin property value has changed type Service $w.ValueMixin property value has changed description Service npm-modules has changed description Service wix-window operation openLightbox has changed extra.notes
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (234))
Property center is defined two or more times (GoogleMap.es6 (158, 193))
Property zoom is defined two or more times (GoogleMap.es6 (210, 234))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (106, 141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 346
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 354
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_set.es6' not found. File: ForegroundColorMixin.es6 line: 54
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_get.es6' not found. File: ForegroundColorMixin.es6 line: 54