DocWorks for wix-ui-santa - 1 change detected, but 65 issue detected changes: Service $w.VideoPlayer property src.examples[6] has changed body
issues:
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (35))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (4))
Mixin $w.ValueMixin not found (Slider.js (4))
Mixin $w.DisabledMixin not found (Slider.js (4))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (4))
Mixin $w.FocusMixin not found (Slider.js (4))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (478))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (517))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (556))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (593))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (10))
Mixin $w.DisabledMixin not found (TimePicker.js (10))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (10))
Mixin $w.RequiredMixin not found (TimePicker.js (10))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (10))
Mixin $w.FormElement not found (TimePicker.js (10))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (24))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Property placeholder is missing a type annotation (AddressInput.js (220))
Property locale is missing a type annotation (AddressInput.js (267))
Property googleMapsApiKey is missing a type annotation (AddressInput.js (334))
Mixin $w.FormElement not found (AddressInput.js (126))
Mixin $w.DisabledMixin not found (AddressInput.js (126))
Mixin $w.RequiredMixin not found (AddressInput.js (126))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (126))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (126))
Mixin $w.FocusMixin not found (AddressInput.js (126))
Mixin $w.ClickableMixin not found (AddressInput.js (126))
ERROR: The @snippet tag - file 'examples/[AddressInput-bias_get.es6=Get a preferred geographic area
for suggested address results]' not found. File: AddressInput.js line: 154
ERROR: Unable to parse a tag's type expression for source file /Users/samm/Documents/repos/wix-ui-santa/src/components/AddressInput/wixcode/AddressInput.js with tag title "type" and text "{external: String}": Invalid type expression "external: String": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter or [1-9] but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/samm/Documents/repos/wix-ui-santa/src/components/AddressInput/wixcode/AddressInput.js with tag title "type" and text "{external: String}": Invalid type expression "external: String": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter or [1-9] but " " found.
ERROR: Unable to parse a tag's type expression for source file /Users/samm/Documents/repos/wix-ui-santa/src/components/AddressInput/wixcode/AddressInput.js with tag title "type" and text "{external: String}": Invalid type expression "external: String": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter or [1-9] but " " found.
ERROR: The @snippet tag - file 'examples/[AddressInput-bias_get.es6=Get a preferred geographic area
for suggested address results]' not found. File: AddressInput.js line: 522
ERROR: The @snippet tag - file 'examples/[AddressInput-bias_set.es6=Set a preferred geographic area
for suggested address results]' not found. File: AddressInput.js line: 522