DocWorks for wixcode-seo - 1 change detected, but 4 issue detected changes: Service wix-seo is new
issues:
Property title has an unknown type $w.Style (seo.js (56))
Property structuredData is missing a type annotation (seo.js (69))
Property metaTags is missing a type annotation (seo.js (86))
ERROR: The @snippet tag - file 'examples/SEO-getLinks.es6' not found. File: seo.js line: 213