DocWorks for payment-provider-spi - 12 changes detected, but 2 issue detected changes: Service payment-provider-spi operation createAccount has changed param options type Service payment-provider-spi operation createAccount has changed return type Service payment-provider-spi operation createTransaction has changed param options type Service payment-provider-spi operation createTransaction has changed return type Service payment-provider-spi message createAccountOptions was removed Service payment-provider-spi message createAccountResponse was removed Service payment-provider-spi message createTransactionOptions was removed Service payment-provider-spi message createTransactionResponse was removed Service payment-provider-spi has a new message CreateAccountOptions Service payment-provider-spi has a new message CreateAccountResponse Service payment-provider-spi has a new message CreateTransactionOptions Service payment-provider-spi has a new message CreateTransactionResponse
issues:
Message CreateTransactionOptions has an unknown property type object (payment-provider-spi.js (77))
ERROR: The @description tag requires a value. File: payment-provider-spi.js, line: 58