Velo Portal: $w elements add Introduction
* DocWorks for js-wixcode-sdk - 19 changes detected, but 14 issue detected
changes:
Service $w.AccountNavBar has changed description
Service $w.Background has changed description
Service $w.Button has changed description
Service $w.Checkbox has changed description
Service $w.Column has changed description
Service $w.ColumnStrip has changed description
Service $w.Container has changed description
Service $w.DatePicker has changed description
Service $w.GalleryItemChangedEvent has changed description
Service $w.GalleryItemClickedEvent has changed description
Service $w.GoogleMap has changed description
Service $w.HtmlComponentMessageEvent has changed description
Service $w.IFrame has changed description
Service $w.IconMouseInEvent has changed description
Service $w.MediaBox has changed description
Service $w.QuickActionBarItemClickedEvent has changed description
Service $w.State has changed description
Service $w.Table has changed description
Service $w.VectorImage has changed description

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (97))
Property data has an unknown type * (HtmlComponentMessageEvent.js (17))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window-frontend.js (201))
Operation get has an unknown return type * (window-frontend.js (234))
Operation set has an unknown param type * (window.js (235))
Operation get has an unknown return type * (window.js (269))
Callback ViewChangeOperation is defined two or more times (AppointmentField.js (347), DatePicker.js (472))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Callback ViewChangeEventHandler is defined two or more times (AppointmentField.js (362), DatePicker.js (466))
Callback Validator has an unknown param type * (ValidatableMixin.js (143))
Property  ...

* DocWorks for wix-ui-santa - 5 changes detected, but 122 issue detected
changes:
Service $w.AddressInput has changed description
Service $w.RatingsDisplay has changed description
Service $w.RatingsInput has changed description
Service $w.RichTextBox has changed description
Service $w.Switch has changed description

issues:
Mixin $w.LabelMixin not found (AddressInput.js (50))
Mixin $w.FormElement not found (AddressInput.js (50))
Mixin $w.DisabledMixin not found (AddressInput.js (50))
Mixin $w.RequiredMixin not found (AddressInput.js (50))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (50))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (50))
Mixin $w.FocusMixin not found (AddressInput.js (50))
Mixin $w.ClickableMixin not found (AddressInput.js (50))
Mixin $w.Element not found (Captcha.js (1))
Mixin $w.FocusMixin not found (Captcha.js (1))
Mixin $w.HiddenCollapsedMixin not found (Captcha.js (1))
Mixin $w.Element not found (CustomElement.js (1))
Mixin $w.HiddenCollapsedMixin not found (CustomElement.js (1))
Operation onPlay has an unknown param type $w.EventHandler (MusicPlayer.js (348))
Operation onPause has an unknown param type $w.EventHandler (MusicPlayer.js (368))
Operation onEnded has an unknown param type $w.EventHandler (MusicPlayer.js (388))
Operation onProgress has an unknown param type $w.EventHandler (MusicPlayer.js (408))
Mixin $w.Element not found (MusicPlayer.js (1))
Mixin $w.HiddenCollapsedMixin not found (MusicPlayer.js (1))
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (32))
Mixin $w.Element not found (Pagination.js (1))
Mixin $w.DisabledMixin not found (Pagination.js (1))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (1))
Mixin $w.ClickableMixin not found (Pagination.js (1))
Mixin $w.ViewportMixin not found (Pagination.js (1))
Property style has an unknown type $w.Style (ProgressBar.js (27))
Mixin $w.Element not found (ProgressBar.js (1))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (1))
 ...

* DocWorks for wixstores-client-worker - 3 changes detected, but 9 issue detected
changes:
Service $w.CartIcon operation addToCart has changed param quantity doc
Service $w.ProductPage has changed description
Service $w.ThankYouPage has changed description

issues:
Mixin $w.Element not found (CartIcon.js (1))
Mixin $w.HiddenCollapsedMixin not found (CartIcon.js (1))
Message SeoTag has an unknown property type object (ProductPage.js (162))
Message SeoTag has an unknown property type object (ProductPage.js (162))
Mixin $w.Element not found (ProductPage.js (1))
Mixin $w.HiddenCollapsedMixin not found (ProductPage.js (1))
Mixin $w.Element not found (ThankYouPage.js (1))
Mixin $w.HiddenCollapsedMixin not found (ThankYouPage.js (1))
ERROR: The @snippet tag - file 'velo-docs/examples/ThankYouPage-getOrder_pickup.es6' not found. File: ThankYouPage.js line: 158

* DocWorks for js-wixcode-sdk - no significant changes detected, but 14 issue detected

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (97))
Property data has an unknown type * (HtmlComponentMessageEvent.js (17))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window-frontend.js (201))
Operation get has an unknown return type * (window-frontend.js (234))
Operation set has an unknown param type * (window.js (235))
Operation get has an unknown return type * (window.js (269))
Callback ViewChangeOperation is defined two or more times (AppointmentField.js (347), DatePicker.js (472))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Callback ViewChangeEventHandler is defined two or more times (AppointmentField.js (362), DatePicker.js (466))
Callback Validator has an unknown param type * (ValidatableMixin.js (143))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

* DocWorks for editor-elements - 2 changes detected, but 124 issue detected
changes:
Service $w.WixEvents has changed description
Service $w.WixFormsV2 has changed description

issues:
Mixin $w.HiddenCollapsedMixin not found (Breadcrumbs.js (1))
Mixin $w.ViewportMixin not found (Breadcrumbs.js (1))
Mixin $w.Element not found (CollapsibleTextBox.js (1))
Mixin $w.HiddenCollapsedMixin not found (CollapsibleTextBox.js (1))
Mixin $w.ClickableMixin not found (CollapsibleTextBox.js (1))
Property link has an unknown type null (DashboardButton.js (110))
Property target has an unknown type null (DashboardButton.js (116))
Property prefix has an unknown type null (DashboardButton.js (146))
Property suffix has an unknown type null (DashboardButton.js (177))
Property customClassList has an unknown type $w.CustomClassList (DashboardButton.js (205))
Property link has mismatching types for get (string) and set (string,null) (DashboardButton.js (65, 110))
Property target is defined two or more times (DashboardButton.js (116, 140))
Property prefix has mismatching types for get (string,null) and set (string) (DashboardButton.js (146, 171))
Property suffix has mismatching types for get (string,null) and set (string) (DashboardButton.js (177, 199))
Mixin $w.ClickableMixin not found (DashboardButton.js (1))
Mixin $w.DisabledMixin not found (DashboardButton.js (1))
Mixin $w.HiddenCollapsedElement not found (DashboardButton.js (1))
Property customClassList has an unknown type $w.CustomClassList (DashboardHeading.js (33))
Mixin $w.HiddenCollapsedElement not found (DashboardHeading.js (1))
Property target has an unknown type null (DashboardIconButton.js (122))
Property customClassList has an unknown type $w.CustomClassList (DashboardIconButton.js (152))
Property target has mismatching types for get (string,null) and set (string) (DashboardIconButton.js (122, 146))
Mixin $w.HiddenCollapsedElement not found (DashboardIconButton.js (1))
Mixin $w.ClickableMixin not found (DashboardIconButton.js (1) ...

* DocWorks for editor-elements - no significant changes detected, but 124 issue detected

issues:
Mixin $w.HiddenCollapsedMixin not found (Breadcrumbs.js (1))
Mixin $w.ViewportMixin not found (Breadcrumbs.js (1))
Mixin $w.Element not found (CollapsibleTextBox.js (1))
Mixin $w.HiddenCollapsedMixin not found (CollapsibleTextBox.js (1))
Mixin $w.ClickableMixin not found (CollapsibleTextBox.js (1))
Property link has an unknown type null (DashboardButton.js (110))
Property target has an unknown type null (DashboardButton.js (116))
Property prefix has an unknown type null (DashboardButton.js (146))
Property suffix has an unknown type null (DashboardButton.js (177))
Property customClassList has an unknown type $w.CustomClassList (DashboardButton.js (205))
Property link has mismatching types for get (string) and set (string,null) (DashboardButton.js (65, 110))
Property target is defined two or more times (DashboardButton.js (116, 140))
Property prefix has mismatching types for get (string,null) and set (string) (DashboardButton.js (146, 171))
Property suffix has mismatching types for get (string,null) and set (string) (DashboardButton.js (177, 199))
Mixin $w.ClickableMixin not found (DashboardButton.js (1))
Mixin $w.DisabledMixin not found (DashboardButton.js (1))
Mixin $w.HiddenCollapsedElement not found (DashboardButton.js (1))
Property customClassList has an unknown type $w.CustomClassList (DashboardHeading.js (33))
Mixin $w.HiddenCollapsedElement not found (DashboardHeading.js (1))
Property target has an unknown type null (DashboardIconButton.js (122))
Property customClassList has an unknown type $w.CustomClassList (DashboardIconButton.js (152))
Property target has mismatching types for get (string,null) and set (string) (DashboardIconButton.js (122, 146))
Mixin $w.HiddenCollapsedElement not found (DashboardIconButton.js (1))
Mixin $w.ClickableMixin not found (DashboardIconButton.js (1))
Mixin $w.DisabledMixin not found (DashboardIconButton.js (1))
Operation onTooltipLink ...

---------

Co-authored-by: ryangec <ryang@wix.com>