DocWorks for wixcode-paid-plans - 23 changes detected, but 1 issue detected changes: Service wix-paid-plans-backend.Events operation onPlanPurchased.examples[0] has changed body Service wix-paid-plans-backend.Events operation onPlanPurchased.examples[0] has changed extra.description Service wix-paid-plans-backend.Events message Order member paymentStatus has changed doc Service wix-paid-plans-backend.Events message Order member cancellationReason has changed doc Service wix-paid-plans-backend.Events message Order member cashierOrderId was removed Service wix-paid-plans-backend.Events message Order member status has changed doc Service wix-paid-plans-backend.Events message Order member orderType has changed doc Service wix-paid-plans-backend.Events message Order has a new member wixPayOrderId Service wix-paid-plans-backend.Events message Order.examples[0] has changed body Service wix-paid-plans-backend.Events message Order.examples[0] has changed extra.description Service wix-paid-plans-backend.Events message Period.examples[0] has changed body Service wix-paid-plans-backend.Events message Period.examples[0] has changed extra.description Service wix-paid-plans-backend.Events message PlanPurchasedEvent member price was removed Service wix-paid-plans-backend.Events message PlanPurchasedEvent has a new member order Service wix-paid-plans-backend.Events message PlanPurchasedEvent.examples[0] has changed body Service wix-paid-plans-backend.Events message PlanPurchasedEvent.examples[0] has changed extra.description Service wix-paid-plans-backend.Events message Price member currency has changed doc Service wix-paid-plans-backend.Events message Price.examples[0] has changed body Service wix-paid-plans-backend.Events message Price.examples[0] has changed extra.description Service wix-paid-plans-backend.Events message ValidFor.examples[0] has changed body Service wix-paid-plans-backend.Events message ValidFor.examples[0] has changed extra.description Service wix-paid-plans-backend has changed description Service wix-paid-plans operation orderPlan.examples[1] has changed body
issues:
ERROR: The @description tag requires a value. File: events.js, line: 1