DocWorks for wix-stores-backend - 54 changes detected, but 34 issue detected changes: Service wix-stores-backend operation createProduct.examples[0] has changed body Service wix-stores-backend has a new operation createOrder Service wix-stores-backend message Address member firstName was removed Service wix-stores-backend message Address member lastName was removed Service wix-stores-backend message Address member email was removed Service wix-stores-backend message Address member phone was removed Service wix-stores-backend message Address member address was removed Service wix-stores-backend message Address has a new member formatted Service wix-stores-backend message Address has a new member city Service wix-stores-backend message Address has a new member country Service wix-stores-backend message Address has a new member addressLine Service wix-stores-backend message Address has a new member addressLine2 Service wix-stores-backend message Address has a new member streetAddress Service wix-stores-backend message Address has a new member postalCode Service wix-stores-backend message Address has a new member subdivision Service wix-stores-backend message Address has changed summary Service wix-stores-backend message Address.examples has 2 examples removed Service wix-stores-backend message Cart member billingAddress has changed type Service wix-stores-backend message Cart member lineItems has changed type Service wix-stores-backend message LineItem was removed Service wix-stores-backend message MediaItem member title was removed Service wix-stores-backend message MediaItem member description was removed Service wix-stores-backend message MediaItem member type has changed doc Service wix-stores-backend message MediaItem member src has changed doc Service wix-stores-backend message MediaItem member thumbnail was removed Service wix-stores-backend message MediaItem has a new member altText Service wix-stores-backend message MediaItem has a new member externalImageUrl Service wix-stores-backend message MediaItem has changed summary Service wix-stores-backend message MediaItem.examples has 1 examples removed Service wix-stores-backend message Product.examples[0] has changed body Service wix-stores-backend message ShippingInfo was removed Service wix-stores-backend has a new message CartAddress Service wix-stores-backend has a new message CartShippingInfo Service wix-stores-backend has a new message CartLineItem Service wix-stores-backend has a new message Order Service wix-stores-backend has a new message OrderInfo Service wix-stores-backend has a new message Activities Service wix-stores-backend has a new message StreetAddress Service wix-stores-backend has a new message VatId Service wix-stores-backend has a new message ChannelInfo Service wix-stores-backend has a new message EnteredBy Service wix-stores-backend has a new message BillingInfo Service wix-stores-backend has a new message OrderShippingInfo Service wix-stores-backend has a new message ShipmentPriceData Service wix-stores-backend has a new message LineItemPriceData Service wix-stores-backend has a new message ShipmentDetails Service wix-stores-backend has a new message PickupDetails Service wix-stores-backend has a new message OrderLineItem Service wix-stores-backend has a new message Totals Service wix-stores-backend has a new message CustomField Service wix-stores-backend has a new message LineItems Service wix-stores-backend has a new message TrackingInfo Service wix-stores-backend has a new message Fulfillment Service wix-stores-backend has a new message Discount
issues:
Message CartCompletedEvent has an unknown property type wix-stores-backend.ShippingInfo (events.js (183))
Message ProductCreatedEvent has an unknown property type $w.Gallery.VideoItem (events.js (216))
Message Cart has an unknown property type wix-stores-backend.ShippingInfo (carts.js (1))
Message AppliedCoupon is defined two or more times (carts.js (32), orders.js (392))
Message BuyerInfo is defined two or more times (carts.js (52), orders.js (91))
Message Option is defined two or more times (carts.js (120), orders.js (281))
Message CustomTextField is defined two or more times (carts.js (131), orders.js (300))
Message MediaItem is defined two or more times (orders.js (289), products.js (66))
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 20
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 65
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 91
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 111
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 140
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 148
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 162
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 170
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 190
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 207
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 225
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 236
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 244
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 253
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 269
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 281
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 289
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 300
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 308
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 343
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 356
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 365
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 373
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 382
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 392
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 401