remove frontend typedef dependencies from wix-users-backend
* DocWorks for wix-users-backend - 11 changes detected, but 3 issue detected
changes:
Service wix-users-backend.Badges operation createBadge has changed summary
Service wix-users-backend.Badges operation deleteBadge has changed summary
Service wix-users-backend.Badges operation listMemberBadges has changed summary
Service wix-users-backend.Badges operation listMembers has changed summary
Service wix-users-backend.Badges operation removeMembers has changed summary
Service wix-users-backend.Badges operation updateBadge has changed summary
Service wix-users-backend operation emailUser has changed param options type
Service wix-users-backend operation register has changed param options type
Service wix-users-backend has a new message RegistrationOptions
Service wix-users-backend has a new message ContactInfo
Service wix-users-backend has a new message TriggeredEmailOptions

issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (537))
Message RegistrationResult has an unknown property type wix-users.User (users.js (34))
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 65

* DocWorks for wix-users-backend - 7 changes detected, but 3 issue detected
changes:
Service wix-users-backend.Badges operation createBadge has changed summary
Service wix-users-backend.Badges operation deleteBadge has changed summary
Service wix-users-backend.Badges operation listMemberBadges has changed summary
Service wix-users-backend.Badges operation listMembers has changed summary
Service wix-users-backend.Badges operation removeMembers has changed summary
Service wix-users-backend.Badges operation updateBadge has changed summary
Service wix-users-backend.Badges operation updateBadge has changed description

issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (537))
Message RegistrationResult has an unknown property type wix-users.User (users.js (34))
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 65

* DocWorks for wix-users-backend - 1 change detected, but 3 issue detected
changes:
Service wix-users-backend.Badges operation updateBadge has changed description

issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (537))
Message RegistrationResult has an unknown property type wix-users.User (users.js (34))
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 65

Co-authored-by: Adam Friedmann <adamfri@wix.com>