DocWorks for wix-members-backend - 1 change detected, but 3 issue detected changes: Service wix-activity-counters-backend operation getActivityCounters.examples has 1 new examples
issues:
Message Counter is defined two or more times (setActivityCounters.js (1), shared.js (9))
ERROR: The @snippet tag - file 'velo-docs/examples/queryActivityCounters.es6' not found. File: queryActivityCounters.js line: 60
ERROR: The @snippet tag - file 'velo-docs/examples/setActivityCounters.es6' not found. File: setActivityCounters.js line: 25