[members, members-backend] fix customFields structure
* DocWorks for wix-members - 2 changes detected, but 2 issue detected
changes:
Service wix-members.CurrentMember message ContactDetails member customFields has changed type
Service wix-members.CurrentMember has a new message CustomField

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (161))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wix-members - 2 changes detected, but 3 issue detected
changes:
Service wix-members.CurrentMember message ContactDetails member customFields was removed
Service wix-members.CurrentMember message ContactDetails has a new member undefined

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (161))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: Unable to parse a tag's type expression for source file /Users/imnotashrimp/gitRepos/velo-docs/wix-members/velo-docs/api/members_shared.js with tag title "property" and text "{[wix-members.CurrentMember.CustomField]} customFields Set of key-value pairs.
Custom fields,
where each key is the field key,
and each value is the field's value for the member.": Invalid type expression "[wix-members.CurrentMember.CustomField]": Expected "!", "$", "'", "(", "*", ".", "...", "0", "?", "@", "Function", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "null", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "true", "try", "typeof", "undefined", "var", "void", "while", "with", "yield", "{", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but "[" found.

* DocWorks for wix-members - 2 changes detected, but 2 issue detected
changes:
Service wix-members.CurrentMember message ContactDetails member undefined was removed
Service wix-members.CurrentMember message ContactDetails has a new member customFields

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (161))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wix-members - 1 change detected, but 2 issue detected
changes:
Service wix-members.CurrentMember message ContactDetails member customFields has changed doc

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (163))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wix-members-backend - 3 changes detected
changes:
Service wix-members-backend.Members message ContactDetails member customFields has changed type
Service wix-members-backend.Members message ContactDetails member customFields has changed doc
Service wix-members-backend.Members has a new message CustomField

* DocWorks for wix-members-backend - 1 change detected
changes:
Service wix-members-backend.Members message ContactDetails member customFields has changed doc

* DocWorks for wix-members - 1 change detected, but 2 issue detected
changes:
Service wix-members.CurrentMember message ContactDetails member customFields has changed doc

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (163))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wix-members-backend - 9 changes detected
changes:
Service wix-members-backend.CurrentMember operation getMember.examples[0] has changed body
Service wix-members-backend.CurrentMember operation makeProfilePrivate.examples[0] has changed body
Service wix-members-backend.CurrentMember operation makeProfilePublic.examples[0] has changed body
Service wix-members-backend.CurrentMember operation updateSlug.examples[0] has changed body
Service wix-members-backend.Members operation getMember.examples[0] has changed body
Service wix-members-backend.Members operation updateMember.examples[0] has changed body
Service wix-members-backend.Members message ContactDetails member customFields has changed doc
Service wix-members-backend.Members message Image member _id has changed doc
Service wix-members-backend has changed description

* DocWorks for wix-members-backend - 1 change detected
changes:
Service wix-members-backend has changed description

* DocWorks for wix-members - 8 changes detected, but 3 issue detected
changes:
Service wix-members.CurrentMember operation getMember.examples[0] has changed body
Service wix-members.CurrentMember operation makeProfilePrivate.examples[0] has changed body
Service wix-members.CurrentMember operation makeProfilePublic.examples[0] has changed body
Service wix-members.CurrentMember message ContactDetails member customFields has changed type
Service wix-members.CurrentMember message ContactDetails member customFields has changed doc
Service wix-members.CurrentMember message CustomField was removed
Service wix-members.CurrentMember message Image member _id has changed doc
Service wix-members has changed description

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (163))
Message ContactDetails has an unknown property type object (members_shared.js (18))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wix-members - 1 change detected, but 3 issue detected
changes:
Service wix-members.CurrentMember message ContactDetails member customFields has changed doc

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (164))
Message ContactDetails has an unknown property type object (members_shared.js (18))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wix-members - 3 changes detected, but 3 issue detected
changes:
Service wix-members.CurrentMember operation getMember.examples[0] has changed body
Service wix-members.CurrentMember operation makeProfilePrivate.examples[0] has changed body
Service wix-members.CurrentMember operation makeProfilePublic.examples[0] has changed body

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (164))
Message ContactDetails has an unknown property type object (members_shared.js (18))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wix-members-backend - 10 changes detected, but 1 issue detected
changes:
Service wix-members-backend.CurrentMember operation getMember.examples[0] has changed body
Service wix-members-backend.CurrentMember operation makeProfilePrivate.examples[0] has changed body
Service wix-members-backend.CurrentMember operation makeProfilePublic.examples[0] has changed body
Service wix-members-backend.CurrentMember operation updateSlug.examples[0] has changed body
Service wix-members-backend.Members operation getMember.examples[0] has changed body
Service wix-members-backend.Members operation updateMember.examples[0] has changed body
Service wix-members-backend.Members message ContactDetails member customFields has changed type
Service wix-members-backend.Members message ContactDetails member customFields has changed doc
Service wix-members-backend.Members message CustomField was removed
Service wix-members-backend has changed description

issues:
Message ContactDetails has an unknown property type object (members_shared.js (18))

* DocWorks for wix-members-backend - 2 changes detected, but 1 issue detected
changes:
Service wix-members-backend.Members message Image member _id has changed doc
Service wix-members-backend has changed description

issues:
Message ContactDetails has an unknown property type object (members_shared.js (18))

* DocWorks for wix-members - 2 changes detected, but 3 issue detected
changes:
Service wix-members.CurrentMember message Image member _id has changed doc
Service wix-members has changed description

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (164))
Message ContactDetails has an unknown property type object (members_shared.js (18))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wix-members - 1 change detected, but 3 issue detected
changes:
Service wix-members has changed description

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (164))
Message ContactDetails has an unknown property type object (members_shared.js (18))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wix-members-backend - 1 change detected, but 1 issue detected
changes:
Service wix-members-backend has changed description

issues:
Message ContactDetails has an unknown property type object (members_shared.js (18))

Co-authored-by: Wix Docs Feds <wix-docs-feds@wix.com>