DocWorks for wix-crm-backend - 5 changes detected, but 1 issue detected changes: Service wix-crm-backend.Events was removed Service wix-crm-backend.invoices was removed Service wix-crm-backend.price-quotes was removed Service wix-crm-backend.tasks was removed Service wix-crm-backend was removed
issues:
ERROR: Unable to find the source file or directory /home/builduser/agent00/work/bb0dbed81ed35a80/wix-crm-backend/dist/src