DocWorks for wix-members - no significant changes detected, but 3 issue detected
issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (154))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/authentication.loggedIn_getCurrentMember.es6' not found. File: loggedIn.js line: 1