DocWorks for wix-crm-backend - 11 changes detected, but 15 issue detected changes: Service wix-crm-backend.Events has changed description Service wix-crm-backend.Events operation onFormSubmit has changed description Service wix-crm-backend.Events operation onFormSubmit.examples[0] has changed body Service wix-crm-backend.Events message FormSubmitEvent member field was removed Service wix-crm-backend.Events message FormSubmitEvent member attachment was removed Service wix-crm-backend.Events message FormSubmitEvent has a new member Object Service wix-crm-backend.Events message FormSubmitEvent.examples[0] has changed body Service wix-crm-backend.Events message attachment was removed Service wix-crm-backend.Events message field was removed Service wix-crm-backend.Events has a new message fields Service wix-crm-backend.Events has a new message attachments
issues:
Message attachments has an unknown property type Type (events.js (61))
Operation emailContact has an unknown param type wix-users.TriggeredEmailOptions (contacts.js (143))
Operation createInvoice has an unknown param type ICreateInvoiceRequest (invoices.js (28))
Operation createInvoice has an unknown return type wix-crm-backend.invoices.IResponse (invoices.js (28))
Operation updateInvoice has an unknown param type IIdAndVersion (invoices.js (59))
Operation updateInvoice has an unknown param type IUpdateInvoiceRequest (invoices.js (59))
Operation updateInvoice has an unknown return type wix-crm-backend.invoices.IResponse (invoices.js (59))
Operation getInvoice has an unknown return type wix-crm-backend.invoices.IInvoice (invoices.js (91))
Operation deleteInvoice has an unknown return type wix-crm-backend.invoices.IErrorResult (invoices.js (150))
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-createPriceQuote.es6' not found. File: price-quotes.js line: 28
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-createPriceQuote.es6' not found. File: price-quotes.js line: 43
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-updatePriceQuote.es6' not found. File: price-quotes.js line: 60
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-updatePriceQuote.es6' not found. File: price-quotes.js line: 76
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-deletePriceQuote.es6' not found. File: price-quotes.js line: 113
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-deletePriceQuote.es6' not found. File: price-quotes.js line: 128