DocWorks for wix-data-core - 1 change detected, but 13 issue detected changes: Service wix-data was removed
issues:
Operation eq has an unknown param type * (filterMixin.es6 (44))
Operation ne has an unknown param type * (filterMixin.es6 (73))
Operation hasSome has an unknown param type * (filterMixin.es6 (404))
Operation hasAll has an unknown param type * (filterMixin.es6 (445))
Operation onFailure has an unknown param type Error (hooks.es6 (475))
Operation count has an unknown param type wix-data.WixDataOptions (query.es6 (75))
Operation distinct has an unknown param type wix-data.WixDataOptions (query.es6 (118))
Operation find has an unknown param type wix-data.WixDataOptions (query.es6 (228))
Operation eq has an unknown param type * (filterMixin.es6 (44))
Operation hasAll has an unknown param type * (filterMixin.es6 (445))
Operation hasSome has an unknown param type * (filterMixin.es6 (404))
Operation ne has an unknown param type * (filterMixin.es6 (73))
ERROR: Unable to parse /Users/edb/repos/wix-data/wix-data-core/src/data-api.es6: Unexpected token {