DocWorks for wix-members-backend - 8 changes detected, but 34 issue detected changes: Service wix-members-backend.Events operation onMemberApproved has changed description Service wix-members-backend.Events has a new operation onMemberBlocked Service wix-members-backend.Events has a new operation onMemberCreated Service wix-members-backend.Events message ApprovedMember was removed Service wix-members-backend.Events has a new message ApprovedMemberEvent Service wix-members-backend.Events has a new message BlockedMemberEvent Service wix-members-backend.Events has a new message CreatedMemberEvent Service wix-members-backend has a new message Events~
issues:
Operation onMemberApproved has an unknown param type wix-members-backend.Events.ApprovedMember (events.js (31))
Operation on is defined two or more times (events.js (259, 259, 259, 259, 259, 259, 259))
Message ApprovedMemberEvent has an unknown property type Members (events.js (50))
Message BlockedMemberEvent has an unknown property type Members (events.js (58))
Message CreatedMemberEvent has an unknown property type Members (events.js (83))
Message Events~ is defined two or more times (events.js (251, 251, 251, 251, 251, 251, 251))
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberApproved.es6' not found. File: events.js line: 31
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberApproved.es6' not found. File: events.js line: 47
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-on.es6' not found. File: events.js line: 55
ERROR: The @snippet tag - file 'velo-docs/examples/Members-backend-Events-onMemberBlocked.es6' not found. File: events.js line: 63
ERROR: Unable to parse a tag's type expression for source file /Users/michaelho/Desktop/repos/velo-docs/wix-members-backend/velo-docs/api/events.js with tag title "param" and text "{wix-members-backend.Events~} event Information about the site member that was blocked.": Invalid type  ...