DocWorks for wix-bookings-backend - 7 changes detected, but 6 issue detected changes: Service wix-bookings-backend message PaidPlan was removed Service wix-bookings-backend message PaidPlanDetails was removed Service wix-bookings-backend message PaidPlan_11584964510 was removed Service wix-bookings-backend message PaymentDetails member paidPlanDetails was removed Service wix-bookings-backend message PaymentDetails has a new member pricingPlanDetails Service wix-bookings-backend has a new message PricingPlanDetails Service wix-bookings-backend has a new message PricingPlan
issues:
Operation eq has an unknown param type * (WixBookingsQueryBuilder.js (48))
ERROR: The @snippet tag - file 'velo-docs/examples/BookingsDataQueryResult-items.es6' not found. File: WixBookingsQueryResult.js line: 11
ERROR: The @snippet tag - file 'velo-docs/examples/BookingsQueryResult-next.es6' not found. File: WixBookingsQueryResult.js line: 123
ERROR: The @snippet tag - file 'velo-docs/examples/BookingsQueryResult-next_scenario.es6' not found. File: WixBookingsQueryResult.js line: 123
ERROR: The @snippet tag - file 'velo-docs/examples/BookingsQueryResult-hasNext.es6' not found. File: WixBookingsQueryResult.js line: 166
ERROR: The @snippet tag - file 'velo-docs/examples/BookingsQueryResult-next_scenario.es6' not found. File: WixBookingsQueryResult.js line: 166