Types fix (#67)
* DocWorks for js-wixcode-sdk - 25 changes detected, but 13 issue detected
changes:
Service $w.GoogleMap has a new property center
Service $w.GoogleMap has a new property zoom
Service $w.GoogleMap has a new property markers
Service $w.HtmlComponentMessageEvent property data has changed type
Service $w.Slideshow operation onChange has changed extra.notes
Service $w.TextInputMixin operation onInput was removed
Service $w.TextInputMixin operation onKeyPress has changed extra.notes
Service $w.UploadButton property fileType has changed description
Service npm-modules has changed description
Service site-monitoring.LogEntry message LogEntryOperation has changed description
Service site-monitoring.LogEntry message LogEntryOperation has changed extra.notes
Service wix-site message PrefetchItems member pages has changed optional
Service wix-site message PrefetchItems member lightboxes has changed optional
Service wix-site message SiteStructure member pages has changed doc
Service wix-storage.Storage has changed summary
Service wix-storage.Storage operation setItem has changed extra.notes
Service wix-storage has changed summary
Service wix-storage has changed description
Service wix-window operation copyToClipboard has changed return doc
Service wix-window operation copyToClipboard has changed summary
Service wix-window operation copyToClipboard has changed description
Service wix-window operation copyToClipboard.examples[0] has changed body
Service $w.HoverBox is new
Service $w.VideoBox is new
Service wix-events is new

issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (143))
Property data has an unknown type * (HtmlComponentMessageEvent.es6 (26))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @description tag requires a value. File: document.es6, line: 104
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 381
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389

* DocWorks for wix-router-sdk - 7 changes detected, but 2 issue detected
changes:
Service wix-router.WixRouterResponse message HeadOptions member title has changed optional
Service wix-router.WixRouterResponse message HeadOptions member description has changed optional
Service wix-router.WixRouterResponse message HeadOptions member keywords has changed optional
Service wix-router.WixRouterResponse message HeadOptions member noIndex has changed optional
Service wix-router.WixRouterResponse message HeadOptions member metaTags has changed optional
Service wix-router.WixRouterResponse message HeadOptions member links has changed optional
Service wix-router.WixRouterResponse message HeadOptions member structuredData has changed optional

issues:
Operation customizeQuery has an unknown param type wix-data.WixDataQuery (router.js (320))
Operation customizeQuery has an unknown return type wix-data.WixDataQuery (router.js (320))

* DocWorks for wix-fetch - 7 changes detected
changes:
Service wix-fetch message WixFetchRequest member method has changed doc
Service wix-fetch message WixFetchRequest member method has changed optional
Service wix-fetch message WixFetchRequest member headers has changed optional
Service wix-fetch message WixFetchRequest member body has changed optional
Service wix-fetch message WixFetchRequest has a new member mode
Service wix-fetch message WixFetchRequest has a new member credentials
Service wix-fetch message WixFetchRequest has a new member cache

* Clean up