DocWorks for wix-file-sharing-backend - 2 changes detected, but 1 issue detected changes: Service wix-file-sharing-backend message DownloadUrl was removed Service wix-file-sharing-backend message LibraryItems was removed
issues:
ERROR: Unable to parse /Users/samm/Documents/repos/catalyst-server/file-sharing-server/wix-file-sharing-backend/dist/get-download-url.js: Line 57: Unexpected token function