DocWorks for chat-worker - 22 changes detected, but 18 issue detected changes: Service $w.Chatbox operation maximize.examples has 1 new examples Service $w.Chatbox operation onMessageReceived.examples has 1 new examples Service $w.Chatbox operation onMessageSent.examples has 1 new examples Service $w.Chatbox operation sendMessage has changed param name from MessageInfo to messageInfo Service $w.Chatbox operation sendMessage has changed param messageInfo type Service $w.Chatbox message Channel has a new link [`getChannel()`](#getChannel) Service $w.Chatbox message Channel has a new link [`getChannelList()`](#getChannelList) Service $w.Chatbox message Channel link ['getChannel()'](#getChannel) was removed Service $w.Chatbox message ChannelFocusInfo has changed summary Service $w.Chatbox message ChannelFocusInfo has changed description Service $w.Chatbox message ChannelFocusInfo has a new link [`focusChannel()`](#focusChannel) Service $w.Chatbox message ChannelInfo has changed description Service $w.Chatbox message ChannelInfo has a new link [`getChannel()`](#getChannel) Service $w.Chatbox message DisplayData has a new link [`getChannel()`](#getChannel) Service $w.Chatbox message DisplayData has a new link [`getChannelList()`](#getChannelList) Service $w.Chatbox message Message has a new link [`onMessageSent()`](#onMessageSent) Service $w.Chatbox message Message has a new link [`onMessageReceived()`](#onMessageReceived) Service $w.Chatbox message MessageInfo has a new link [`sendMessage()`](#sendMessage) Service $w.Chatbox message MessagePayload has a new link [`Message`](#Message) Service $w.Chatbox message MessagePayload has a new link [`onMessageSent()`](#onMessageSent) Service $w.Chatbox message MessagePayload has a new link [`onMessageReceived()`](#onMessageReceived) Service $w.Chatbox message MessagePayload link ['Message'](#Message), ['onMessageSent()'](#onMessageSent), ['onMessageReceived()'](#onMessageReceived) was removed
issues:
Operation focusChannel has an unknown param type $w.ChannelInfo (chatApiPublic.js (221))
Operation getChannel has an unknown param type $w.ChannelInfo (chatApiPublic.js (278))
Mixin $w.Element not found (chatApiPublic.js (115))
Mixin $w.HiddenMixin not found (chatApiPublic.js (115))
ERROR: The @snippet tag - file 'examples/Chatbox-focus.es6' not found. File: chatApiPublic.js line: 171
ERROR: The @snippet tag - file 'examples/Chatbox-focus.es6' not found. File: chatApiPublic.js line: 188
ERROR: The @snippet tag - file 'examples/Chatbox-minimize.es6' not found. File: chatApiPublic.js line: 208
ERROR: The @snippet tag - file 'examples/Chatbox-minimize.es6' not found. File: chatApiPublic.js line: 220
ERROR: The @snippet tag - file 'examples/Chatbox-focus.es6' not found. File: chatApiPublic.js line: 221
ERROR: The @snippet tag - file 'examples/Chatbox-focus.es6' not found. File: chatApiPublic.js line: 233
ERROR: The @snippet tag - file 'examples/Chatbox-focus.es6' not found. File: chatApiPublic.js line: 237
ERROR: The @snippet tag - file 'examples/Chatbox-focus.es6' not found. File: chatApiPublic.js line: 248
ERROR: The @snippet tag - file 'examples/UploadButton-buttonLabel_get.es6' not found. File: chatApiPublic.js line: 262
ERROR: The @snippet tag - file 'examples/UploadButton-buttonLabel_set.es6' not found. File: chatApiPublic.js line: 262
ERROR: The @snippet tag - file 'examples/UploadButton-buttonLabel_get.es6' not found. File: chatApiPublic.js line: 275
ERROR: The @snippet tag - file 'examples/UploadButton-buttonLabel_set.es6' not found. File: chatApiPublic.js line: 275
ERROR: The @snippet tag - file 'examples/Chatbox-focus.es6' not found. File: chatApiPublic.js line: 278
ERROR: The @snippet tag - file 'examples/Chatbox-focus.es6' not found. File: chatApiPublic.js line: 298