Publish wix-applications API for Blocks
* DocWorks for wix-application - 1 change detected
changes:
Service wix-application is new

* DocWorks for wix-application - 6 changes detected, but 1 issue detected
changes:
Service wix-application has changed summary
Service wix-application has changed description
Service wix-application operation getAppInstance was removed
Service wix-application operation getDecodedAppInstance has changed return doc
Service wix-application operation getDecodedAppInstance has changed description
Service wix-application has a new operation getAppPageUrl

issues:
Operation getAppPageUrl is defined two or more times (application.js (38, 50))

* DocWorks for wix-application - 1 change detected, but 1 issue detected
changes:
Service wix-application has a new operation openAppLightbox

issues:
Operation getAppPageUrl is defined two or more times (application.js (38, 50))

* DocWorks for wix-application - 5 changes detected, but 5 issue detected
changes:
Service wix-application operation openAppLightbox has changed param name from name to lightboxId
Service wix-application operation openAppLightbox has changed param lightboxId doc
Service wix-application operation openAppLightbox has changed return type
Service wix-application operation openAppLightbox has changed return doc
Service wix-application operation openAppLightbox has changed description

issues:
Operation getAppPageUrl is defined two or more times (application.js (38, 50))
ERROR: The @snippet tag - file 'velo-docs/examples/Lightbox-close.es6' not found. File: application.js line: 63
ERROR: The @snippet tag - file 'velo-docs/examples/Lightbox-close_options.es6' not found. File: application.js line: 63
ERROR: The @snippet tag - file 'velo-docs/examples/Window-openLightbox_Hello_Lightboxes.es6' not found. File: application.js line: 63
ERROR: The @snippet tag - file 'velo-docs/examples/Lightbox-scenario.es6' not found. File: application.js line: 63

* DocWorks for wix-application - 13 changes detected
changes:
Service wix-application operation getAppInstance has changed return doc
Service wix-application operation getAppInstance has changed description
Service wix-application operation getAppPageUrl has a new param pageId
Service wix-application operation getAppPageUrl has changed return doc
Service wix-application operation getAppPageUrl has changed summary
Service wix-application operation getAppPageUrl has changed description
Service wix-application operation getAppPageUrl.examples[0] has changed title
Service wix-application operation getAppPageUrl.examples[0] has changed body
Service wix-application operation openAppLightbox has changed param lightboxId doc
Service wix-application operation openAppLightbox has changed description
Service wix-application operation openAppLightbox.examples[0] has changed title
Service wix-application operation openAppLightbox.examples[0] has changed body
Service wix-application operation openAppLightbox.examples has 3 new examples

* DocWorks for wix-application - 8 changes detected
changes:
Service wix-application operation getAppInstance has changed return doc
Service wix-application operation getAppInstance has changed summary
Service wix-application operation getAppPageUrl has changed return doc
Service wix-application operation getDecodedAppInstance has changed summary
Service wix-application operation openAppLightbox has changed summary
Service wix-application operation openAppLightbox has changed description
Service wix-application operation openAppLightbox.examples[2] has changed body
Service wix-application operation openAppLightbox.examples[3] has changed body

---------

Co-authored-by: daphneta <daphnet@wix.com>
Co-authored-by: Tova Rosenstein <42133141+talyaro@users.noreply.github.com>