DocWorks for js-wixcode-sdk - 9 changes detected, but 11 issue detected changes: Service $w.VideoBox mixes $w.AnimatableMixin was removed Service npm-modules has changed description Service wix-location property baseUrl has changed summary Service wix-location property path has changed summary Service wix-location property protocol has changed summary Service wix-location property query has changed summary Service wix-location has a new property queryParams Service wix-location operation onChange has changed description Service wix-location.QueryParams is new
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (102))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 397