DocWorks for wix-crm-backend - 15 changes detected, but 9 issue detected changes: Service wix-crm-backend.Events operation onFormSubmit.examples[0] has changed body Service wix-crm-backend.Events message FormSubmitEvent member Object was removed Service wix-crm-backend.Events message FormSubmitEvent has a new member undefined Service wix-crm-backend.Events message FormSubmitEvent has a new member attachments Service wix-crm-backend.Events message FormSubmitEvent.examples[0] has changed body Service wix-crm-backend.Events message attachments was removed Service wix-crm-backend.Events message fields was removed Service wix-crm-backend.Events has a new message FormAttachment Service wix-crm-backend.invoices operation createInvoice.examples[0] has changed body Service wix-crm-backend.invoices operation getInvoice.examples[0] has changed body Service wix-crm-backend.invoices operation updateInvoice has changed param name from id to createInvoiceRequest Service wix-crm-backend.invoices operation updateInvoice has changed param createInvoiceRequest type Service wix-crm-backend.invoices operation updateInvoice has changed param createInvoiceRequest doc Service wix-crm-backend.invoices operation updateInvoice param createInvoiceRequest was removed Service wix-crm-backend.invoices operation updateInvoice.examples[0] has changed body
issues:
Message FormAttachment has an unknown property type Type (events.js (52))
Operation emailContact has an unknown param type wix-users.TriggeredEmailOptions (contacts.js (90))
Operation createInvoice has an unknown param type ICreateInvoiceRequest (invoices.js (28))
Operation createInvoice has an unknown return type wix-crm-backend.invoices.IResponse (invoices.js (28))
Operation updateInvoice has an unknown param type IUpdateInvoiceRequest (invoices.js (59))
Operation updateInvoice has an unknown return type wix-crm-backend.invoices.IResponse (invoices.js (59))
Operation getInvoice has an unknown return type wix-crm-backend.invoices.IInvoice (invoices.js (90))
Operation deleteInvoice has an unknown return type wix-crm-backend.invoices.IErrorResult (invoices.js (149))
ERROR: Unable to parse a tag's type expression for source file /Users/samm/Documents/repos/elementory-dynamic-modules/wix-crm-backend/dist/src/events.js with tag title "property" and text "{external: Object} fields The fields in the form. The object contains key:value pairs where the key is the field name and the value is the contents of the field.": Invalid type expression "external: Object": Expected "$", "'", ".", "0", "@", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "try", "typeof", "var", "void", "while", "with", "yield", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter or [1-9] but " " found.