DocWorks for js-wixcode-sdk - 10 changes detected, but 3 issue detected changes: Service $w.IconMouseInEvent has changed summary Service $w.IconMouseInEvent has a new property label Service $w.IconMouseInEvent has a new property value Service $w callback IconMouseInEventHandler param $w was removed Service wix-window.multilingual property currentLanguage has changed summary Service wix-window.multilingual property currentLanguage has changed description Service wix-window.multilingual property currentLanguage.examples[0] has changed title Service wix-window.multilingual property currentLanguage.examples[1] has changed title Service wix-window.multilingual property siteLanguages.examples has 1 new examples Service wix-window.multilingual message SiteLanguages member locale has changed doc
issues:
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (98))
ERROR: The @snippet tag - file 'examples/Multilingual-siteLanguages.es6' not found. File: window.es6 line: 1179
ERROR: The @snippet tag - file 'examples/Multilingual-siteLanguages.es6' not found. File: window.es6 line: 1205