DocWorks for communities-blog-viewer-app - 4 changes detected, but 3 issue detected changes: Service $w.PostPage message BlogPost member coverImage has changed doc Service $w.PostPage message BlogPost has a new link [`getPost()`](#getPost) Service $w.PostPage message BlogPost link [getPost( )](#getPost) was removed Service $w.PostPage message BlogPost has changed extra.notes
issues:
Mixin $w.Element not found (post-page.js (3))
Mixin $w.HiddenCollapsedMixin not found (post-page.js (3))
ERROR: Unable to parse /Users/talyaro/Repos/app-market/communities/communities-blog-viewer-app/src/controllers/post-page.spec.js: Line 15: Unexpected token =>