DocWorks  - 90 changes detected, but 22 issue detected changes: Service $w.Background message BackgroundOptions has changed description Service $w.Checkbox property required has changed description Service $w.CollapsedMixin property collapsed has changed description Service $w.ContainableMixin has changed summary Service $w.DisabledMixin property enabled has changed description Service $w.Document message BackgroundOptions has changed description Service $w.EffectOptions was removed Service $w.FocusMixin operation blur has changed description Service $w.FocusMixin operation focus has changed description Service $w.Gallery property currentItem has changed type Service $w.Gallery property items has changed type Service $w.Gallery property items has changed description Service $w.Gallery message GalleryCapabilities has a new link [`galleryCapabilities`](#galleryCapabilities) Service $w.Gallery message GalleryCapabilities link [galleryCapabilities](#galleryCapabilities) was removed Service $w.Gallery message ImageItem was removed Service $w.Gallery message ImageItemSettings was removed Service $w.Gallery message TextItem was removed Service $w.Gallery message TextItemStyle was removed Service $w.Gallery message VideoItem was removed Service $w.GalleryItemChangedEvent property item has changed type Service $w.HiddenMixin property hidden has changed description Service $w.HiddenMixin property isVisible has changed description Service $w.HiddenMixin operation hide has changed param effectOptions type Service $w.HiddenMixin operation hide has changed description Service $w.HiddenMixin operation show has changed param effectOptions type Service $w.HiddenMixin operation show has changed description Service $w.HtmlComponent operation onMessage has changed summary Service $w.HtmlComponent operation onMessage has changed description Service $w.HtmlComponent operation postMessage has changed param name from message to msg Service $w.HtmlComponent operation postMessage has changed description Service $w.LinkableMixin property link has changed description Service $w.MouseEvent property clientX has changed description Service $w.MouseEvent property clientY has changed description Service $w.MouseEvent property offsetX has changed description Service $w.MouseEvent property offsetY has changed description Service $w.MouseEvent property pageX has changed description Service $w.MouseEvent property pageY has changed description Service $w.MouseEvent property screenX has changed description Service $w.MouseEvent property screenY has changed description Service $w.Pagination property currentPage has changed description Service $w.Pagination property totalPages has changed description Service $w.PlayableMixin operation pause has changed description Service $w.PlayableMixin operation play has changed description Service $w.Repeater property data has changed description Service $w.Repeater operation forEachItem has changed description Service $w.Repeater operation forItems has changed description Service $w.Repeater operation onItemReady has changed description Service $w.RequiredMixin property required has changed description Service $w.Slideshow operation onChange has changed description Service $w.Table property dataFetcher has changed summary Service $w.Table property pagination has changed type Service $w.Table property pagination has changed summary Service $w.Table property pagination has changed description Service $w.Table property rows has changed description Service $w.Table message PaginationOptions was removed Service $w.TextBox property wrap has changed summary Service $w.TextBox property wrap has changed description Service $w.ToggleSwitch was removed Service $w.UploadButton has changed description Service $w.UploadButton operation startUpload has changed description Service $w.ValidatableMixin operation resetValidityIndication has changed description Service $w.ValidatableMixin operation updateValidityIndication has changed summary Service $w.VectorImage has changed summary Service $w operation $w has changed param name from selector to getWixSelector Service $w operation $w has changed description Service wix-crm was removed Service wix-location operation to has changed description Service wix-pay was removed Service wix-users-backend was removed Service wix-users has changed summary Service wix-users has changed description Service wix-users operation applySessionToken was removed Service wix-users operation emailUser has changed param emailId doc Service wix-users operation emailUser has changed param options type Service wix-users operation emailUser has changed summary Service wix-users operation emailUser has changed description Service wix-users operation onLogin has changed description Service wix-users operation register was removed Service wix-users message RegistrationOptions was removed Service wix-users message RegistrationResult was removed Service wix-users message TransactionalEmailOptions member variables has changed doc Service wix-users message TriggeredEmailOptions was removed Service wix-window.trackingParameters was removed Service wix-window operation openLightbox link [openModal( )](#openModal) was removed Service wix-window operation openModal was removed Service wix-window operation postMessage was removed Service wix-window operation scrollTo has changed description Service wix-window operation trackEvent has changed param parameters type Service wix-window operation trackEvent has changed description Service wix-window message OpenModalOptions was removed
issues:
Property background is defined two or more times (document.es6 (74), Columns.es6 (61))
Operation onItemClicked is defined two or more times (BaseGallery.es6 (368), ProGallery.es6 (53))
Property scrolling is missing a type annotation (HtmlComponent.es6 (67))
Property dataFetcher is missing a type annotation (Table.es6 (447))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (95))
Callback ReadyHandler has an unknown return type void (wixCode.es6 (81))
Operation promptForgotPassword has an unknown return type void (users.es6 (332))
Operation emailUser has an unknown return type void (users.es6 (431))
Operation scrollTo has an unknown return type void (window.es6 (323))
Operation scrollBy has an unknown return type void (window.es6 (369))
Property value is defined two or more times (DropDown.es6 (227), FormElement.es6 (25))
Operation scrollTo has an unknown return type void (Node.es6 (163))
Operation collapse has an unknown return type void (CollapsedMixin.es6 (16))
Operation expand has an unknown return type void (CollapsedMixin.es6 (111))
Operation disable has an unknown return type void (DisabledMixin.es6 (10))
Operation enable has an unknown return type void (DisabledMixin.es6 (41))
Operation hide has an unknown return type void (HiddenMixin.es6 (38))
Operation show has an unknown return type void (HiddenMixin.es6 (182))
ERROR: The @snippet tag - file 'examples/HiddenMixin-FadeOptions-hide.es6' not found. File: HiddenMixin.es6 line: 71
ERROR: The @snippet tag - file 'examples/HiddenMixin-FadeOptions-hide.es6' not found. File: HiddenMixin.es6 line: 127
ERROR: The @snippet tag - file 'examples/HiddenMixin-FadeOptions.es6' not found. File: HiddenMixin.es6 line: 218
ERROR: The @snippet tag - file 'examples/HiddenMixin-FadeOptions.es6' not found. File: HiddenMixin.es6 line: 267