DocWorks for wixcode-stores - 8 changes detected, but 5 issue detected changes: Service wix-stores operation getProductVariants has changed summary Service wix-stores operation getProductVariants has changed description Service wix-stores operation getProductVariants.examples has 1 examples removed Service wix-stores message PagingOptions.examples has 1 examples removed Service wix-stores message ProductVariantOptions member paging was removed Service wix-stores message ProductVariantOptions.examples[0] has changed title Service wix-stores message ProductVariantOptions.examples[0] has changed body Service wix-stores message ProductVariantOptions.examples has 1 examples removed
issues:
Operation getCurrentCart has an unknown return type wix-stores-backend.Cart (stores.js (248))
Operation removeProductFromCart has an unknown return type wix-stores-backend.Cart (stores.js (260))
Callback CartChangedHandler has an unknown param type wix-stores-backend.Cart (stores.js (222))
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-getProductVariants_paging.es6' not found. File: stores.js line: 120
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-getProductVariants_paging.es6' not found. File: stores.js line: 144