Scopes - adding scopes
* DocWorks for wix-billing-backend - 1 change detected, but 1 issue detected
changes:
Service wix-billing-backend has changed description

issues:
scopes schema [backend]   ``` is not valid INVALID_SCOPES_SCHEMA

* DocWorks for wix-billing-backend - 2 changes detected
changes:
Service wix-billing-backend has changed description
Service wix-billing-backend has changed extra.scopes

* DocWorks for wixcode-bookings - 1 change detected
changes:
Service wix-bookings has changed extra.scopes

* DocWorks for wix-billing-backend - no significant changes detected

* DocWorks for wixcode-bookings - no significant changes detected

* DocWorks for wix-bookings-backend - 1 change detected, but 3 issue detected
changes:
Service wix-bookings-backend has changed extra.scopes

issues:
Operation eq has an unknown param type * (SessionQueryBuilder.js (121))
Operation ne has an unknown param type * (SessionQueryBuilder.js (146))
Operation eq has an unknown param type * (WixBookingsQueryBuilder.js (50))

* DocWorks for wix-configs-backend - 1 change detected, but 1 issue detected
changes:
Service wix-configs-backend has changed extra.scopes

issues:
Operation getPackageConfig has an unknown return type * (config.js (21))

* DocWorks for wix-crm-backend - no significant changes detected, but 3 issue detected

issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

* DocWorks for wixcode-crm - no significant changes detected

* DocWorks for wix-data - no significant changes detected, but 7 issue detected

issues:
Operation eq has an unknown param type * (filterMixin.js (33))
Operation ne has an unknown param type * (filterMixin.js (59))
Operation hasSome has an unknown param type * (filterMixin.js (342))
Operation hasAll has an unknown param type * (filterMixin.js (380))
Operation onFailure has an unknown param type Error (hooks.js (490))
Message WixDataBulkRemoveResult has an unknown property type Error (data-api.js (363))
Message WixDataBulkResult has an unknown property type Error (data-api.js (725))

* DocWorks for dbsm-viewer-app - no significant changes detected, but 3 issue detected

issues:
Operation setFieldValue has an unknown param type * (datasetApi.js (390))
Operation setSort has an unknown param type wix-data.WixDataSort (datasetApi.js (934))
Operation setFilter has an unknown param type wix-data.WixDataFilter (datasetApi.js (993))

* DocWorks for js-wixcode-sdk - no significant changes detected, but 10 issue detected

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (101))
Property data has an unknown type * (HtmlComponentMessageEvent.js (20))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (227))
Operation get has an unknown return type * (window.js (261))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.js (88))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

* DocWorks for wix-events - 1 change detected
changes:
Service wix-events has changed extra.scopes

* DocWorks for wix-events-backend - no significant changes detected, but 2 issue detected

issues:
Operation eq has an unknown param type * (event-query.js (34))
Operation ne has an unknown param type * (event-query.js (63))

* DocWorks for wix-groups-backend - 3 changes detected, but 10 issue detected
changes:
Service wix-groups-backend message CoverImage member imageUrl has changed doc
Service wix-groups-backend message CoverImageOptions member imageUrl has changed doc
Service wix-groups-backend has changed extra.scopes

issues:
Operation eq has an unknown param type * (createRequests.js (214))
Operation ne has an unknown param type * (createRequests.js (235))
Operation eq has an unknown param type * (groups.js (270))
Operation ne has an unknown param type * (groups.js (292))
Operation eq has an unknown param type * (joinRequests.js (211))
Operation ne has an unknown param type * (joinRequests.js (233))
Operation eq has an unknown param type * (members.js (274))
Operation ne has an unknown param type * (members.js (296))
Operation eq has an unknown param type * (members.js (739))
Operation ne has an unknown param type * (members.js (761))

* DocWorks for wix-media-manager-backend - no significant changes detected, but 1 issue detected

issues:
Operation upload has an unknown param type Buffer (upload.js (1))

* DocWorks for wix-members-backend - 1 change detected
changes:
Service wix-members-backend has changed extra.scopes

* DocWorks for wix-paid-plans - no significant changes detected

* DocWorks for wix-pay - no significant changes detected

* DocWorks for wix-pricing-plans-backend - no significant changes detected, but 2 issue detected

issues:
Operation eq has an unknown param type * (plan-queries.js (43))
Operation ne has an unknown param type * (plan-queries.js (73))

* DocWorks for wix-realtime-backend - 1 change detected, but 1 issue detected
changes:
Service wix-realtime-backend has changed extra.scopes

issues:
Operation publish has an unknown param type * (publisher.js (78))

* DocWorks for wixcode-stores - 1 change detected
changes:
Service wix-stores has changed extra.scopes

* DocWorks for wixcode-users - no significant changes detected, but 1 issue detected

issues:
Message RegistrationOptions has an unknown property type wix-crm.ContactInfo (users.js (744))

* DocWorks for wix-users-backend - 1 change detected, but 2 issue detected
changes:
Service wix-users-backend has changed extra.scopes

issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (538))
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 66

* DocWorks for wix-media-manager-backend - no significant changes detected, but 1 issue detected

issues:
Operation upload has an unknown param type Buffer (upload.js (1))

Co-authored-by: Marta Berman <martab@wix.com>