DocWorks for wix-crm-backend - 2 changes detected, but 2 issue detected changes: Service wix-crm-backend.Events operation onFormSubmit was removed Service wix-crm-backend was removed
issues:
Error: cannot create a doclet for the comment "/** * @namespace wix-crm-backend * @custom-label maturity-preview * @summary The wix-crm-backend module contains functionality for working with *  [your site's contacts](https://support.wix.com/en/article/about-your-contact-list) *  from backend code. * @description *  To use the CRM API, import `wixCrmBackend` from the `wix-crm-backend` module: * *    ```javascript *    import wixCrmBackend from 'wix-crm-backend'; *    ``` */": tags.split is not a function
    at createDoclet (/Users/roib/WebstormProjects/docworks/node_modules/jsdoc/lib/jsdoc/src/handlers.js:47:15)
    at exports.Parser.<anonymous> (/Users/roib/WebstormProjects/docworks/node_modules/jsdoc/lib/jsdoc/src/handlers.js:318:25)
    at exports.Parser.emit (events.js:223:5)
    at exports.Visitor.Visitor.visitNodeComments (/Users/roib/WebstormProjects/docworks/node_modules/jsdoc/lib/jsdoc/src/visitor.js:431:20)
    at exports.Visitor.Visitor.visit (/Users/roib/WebstormProjects/docworks/node_modules/jsdoc/lib/jsdoc/src/visitor.js:369:27)
    at exports.Walker.Walker.recurse (/Users/roib/WebstormProjects/docworks/node_modules/jsdoc/lib/jsdoc/src/walker.js:596:44)
    at exports.Parser.Parser._walkAst (/Users/roib/WebstormProjects/docworks/node_modules/jsdoc/lib/jsdoc/src/parser.js:266:18)
    at exports.Parser.Parser._parseSourceCode (/Users/roib/WebstormProjects/docworks/node_modules/jsdoc/lib/jsdoc/src/parser.js:257:18)
    at exports.Parser.Parser.parse (/Users/roib/WebstormProjects/docworks/node_modules/jsdoc/lib/jsdoc/src/parser.js:178:18)
    at Object.module.exports.cli.parseFiles (/Users/roib/WebstormProjects/docworks/node_modules/jsdoc/cli.js:356:42)
    at run (/Users/roib/WebstormProjects/docworks/docworks-jsdoc2spec/lib/jsdoc-runner.js:56:9)
    at extractCompar ...