DocWorks for wix-members-frontend - 4 changes detected, but 3 issue detected changes: Service wix-members-frontend.Authentication has a new operation changePassword Service wix-members-frontend.Authentication has a new operation resendVerificationCodeEmail Service wix-members-frontend.Authentication has a new operation sendForgotPasswordEmail Service wix-members-frontend.Authentication has a new operation verifyEmail
issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (162))
Message ContactDetails has an unknown property type object (members_shared.js (18))
ERROR: The @snippet tag - file 'velo-docs/examples/authentication/sendForgotPasswordEmail.es6' not found. File: sendForgotPasswordEmail.js line: 2