DocWorks for wix-privatemedia-backend - 3 changes detected, but 4 issue detected changes: Service wix-privatemedia-backend.Events message FileUploadedEvent member The has changed type Service wix-privatemedia-backend.Events message FileUploadedEvent member The has changed doc Service wix-privatemedia-backend.Events message FileUploadedEvent member The was removed
issues:
Message FileUploadedEvent has an unknown property type FileInfo (events.ts (42))
Message FileUploadedEvent has an unknown property type context:Object (events.ts (42))
ERROR: Unable to parse /Users/samm/Documents/repos/elementory-dynamic-modules/wix-privatemedia-backend/src/upload-media-type.ts: Line 17: Unexpected reserved word
ERROR: Unable to parse /Users/samm/Documents/repos/elementory-dynamic-modules/wix-privatemedia-backend/src/uploader.ts: Line 32: Use of future reserved word in strict mode