DocWorks for wix-ui-santa - 18 changes detected, but 88 issue detected changes: Service $w.AddressInput has changed summary Service $w.AddressInput has changed description Service $w.AddressInput has changed extra.notes Service $w.Captcha property token.examples[0] has changed body Service $w.Captcha property token.examples[1] has changed body Service $w.Captcha operation onVerified.examples[1] has changed body Service $w.Captcha operation reset.examples[1] has changed body Service $w.Pagination property currentPage has changed description Service $w.SelectionTags has a new mixes $w.ValidatableMixin Service $w.SelectionTags property options has changed description Service $w.Slider has a new mixes $w.ClickableMixin Service $w.Slider has changed description Service $w.Slider property value was removed Service $w.TimePicker property value was removed Service $w.VideoPlayer property description.examples has 2 examples removed Service $w.VideoPlayer property poster has changed summary Service $w.VideoPlayer property poster.examples has 2 examples removed Service $w.VideoPlayer property src.examples has 2 examples removed
issues:
Property style has an unknown type $w.Style (SelectionTagsList.js (229))
Mixin $w.FormElement not found (SelectionTagsList.js (44))
Mixin $w.HiddenCollapsedMixin not found (SelectionTagsList.js (44))
Mixin $w.DisabledMixin not found (SelectionTagsList.js (44))
Mixin $w.ClickableMixin not found (SelectionTagsList.js (44))
Mixin $w.StyleMixin not found (SelectionTagsList.js (44))
Mixin $w.ValidatableMixin not found (SelectionTagsList.js (44))
Mixin $w.RequiredMixin not found (SelectionTagsList.js (44))
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (37))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (6))
Mixin $w.ValueMixin not found (Slider.js (6))
Mixin $w.DisabledMixin not found (Slider.js (6))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (6))
Mixin $w.FocusMixin not found (Slider.js (6))
Mixin $w.ClickableMixin not found (Slider.js (6))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (612))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (651))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (690))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (727))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (12))
Mixin $w.DisabledMixin not found (TimePicker.js (12))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (12))
Mixin $w.RequiredMixin not found (TimePicker.js (12))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (12))
Mixin $w.FormElement not found (TimePicker.js (12))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (26))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Mixin $w.FormElement not found (AddressInput.js (62))
Mixin $w.DisabledMixin not found (AddressInput.js (62))
Mixin $w.RequiredMixin not found (AddressInput.js (62))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (62))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (62))
Mixin $w.FocusMixin not found (AddressInput.js (62))
Mixin $w.ClickableMixin not found (AddressInput.js (62))
Operation onPlay has an unknown param type $w.EventHandler (MusicPlayer.js (595))
Operation onPause has an unknown param type $w.EventHandler (MusicPlayer.js (634))
Operation onEnded has an unknown param type $w.EventHandler (MusicPlayer.js (673))
Operation onProgress has an unknown param type $w.EventHandler (MusicPlayer.js (710))
Mixin $w.Element not found (MusicPlayer.js (10))
Mixin $w.HiddenCollapsedMixin not found (MusicPlayer.js (10))
Mixin $w.Element not found (Captcha.js (8))
Mixin $w.FocusMixin not found (Captcha.js (8))
Mixin $w.HiddenCollapsedMixin not found (Captcha.js (8))
Property style has an unknown type $w.Style (ProgressBar.js (42))
Mixin $w.Element not found (ProgressBar.js (17))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (17))
Mixin $w.StyleMixin not found (ProgressBar.js (17))
Mixin $w.Element not found (CustomElement.js (5))
Mixin $w.HiddenCollapsedMixin not found (CustomElement.js (5))
ERROR: The @snippet tag - file 'examples/VideoPlayer-description_get.es6' not found. File: VideoPlayer.js line: 547
ERROR: The @snippet tag - file 'examples/VideoPlayer-description_set.es6' not found. File: VideoPlayer.js line: 547
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-wix.es6' not found. File: VideoPlayer.js line: 753
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-youtube.es6' not found. File: VideoPlayer.js line: 753
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-vimeo.es6' not found. File: VideoPlayer.js line: 753
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-twitch.es6' not found. File: VideoPlayer.js line: 753
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-dailymotion.es6' not found. File: VideoPlayer.js line: 753
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-mp4.es6' not found. File: VideoPlayer.js line: 753