Duplicate WixRouterSitemapEntry in frontend for wix-site due to scopes
* DocWorks for js-wixcode-sdk - 3 changes detected, but 10 issue detected
changes:
Service wix-site has a new property wixRouterSitemapEntry
Service wix-site operation routerSitemap has changed return type
Service wix-site.WixRouterSitemapEntry is new

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (101))
Property data has an unknown type * (HtmlComponentMessageEvent.js (20))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (227))
Operation get has an unknown return type * (window.js (261))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))
ERROR: The @snippet tag - file 'velo-docs/examples/Sitemap-entry-priority_get.es6' not found. File: sitemap-entry.js line: 76

* DocWorks for js-wixcode-sdk - 12 changes detected, but 10 issue detected
changes:
Service wix-site.WixRouterSitemapEntry property changeFrequency has changed setter
Service wix-site.WixRouterSitemapEntry property changeFrequency has changed summary
Service wix-site.WixRouterSitemapEntry property lastModified has changed setter
Service wix-site.WixRouterSitemapEntry property lastModified has changed summary
Service wix-site.WixRouterSitemapEntry property pageName has changed setter
Service wix-site.WixRouterSitemapEntry property pageName has changed summary
Service wix-site.WixRouterSitemapEntry property priority has changed setter
Service wix-site.WixRouterSitemapEntry property priority has changed summary
Service wix-site.WixRouterSitemapEntry property title has changed setter
Service wix-site.WixRouterSitemapEntry property title has changed summary
Service wix-site.WixRouterSitemapEntry property url has changed setter
Service wix-site.WixRouterSitemapEntry property url has changed summary

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (101))
Property data has an unknown type * (HtmlComponentMessageEvent.js (20))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (227))
Operation get has an unknown return type * (window.js (261))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))
ERROR: The @snippet tag - file 'velo-docs/examples/Sitemap-entry-priority_get.es6' not found. File: sitemap-entry.js line: 76

* DocWorks for js-wixcode-sdk - 1 change detected, but 9 issue detected
changes:
Service wix-site.WixRouterSitemapEntry property priority.examples has 1 new examples

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (101))
Property data has an unknown type * (HtmlComponentMessageEvent.js (20))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (227))
Operation get has an unknown return type * (window.js (261))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

* DocWorks for js-wixcode-sdk - 1 change detected, but 9 issue detected
changes:
Service wix-site.WixRouterSitemapEntry property lastModified has changed summary

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (101))
Property data has an unknown type * (HtmlComponentMessageEvent.js (20))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (227))
Operation get has an unknown return type * (window.js (261))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

* DocWorks for js-wixcode-sdk - no significant changes detected, but 9 issue detected

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (101))
Property data has an unknown type * (HtmlComponentMessageEvent.js (20))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (227))
Operation get has an unknown return type * (window.js (261))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

Co-authored-by: Tova Rosenstein <talyaro@wix.com>