DocWorks for js-wixcode-sdk - 1 change detected, but 6 issue detected changes: Service $w.CheckboxGroup is new
issues:
Property background is defined two or more times (document.es6 (68), ColumnStrip.es6 (55))
Property scrolling is missing a type annotation (HtmlComponent.es6 (76))
Property dataFetcher is missing a type annotation (Table.es6 (475))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (98))
ERROR: The @snippet tag - file 'examples/CheckboxGroup-selectedIndices_get.es6' not found. File: CheckboxGroup.es6 line: 316
ERROR: The @snippet tag - file 'examples/CheckboxGroup-selectedIndices_set.es6' not found. File: CheckboxGroup.es6 line: 316