DocWorks for wix-users-backend - no significant changes detected, but 2 issue detected
issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (538))
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 66