DocWorks for wixcode-crm - 5 changes detected, but 3 issue detected changes: Service wix-crm.Captcha operation openCaptchaModal param token was removed Service wix-crm.Captcha operation openCaptchaModal has changed return type Service wix-crm.Captcha operation openCaptchaModal has changed return doc Service wix-crm.Captcha operation openCaptchaModal has changed description Service wix-crm.Captcha has a new message Token
issues:
Operation appendOrCreateContact has an unknown param type wix-crm-backend.Contacts.ContactInfo (appendOrCreateContact.js (1))
Operation appendOrCreateContact has an unknown return type wix-crm-backend.Contacts.ContactIdentification (appendOrCreateContact.js (1))
ERROR: The @snippet tag - file 'velo-docs/examples/Captcha-backend-scenario.es6' not found. File: openCaptchaModal.js line: 1