DocWorks for wix-ui-santa - 3 changes detected, but 75 issue detected changes: Service $w.AudioPlayer was removed Service $w.ProgressBar has changed description Service $w.ProgressBar property style.examples has 2 new examples
issues:
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (36))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (6))
Mixin $w.ValueMixin not found (Slider.js (6))
Mixin $w.DisabledMixin not found (Slider.js (6))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (6))
Mixin $w.FocusMixin not found (Slider.js (6))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (479))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (518))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (557))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (594))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (10))
Mixin $w.DisabledMixin not found (TimePicker.js (10))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (10))
Mixin $w.RequiredMixin not found (TimePicker.js (10))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (10))
Mixin $w.FormElement not found (TimePicker.js (10))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (25))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Mixin $w.FormElement not found (AddressInput.js (124))
Mixin $w.DisabledMixin not found (AddressInput.js (124))
Mixin $w.RequiredMixin not found (AddressInput.js (124))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (124))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (124))
Mixin $w.FocusMixin not found (AddressInput.js (124))
Mixin $w.ClickableMixin not found (AddressInput.js (124))
Operation onError has an unknown param type $w.EventHandler (Captcha.js (26))
Operation onError has an unknown return type $w.captcha (Captcha.js (26))
Operation onTimeout has an unknown param type $w.EventHandler (Captcha.js (50))
Operation onTimeout has an unknown return type $w.captcha (Captcha.js (50))
Operation onVerified has an unknown param type $w.EventHandler (Captcha.js (77))
Operation onVerified has an unknown return type $w.captcha (Captcha.js (77))
Property style has an unknown type $w.Style (ProgressBar.js (27))
Mixin $w.FocusMixin not found (ProgressBar.js (9))
Mixin $w.DisabledMixin not found (ProgressBar.js (9))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (9))
Mixin $w.Element not found (ProgressBar.js (9))
Mixin $w.StyleMixin not found (ProgressBar.js (9))
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-wix.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-youtube.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-vimeo.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-twitch.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-dailymotion.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-mp4.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/Captcha-onTimeout.es6' not found. File: Captcha.js line: 89