DocWorks for payment-provider-spi - 6 changes detected, but 8 issue detected changes: Service payment-provider-spi operation createRefund was removed Service payment-provider-spi has a new operation refundTransaction Service payment-provider-spi message CreateRefundOptions was removed Service payment-provider-spi message CreateRefundResponse was removed Service payment-provider-spi has a new message RefundOptions Service payment-provider-spi has a new message RefundResponse
issues:
Message ConnectAccountOptions has an unknown property type object (payment-provider-spi.js (31))
Message ConnectAccountResponse has an unknown property type object (payment-provider-spi.js (42))
Message CreateTransactionOptions has an unknown property type object (payment-provider-spi.js (70))
Message RefundOptions has an unknown property type object (payment-provider-spi.js (186))
ERROR: The @description tag requires a value. File: payment-provider-spi.js, line: 50
ERROR: The @snippet tag - file 'velo-docs/examples/createTransaction-approves.es6' not found. File: payment-provider-spi.js line: 50
ERROR: The @description tag requires a value. File: payment-provider-spi.js, line: 160
ERROR: The @snippet tag - file 'velo-docs/examples/refundTransaction-failed.es6' not found. File: payment-provider-spi.js line: 160