DocWorks for wix-crm-backend - 40 changes detected, but 17 issue detected changes: Service wix-crm-backend.Events message CardCreatedEvent member card has changed type Service wix-crm-backend.Events message CardMovedEvent member card has changed type Service wix-crm-backend.Events message CardRestoredEvent member card has changed type Service wix-crm-backend.workflows operation createPhase has changed param phase type Service wix-crm-backend.workflows operation getCard has changed return type Service wix-crm-backend.workflows operation getCard.examples[0] has changed body Service wix-crm-backend.workflows operation getPhase was removed Service wix-crm-backend.workflows operation getWorkflow was removed Service wix-crm-backend.workflows operation listCards has changed description Service wix-crm-backend.workflows operation listCards.examples[0] has changed body Service wix-crm-backend.workflows operation listPhases was removed Service wix-crm-backend.workflows operation listWorkflows was removed Service wix-crm-backend.workflows operation updatePhaseFields has changed param phase type Service wix-crm-backend.workflows operation updateWorkflowFields has changed description Service wix-crm-backend.workflows has a new operation getPhaseInfo Service wix-crm-backend.workflows has a new operation listPhasesInfo Service wix-crm-backend.workflows has a new operation getWorkflowInfo Service wix-crm-backend.workflows has a new operation listWorkflowsInfo Service wix-crm-backend.workflows message Card has a new member phaseId Service wix-crm-backend.workflows message Card.examples[0] has changed body Service wix-crm-backend.workflows message CardList.examples[0] has changed body Service wix-crm-backend.workflows message ListCardOptions member skip was removed Service wix-crm-backend.workflows message ListCardOptions member phaseId has changed doc Service wix-crm-backend.workflows message ListCardOptions member fetchArchived was removed Service wix-crm-backend.workflows message ListCardOptions has a new member fetchOnlyArchived Service wix-crm-backend.workflows message ListCardOptions has a new member offset Service wix-crm-backend.workflows message ListCardOptions has a new member order Service wix-crm-backend.workflows message ListCardOptions.examples[0] has changed body Service wix-crm-backend.workflows message ListOptions member skip was removed Service wix-crm-backend.workflows message ListOptions has a new member offset Service wix-crm-backend.workflows message ListOptions has a new member order Service wix-crm-backend.workflows message ListOptions.examples has 2 examples removed Service wix-crm-backend.workflows message Phase.examples has 1 examples removed Service wix-crm-backend.workflows message PhaseList.examples has 1 examples removed Service wix-crm-backend.workflows message Workflow member workflowInfo has changed doc Service wix-crm-backend.workflows message Workflow member winPhaseId has changed doc Service wix-crm-backend.workflows message Workflow.examples has 1 examples removed Service wix-crm-backend.workflows message WorkflowInfo.examples has 1 examples removed Service wix-crm-backend.workflows message WorkflowList.examples has 1 examples removed Service wix-crm-backend.workflows has a new message OrderOptions
issues:
Message CardCreatedEvent has an unknown property type wix-crm-backend.workflows.CardInfo (events.js (94))
Message CardMovedEvent has an unknown property type wix-crm-backend.workflows.CardInfo (events.js (121))
Message CardRestoredEvent has an unknown property type wix-crm-backend.workflows.CardInfo (events.js (150))
Operation emailContact has an unknown param type wix-users.TriggeredEmailOptions (contacts.js (88))
Operation getCard has an unknown return type wix-crm-backend.workflows.CardInfo (cardsApi.js (59))
Operation createPhase has an unknown param type wix-crm-backend.workflows.PhaseInfo (phasesApi.js (15))
Operation getPhaseInfo has an unknown return type wix-crm-backend.workflows.PhaseInfo (phasesApi.js (57))
Operation updatePhaseFields has an unknown param type wix-crm-backend.workflows.PhaseInfo (phasesApi.js (95))
ERROR: The @snippet tag - file 'examples/CRM-workflows-getPhase.es6' not found. File: typesDocs.js line: 23
ERROR: The @snippet tag - file 'examples/CRM-workflows-getWorkflow.es6' not found. File: typesDocs.js line: 31
ERROR: The @snippet tag - file 'examples/CRM-workflows-listWorkflows.es6' not found. File: typesDocs.js line: 39
ERROR: The @snippet tag - file 'examples/CRM-workflows-listPhases.es6' not found. File: typesDocs.js line: 65
ERROR: The @snippet tag - file 'examples/CRM-workflows-listWorkflows.es6' not found. File: typesDocs.js line: 65
ERROR: The @snippet tag - file 'examples/CRM-workflows-listWorkflows.es6' not found. File: typesDocs.js line: 93
ERROR: The @snippet tag - file 'examples/CRM-workflows-listPhases.es6' not found. File: typesDocs.js line: 105
ERROR: The @snippet tag - file 'examples/CRM-workflows-getWorkflow.es6' not found. File: workflowsApi.js line: 33
ERROR: The @snippet tag - file 'examples/CRM-workflows-getWorkflow.es6' not found. File: workflowsApi.js line: 45