DocWorks  - 92 changes detected, but 19 issue detected changes: Service $w.Box property style was removed Service $w.Footer property style was removed Service $w.FormElement operation onChange was removed Service $w.Gallery has a new mixes $w.ClickableMixin Service $w.Gallery message GalleryItem was removed Service $w.Gallery message ImageItem member description has changed doc Service $w.Gallery message ImageItem member settings.quality was removed Service $w.Gallery message ImageItem member settings.amount was removed Service $w.Gallery message ImageItem member settings.radius was removed Service $w.Gallery message ImageItem member settings.threshold was removed Service $w.Gallery message ImageItemSettings member amount has changed doc Service $w.Gallery message ImageItemSettings member radius has changed doc Service $w.Gallery message ImageItemSettings member threshold has changed doc Service $w.Gallery message TextItem member style has changed doc Service $w.Gallery message TextItem member style.layoutRatio was removed Service $w.Gallery message TextItem member style.fillColor was removed Service $w.Gallery message TextItem member style.opacity was removed Service $w.Gallery message TextItem member style.boxPadding was removed Service $w.Gallery message TextItem member style.verticalAlignment was removed Service $w.Gallery message VideoItem member description has changed doc Service $w.Header property style was removed Service $w.HiddenMixin message ArcEffectOptions was removed Service $w.HiddenMixin message BounceEffectOptions was removed Service $w.HiddenMixin message DropEffectOptions was removed Service $w.HiddenMixin message ExpandEffectOptions was removed Service $w.HiddenMixin message FadeEffectOptions was removed Service $w.HiddenMixin message FlipEffectOptions was removed Service $w.HiddenMixin message FloatEffectOptions was removed Service $w.HiddenMixin message FlyEffectOptions was removed Service $w.HiddenMixin message FoldEffectOptions was removed Service $w.HiddenMixin message GlideEffectOptions was removed Service $w.HiddenMixin message RevealEffectOptions was removed Service $w.HiddenMixin message SlideEffectOptions was removed Service $w.HiddenMixin message SpinEffectOptions was removed Service $w.HiddenMixin message TurnEffectOptions was removed Service $w.Image property clickAction was removed Service $w.QuickActionBar property colorScheme has changed description Service $w.RatingsDisplay was removed Service $w.Shape was removed Service $w.Slider mixes $w.Element was removed Service $w.Switch property value was removed Service $w.Table message PaginationParam was removed Service $w.TextBox property inputType was removed Service $w.ToggleSwitch was removed Service $w callback LoginHandler was removed Service $w callback QuickActionBarItemClickedEvent was removed Service wix-crm message ContactInfo member url was removed Service wix-crm message ContactInfo member lastName was removed Service wix-crm message ContactInfo member loginEmail has changed doc Service wix-crm message ContactInfo member addresses was removed Service wix-crm message ContactInfo member labels has changed doc Service wix-crm message ContactInfo member customFields has changed doc Service wix-pay was removed Service wix-users.User was removed Service wix-users-backend was removed Service wix-users was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].id was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].sku was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].name was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].category was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].price was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].currency was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].brand was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].variant was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].list was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].position was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].id was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].sku was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].name was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].category was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].price was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].currency was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].brand was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].variant was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].quantity was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].id was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].name was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].category was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].price was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].currency was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].brand was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].variant was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].quantity was removed Service wix-window message AddPaymentInfoEvent was removed Service wix-window message AddProductImpressionEvent was removed Service wix-window message AddToCartEvent was removed Service wix-window message ClickProductEvent was removed Service wix-window message CustomEvent was removed Service wix-window message InitiateCheckoutEvent was removed Service wix-window message PurchaseEvent was removed Service wix-window message RemoveFromCartEvent was removed Service wix-window message ViewContentEvent was removed
issues:
Property background is defined two or more times (document.es6 (68), Columns.es6 (55))
Property scrolling is missing a type annotation (HtmlComponent.es6 (76))
Property dataFetcher is missing a type annotation (Table.es6 (475))
Operation emailContact has an unknown param type wix-users.TriggeredEmailOptions (crm.es6 (105))
Operation emailContact has an unknown return type void (crm.es6 (105))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (98))
Operation scrollTo has an unknown return type void (window.es6 (320))
Operation scrollBy has an unknown return type void (window.es6 (370))
Operation openModal has an unknown return type void (window.es6 (795))
Callback ReadyHandler has an unknown return type void (wixCode.es6 (75))
Operation scrollTo has an unknown return type void (Node.es6 (161))
Operation collapse has an unknown return type void (CollapsedMixin.es6 (16))
Operation expand has an unknown return type void (CollapsedMixin.es6 (111))
Operation disable has an unknown return type void (DisabledMixin.es6 (10))
Operation enable has an unknown return type void (DisabledMixin.es6 (41))
Operation hide has an unknown return type void (HiddenMixin.es6 (38))
Operation show has an unknown return type void (HiddenMixin.es6 (187))
ERROR: The @snippet tag - file 'examples/QuickActionBar-onItemClicked.es6' not found. File: QuickActionBar.es6 line: 96
ERROR: The @snippet tag - file 'examples/QuickActionBar-onItemClicked.es6' not found. File: QuickActionBar.es6 line: 112