DocWorks for wix-users-backend - 1 change detected, but 1 issue detected changes: Service wix-users-backend was removed
issues:
ERROR: Unable to find the source file or directory /Users/dori/projects/docworks/elementory-dynamic-modules/wix-users-backend/dist/src