DocWorks for wix-crm-backend - 4 changes detected, but 5 issue detected changes: Service wix-crm-backend.Workflows operation listPhasesInfo has changed param options type Service wix-crm-backend.Workflows message ListOptions.examples[0] has changed body Service wix-crm-backend.Workflows message ListOptions.examples[1] has changed body Service wix-crm-backend.Workflows message ListWorkflowsOptions was removed
issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
Operation listWorkflowsInfo has an unknown param type wix-crm-backend.Workflows.ListWorkflowsOptions (workflows.js (125))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1