Updated Workflows for doc bug day.
* DocWorks for wix-crm-backend - 73 changes detected, but 4 issue detected
changes:
Service wix-crm-backend.Workflows operation archiveCard.examples[0] has changed body
Service wix-crm-backend.Workflows operation createCard has changed param card type
Service wix-crm-backend.Workflows operation createCard has changed param card doc
Service wix-crm-backend.Workflows operation createPhase has changed param name from phase to phaseInfo
Service wix-crm-backend.Workflows operation createPhase has changed param phaseInfo type
Service wix-crm-backend.Workflows operation createPhase has changed param phaseInfo doc
Service wix-crm-backend.Workflows operation createPhase.examples[0] has changed body
Service wix-crm-backend.Workflows operation createWorkflow has changed param workflowInfo type
Service wix-crm-backend.Workflows operation createWorkflow has changed param workflowInfo doc
Service wix-crm-backend.Workflows operation deleteCard.examples[0] has changed body
Service wix-crm-backend.Workflows operation deletePhase has changed return doc
Service wix-crm-backend.Workflows operation deletePhase has changed summary
Service wix-crm-backend.Workflows operation deletePhase.examples[0] has changed body
Service wix-crm-backend.Workflows operation deleteWorkflow has changed return doc
Service wix-crm-backend.Workflows operation deleteWorkflow has changed summary
Service wix-crm-backend.Workflows operation deleteWorkflow.examples[0] has changed body
Service wix-crm-backend.Workflows operation getCard has changed param cardId doc
Service wix-crm-backend.Workflows operation getCard has changed return doc
Service wix-crm-backend.Workflows operation getCard has changed summary
Service wix-crm-backend.Workflows operation getCard.examples[0] has changed body
Service wix-crm-backend.Workflows operation getPhaseInfo has changed param phaseId doc
Service wix-crm-backend.Workflows operation getPhaseInfo has changed return doc
Service wix-crm-backend.Workflows operation getPhaseInfo has chan ...

* DocWorks for wix-crm-backend - 4 changes detected, but 5 issue detected
changes:
Service wix-crm-backend.Workflows operation listPhasesInfo has changed param options type
Service wix-crm-backend.Workflows message ListOptions.examples[0] has changed body
Service wix-crm-backend.Workflows message ListOptions.examples[1] has changed body
Service wix-crm-backend.Workflows message ListWorkflowsOptions was removed

issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
Operation listWorkflowsInfo has an unknown param type wix-crm-backend.Workflows.ListWorkflowsOptions (workflows.js (125))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

* DocWorks for wix-crm-backend - 1 change detected, but 4 issue detected
changes:
Service wix-crm-backend.Workflows operation listWorkflowsInfo has changed param options type

issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

---------

Co-authored-by: AriGoldWix <95754543+AriGoldWix@users.noreply.github.com>