wix-stores-backend: bulkUpdate/Adjust products
* DocWorks for wix-stores-backend - 4 changes detected, but 7 issue detected
changes:
Service wix-stores-backend has a new operation bulkAdjustProductProperty
Service wix-stores-backend has a new message BulkAdjustProperties
Service wix-stores-backend has a new message AdjustBy
Service wix-stores-backend has a new message PercentageAdjustment

issues:
Operation bulkAdjustProductProperty has an unknown return type wix-stores-backend.BulkAdjustResponse (products.js (528))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Operation bulkAdjustProductProperty has an unknown return type wix-stores-backend.BulkAdjustResponse (products.js (528))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
ERROR: The @snippet tag - file 'corvid-docs/examples/Gallery-items_set.es6' not found. File: events.js line: 245

* DocWorks for wix-stores-backend - 2 changes detected, but 7 issue detected
changes:
Service wix-stores-backend message BulkAdjustProperties member price has changed optional
Service wix-stores-backend message BulkAdjustProperties has changed extra.oneOfGroups

issues:
Operation bulkAdjustProductProperty has an unknown return type wix-stores-backend.BulkAdjustResponse (products.js (528))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Operation bulkAdjustProductProperty has an unknown return type wix-stores-backend.BulkAdjustResponse (products.js (528))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
ERROR: The @snippet tag - file 'corvid-docs/examples/Gallery-items_set.es6' not found. File: events.js line: 245

* DocWorks for wix-stores-backend - 8 changes detected, but 7 issue detected
changes:
Service wix-stores-backend message AdjustBy member percentage has changed optional
Service wix-stores-backend message AdjustBy member amount has changed optional
Service wix-stores-backend message AdjustBy has changed extra.oneOfGroups
Service wix-stores-backend has a new message BulkAdjustResponse
Service wix-stores-backend has a new message BulkResults
Service wix-stores-backend has a new message ItemMetadata
Service wix-stores-backend has a new message ItemMetadataError
Service wix-stores-backend has a new message BulkActionMetadata

issues:
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (597))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (597))
ERROR: The @snippet tag - file 'corvid-docs/examples/Gallery-items_set.es6' not found. File: events.js line: 245

* DocWorks for wix-stores-backend - 1 change detected, but 7 issue detected
changes:
Service wix-stores-backend message PercentageAdjustment member roundToInt has changed doc

issues:
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (597))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (597))
ERROR: The @snippet tag - file 'corvid-docs/examples/Gallery-items_set.es6' not found. File: events.js line: 245

* DocWorks for wix-stores-backend - 8 changes detected, but 7 issue detected
changes:
Service wix-stores-backend operation bulkAdjustProductProperty has changed return type
Service wix-stores-backend operation bulkAdjustProductProperty has changed description
Service wix-stores-backend operation bulkAdjustProductProperty.examples[0] has changed body
Service wix-stores-backend has a new operation bulkUpdateProductProperty
Service wix-stores-backend message BulkAdjustProperties member cost has changed doc
Service wix-stores-backend message BulkAdjustResponse was removed
Service wix-stores-backend has a new message BulkUpdateProperties
Service wix-stores-backend has a new message BulkUpdateResponse

issues:
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (635))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (635))
ERROR: The @snippet tag - file 'corvid-docs/examples/Gallery-items_set.es6' not found. File: events.js line: 245

* DocWorks for wix-stores-backend - 9 changes detected, but 7 issue detected
changes:
Service wix-stores-backend operation bulkAdjustProductProperty.examples[0] has changed title
Service wix-stores-backend operation bulkAdjustProductProperty.examples[0] has changed body
Service wix-stores-backend operation bulkAdjustProductProperty.examples[1] has changed title
Service wix-stores-backend operation bulkAdjustProductProperty.examples[1] has changed body
Service wix-stores-backend operation bulkAdjustProductProperty.examples has 1 new examples
Service wix-stores-backend operation bulkUpdateProductProperty.examples[0] has changed body
Service wix-stores-backend operation bulkUpdateProductProperty.examples[1] has changed body
Service wix-stores-backend operation bulkUpdateProductProperty.examples[2] has changed body
Service wix-stores-backend operation bulkUpdateProductProperty.examples[2] has changed extra.description

issues:
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (638))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (638))
ERROR: The @snippet tag - file 'corvid-docs/examples/Gallery-items_set.es6' not found. File: events.js line: 245

* DocWorks for wix-stores-backend - 5 changes detected, but 7 issue detected
changes:
Service wix-stores-backend operation bulkAdjustProductProperty.examples[2] has changed title
Service wix-stores-backend operation bulkUpdateProductProperty.examples[0] has changed title
Service wix-stores-backend operation bulkUpdateProductProperty.examples[1] has changed title
Service wix-stores-backend operation bulkUpdateProductProperty.examples[2] has changed title
Service wix-stores-backend operation bulkUpdateProductProperty.examples[2] has changed extra.description

issues:
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (638))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (638))
ERROR: The @snippet tag - file 'corvid-docs/examples/Gallery-items_set.es6' not found. File: events.js line: 245

* DocWorks for wix-stores-backend - no significant changes detected, but 6 issue detected

issues:
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (638))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (638))

* DocWorks for wix-stores-backend - 1 change detected, but 6 issue detected
changes:
Service wix-stores-backend message ItemMetadata member error has changed doc

issues:
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (638))
Message SeoTag has an unknown property type object (products.js (94))
Message SeoTag has an unknown property type object (products.js (94))
Message ItemMetadataError has an unknown property type object (products.js (638))

* DocWorks for wix-stores-backend - 22 changes detected, but 6 issue detected
changes:
Service wix-stores-backend operation bulkAdjustProductProperty has changed description
Service wix-stores-backend operation bulkAdjustProductProperty.examples[0] has changed body
Service wix-stores-backend operation bulkAdjustProductProperty.examples[1] has changed body
Service wix-stores-backend operation bulkAdjustProductProperty.examples[2] has changed body
Service wix-stores-backend operation bulkUpdateProductProperty has changed param ids doc
Service wix-stores-backend operation bulkUpdateProductProperty has changed description
Service wix-stores-backend operation bulkUpdateProductProperty.examples[0] has changed body
Service wix-stores-backend operation bulkUpdateProductProperty.examples[1] has changed body
Service wix-stores-backend operation bulkUpdateProductProperty.examples[2] has changed body
Service wix-stores-backend message BulkAdjustProperties member price has changed doc
Service wix-stores-backend message BulkAdjustProperties member cost has changed doc
Service wix-stores-backend message BulkAdjustProperties member weight has changed doc
Service wix-stores-backend message BulkUpdateProperties member price has changed doc
Service wix-stores-backend message BulkUpdateProperties member cost has changed doc
Service wix-stores-backend message BulkUpdateProperties member weight has changed doc
Service wix-stores-backend message BulkUpdateProperties member ribbon has changed doc
Service wix-stores-backend message BulkUpdateProperties member brand has changed doc
Service wix-stores-backend message ItemMetadata member id has changed doc
Service wix-stores-backend message ItemMetadata member originalIndex has changed doc
Service wix-stores-backend message ItemMetadata member success has changed doc
Service wix-stores-backend message ItemMetadata member error has changed doc
Service wix-stores-backend message PercentageAdjustment member roundToInt has changed doc

issues:
Messa ...

Co-authored-by: roysha-wix <62389977+roysha-wix@users.noreply.github.com>