DocWorks for wix-media-backend - 11 changes detected, but 40 issue detected changes: Service wix-media-backend operation importFile.examples[0] has changed body Service wix-media-backend operation upload.examples[0] has changed body Service wix-media-backend operation upload.examples[1] has changed body Service wix-media-backend message FileInfo.examples[1] has changed body Service wix-media-backend message FileInfo.examples[2] has changed body Service wix-media-backend message MediaOptions.examples[0] has changed body Service wix-media-backend message MediaOptions.examples[1] has changed body Service wix-media-backend message MetadataOptions.examples[0] has changed body Service wix-media-backend message MetadataOptions.examples[1] has changed body Service wix-media-backend message UploadOptions.examples[0] has changed body Service wix-media-backend message UploadOptions.examples[1] has changed body
issues:
Operation getFileInfo is defined two or more times (get-file-info.js (44), uploader.js (285))
Operation getFileUrl is defined two or more times (get-file-url.js (44), uploader.js (333))
Operation getUploadUrl is defined two or more times (get-upload-url.js (44), uploader.js (441))
Operation getVideoPlaybackUrl is defined two or more times (get-video-playback-url.js (44), uploader.js (373))
Operation importFile is defined two or more times (import-file.js (44), uploader.js (94))
Operation upload has an unknown param type Buffer (upload.js (44))
Operation upload is defined two or more times (upload.js (44), uploader.js (187))
Message UploadOptions is defined two or more times (index.js (2), uploader.js (171))
Message FileInfo is defined two or more times (index.js (55), uploader.js (254))
Message UploadUrl is defined two or more times (index.js (90), uploader.js (433))
Message UploadFile has an unknown property type Buffer (uploader.js (150))
Operation getFileInfo is defined two or more times (get-file-info.js (44), uploader.js (285))
Operation getFileUrl is defined two or more times (get-file-url.js (44), uploader.js (333))
Operation getUploadUrl is defined two or more times (get-upload-url.js (44), uploader.js (441))
Operation getVideoPlaybackUrl is defined two or more times (get-video-playback-url.js (44), uploader.js (373))
Operation importFile is defined two or more times (import-file.js (44), uploader.js (94))
Operation upload has an unknown param type Buffer (upload.js (44))
Operation upload is defined two or more times (upload.js (44), uploader.js (187))
Message UploadOptions is defined two or more times (index.js (2), uploader.js (171))
Message FileInfo is defined two or more times (index.js (55), uploader.js (254))
Message UploadUrl is defined two or more times (index.js (90), uploader.js (433))
Message UploadFile has an unknown property type Buffer (uploader.js (150))
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-importFile.es6' not found. File: uploader.js line: 94
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-importFile.es6' not found. File: uploader.js line: 67
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-importFile.es6' not found. File: uploader.js line: 118
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-upload.es6' not found. File: uploader.js line: 187
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-upload_url.es6' not found. File: uploader.js line: 187
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-upload.es6' not found. File: uploader.js line: 150
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-upload.es6' not found. File: uploader.js line: 171
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-upload.es6' not found. File: uploader.js line: 220
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-upload_url.es6' not found. File: uploader.js line: 220
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-getFileInfo.es6' not found. File: uploader.js line: 285
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-FileInfo.es6' not found. File: uploader.js line: 254
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-getFileInfo.es6' not found. File: uploader.js line: 313
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-getFileUrl.es6' not found. File: uploader.js line: 333
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-getFileUrl.es6' not found. File: uploader.js line: 353
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-getVideoPlaybackUrl.es6' not found. File: uploader.js line: 373
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-getVideoPlaybackUrl.es6' not found. File: uploader.js line: 386
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-getUploadUrl.es6' not found. File: uploader.js line: 441
ERROR: The @snippet tag - file 'examples/Privatemedia-backend-getUploadUrl.es6' not found. File: uploader.js line: 481