DocWorks for wixcode-stores - 9 changes detected, but 11 issue detected changes: Service wix-stores.Cart has changed description Service wix-stores operation getProductOptionsAvailability has changed summary Service wix-stores operation getProductOptionsAvailability has changed description Service wix-stores operation getProductOptionsAvailability link [addToCart( )]($w.CartIcon.html#addToCart) was removed Service wix-stores operation getProductOptionsAvailability link [getProduct()]($w.ProductPage.html#getProduct) was removed Service wix-stores operation getProductOptionsAvailability.examples has 2 examples removed Service wix-stores message ProductOptionsAvailability.examples has 1 examples removed Service wix-stores message ProductOptionsAvailabilitySelectedVariant.examples has 1 examples removed Service wix-stores.Product is new
issues:
Operation getCurrentCart has an unknown return type wix-stores-backend.Cart (stores.js (381))
Operation removeProduct has an unknown return type wix-stores-backend.Cart (stores.js (434))
Operation addCustomItems has an unknown return type wix-stores-backend.Cart (stores.js (492))
Operation addProducts has an unknown return type wix-stores-backend.Cart (stores.js (516))
Operation updateLineItemQuantity has an unknown return type wix-stores-backend.Cart (stores.js (594))
Operation getCurrentCart has an unknown return type wix-stores-backend.Cart (stores.js (344))
Operation removeProductFromCart has an unknown return type wix-stores-backend.Cart (stores.js (395))
Operation addCustomItemsToCart has an unknown return type wix-stores-backend.Cart (stores.js (454))
Callback CartChangedHandler has an unknown param type wix-stores-backend.Cart (stores.js (318))
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-getProductOptionsAvailability_no_variant.es6' not found. File: stores.js line: 40
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-getProductOptionsAvailability_yes_variant.es6' not found. File: stores.js line: ...