DocWorks for wix-data - 1 change detected, but 15 issue detected changes: Service DataHooks was removed
issues:
Operation ascending is defined two or more times (distinct.js (92), sortMixin.js (10))
Operation descending is defined two or more times (distinct.js (116), sortMixin.js (41))
Operation eq has an unknown param type * (filterMixin.js (33))
Operation ne has an unknown param type * (filterMixin.js (59))
Operation hasSome has an unknown param type * (filterMixin.js (342))
Operation hasAll has an unknown param type * (filterMixin.js (378))
Operation beforeAggregate is defined two or more times (hooks.js (313, 337))
Operation onFailure has an unknown param type Error (hooks.js (608))
Operation truncate has an unknown return type null (data-api.js (451))
Message WixDataBulkRemoveResult has an unknown property type Error (data-api.js (485))
Message WixDataBulkResult has an unknown property type Error (data-api.js (877))
ERROR: The @snippet tag - file 'velo-docs/examples/Hooks-afterDistinct.es6' not found. File: hooks.js line: 109
ERROR: The @snippet tag - file 'velo-docs/examples/Hooks-afterDistinct_scenario.es6' not found. File: hooks.js line: 109
ERROR: The @snippet tag - file 'velo-docs/examples/Hooks-beforeDistinct.es6' not found. File: hooks.js line: 395
ERROR: The @snippet tag - file 'velo-docs/examples/Hooks-beforeDistinct_scenario.es6' not found. File: hooks.js line: 395