DocWorks for js-wixcode-sdk - 27 changes detected, but 6 issue detected changes: Service $w.Button property label has changed default value Service $w.CheckboxGroup property options has changed default value Service $w.CollapsedMixin property collapsed has changed default value Service $w.ContainableMixin property children has changed default value Service $w.DatePicker property maxDate has changed default value Service $w.DatePicker property minDate has changed default value Service $w.DisabledMixin property enabled has changed default value Service $w.Dropdown property options has changed default value Service $w.Dropdown property selectedIndex has changed default value Service $w.Element property rendered has changed default value Service $w.HiddenMixin property hidden has changed default value Service $w.HiddenMixin property isVisible has changed default value Service $w.Image property alt has changed default value Service $w.Image property src has changed default value Service $w.Image property tooltip has changed default value Service $w.LabelMixin property label has changed default value Service $w.LinkableMixin property link has changed default value Service $w.LinkableMixin property target has changed default value Service $w.Node property global has changed default value Service $w.Node property parent has changed default value Service $w.RadioButtonGroup property options has changed default value Service $w.RadioButtonGroup property selectedIndex has changed default value Service $w.Slider property step has changed default value Service $w.Slider property stepType has changed default value Service $w.Text property text has changed default value Service $w.TextBox property wrap has changed default value Service $w.VectorImage property src has changed default value
issues:
Property background is defined two or more times (document.es6 (68), ColumnStrip.es6 (55))
Property scrolling is missing a type annotation (HtmlComponent.es6 (76))
Property dataFetcher is missing a type annotation (Table.es6 (475))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (98))
ERROR: The @snippet tag - file 'examples/CheckboxGroup-selectedIndices_get.es6' not found. File: CheckboxGroup.es6 line: 316
ERROR: The @snippet tag - file 'examples/CheckboxGroup-selectedIndices_set.es6' not found. File: CheckboxGroup.es6 line: 316