DocWorks for js-wixcode-sdk - 5 changes detected, but 12 issue detected changes: Service $w.MultiStateBox operation changeState has changed param stateReference doc Service $w.MultiStateBox operation changeState has changed return doc Service $w.MultiStateBox operation onChange has changed description Service $w.MultiStateBox operation onChange has a new link [`changeState( )`](#changeState) Service $w.MultiStateBox operation onChange link [changeState( )](#changeState) was removed
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (234))
Property center is defined two or more times (GoogleMap.es6 (158, 193))
Property zoom is defined two or more times (GoogleMap.es6 (210, 234))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (106, 141))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 346
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 354
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_set.es6' not found. File: ForegroundColorMixin.es6 line: 54
ERROR: The @snippet tag - file 'examples/foregroundColorMixin-foregroundColor_get.es6' not found. File: ForegroundColorMixin.es6 line: 54