DocWorks for wix-crm-backend - 1 change detected, but 3 issue detected changes: Service wix-crm-backend operation createContact was removed
issues:
Operation emailContact has an unknown param type wix-users.TriggeredEmailOptions (contacts.js (74))
ERROR: The @custom-labels tag requires a value. File: contacts.js, line: 40
Error: cannot create a doclet for the comment "/** * @function createContact * @custom-labels * @summary Creates a new contact or updates an existing contact. * @description *  The `createContact()` function returns a Promise that resolves to the newly *  created or updated contact's ID when the contact has been created or updated. * *  The passed `ContactInfo` object must contain at least one *  email address or phone number. * *  Calling `createContact()` performs one of the following. (The contact information *  specified in the `contactInfo` parameter matches an existing contact if it *  contains an email address or phone number from an existing contact.) * *  + If there is no matching existing contact, a new contact is created using the *    information specified using the `contactInfo` parameter. *  + If there is a matching existing contact, it is updated with the information *    specified using the `contactInfo` parameter. Any existing contact information *    that is not explicity overriden in the `contactInfo` parameter retains its *    existing value. * * > **Note:** You cannot use the `createContact()` function to update contact information for existing site members. To do so, use [`updateContact`](#updateContact). * * @snippet [CRM-backend-createContact.es6=Create a new contact] *  This example contains a backend function that creates a new contact and *  returns the new contact's ID to the code that called the function. * @param {wix-crm-backend~ContactInfo} contactInfo The information for the contact being created or updated. * @returns {Promise} * @fulfill {String} The ID of the new or updated contact. * @reject {String} Error mess ...