"site tab" changed to "masterpage.js"
* DocWorks for js-wixcode-sdk - 7 changes detected, but 7 issue detected
changes:
Service $w.HtmlComponent operation onMessage has changed description
Service $w.TextInputMixin operation onKeyPress has a new param eventHandler
Service $w.TextInputMixin operation onKeyPress has changed description
Service $w operation onReady has changed description
Service wix-window.ConsentPolicy operation onConsentPolicyChanged has changed description
Service wix-window property locale has changed summary
Service wix-window property referrer.examples[1] has changed extra.description

issues:
Operation postMessage has an unknown param type * (HtmlComponent.es6 (145))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.es6 (252, 272))
Property data has an unknown type * (HtmlComponentMessageEvent.es6 (26))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (98))
Property value has an unknown type * (ValueMixin.es6 (82))
Property value has an unknown type * (ValueMixin.es6 (113))
ERROR: The @description tag requires a value. File: BaseGallery.es6, line: 564

* DocWorks for wixcode-users - 2 changes detected, but 1 issue detected
changes:
Service wix-users operation onConsentPolicyChanged has changed description
Service wix-users operation onLogin has changed description

issues:
Message RegistrationOptions has an unknown property type wix-crm.ContactInfo (users.js (396))

Co-authored-by: Adam Friedmann <adamfri@wix.com>