DocWorks for wixcode-crm - 2 changes detected, but 3 issue detected changes: Service captcha was removed Service wix-crm.Captcha is new
issues:
Operation appendOrCreateContact has an unknown param type wix-crm-backend.Contacts.ContactInfo (appendOrCreateContact.js (1))
Operation appendOrCreateContact has an unknown return type wix-crm-backend.Contacts.ContactIdentification (appendOrCreateContact.js (1))
ERROR: The @snippet tag - file 'velo-docs/examples/Captcha-backend-scenario.es6' not found. File: openCaptchaModal.js line: 1