DocWorks for wixcode-crm - 3 changes detected, but 4 issue detected changes: Service wix-captcha was removed Service wix-crm has a new property openCaptchaModal Service captcha is new
issues:
Operation appendOrCreateContact has an unknown param type wix-crm-backend.Contacts.ContactInfo (appendOrCreateContact.js (1))
Operation appendOrCreateContact has an unknown return type wix-crm-backend.Contacts.ContactIdentification (appendOrCreateContact.js (1))
Property openCaptchaModal has an unknown type wix-crm.Captcha (index.js (21))
ERROR: The @snippet tag - file 'velo-docs/examples/Captcha-backend-scenario.es6' not found. File: openCaptchaModal.js line: 1