DocWorks for js-wixcode-sdk - 12 changes detected, but 3 issue detected changes: Service $w.State property name was removed Service $w.Style has changed summary Service $w.Style property backgroundColor has changed description Service $w.Style property borderColor has changed description Service $w.Style property borderRadius has changed description Service $w.Style property borderWidth has changed description Service $w.Style property color has changed description Service $w.StyleMixin has changed description Service $w.TextInput property min has changed description Service wix-window operation scrollTo has a new param options Service wix-window operation scrollTo has changed description Service wix-window has a new message ScrollToOptions
issues:
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 358
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 366