Hide properties from left menu (leave only capitalized class)
* DocWorks for wix-crm-backend - 2 changes detected, but 4 issue detected
changes:
Service wix-crm-backend operation emailContact has changed summary
Service wix-crm-backend operation emailContact has changed description

issues:
Operation eq has an unknown param type * (queryContacts.js (44))
Operation ne has an unknown param type * (queryContacts.js (87))
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

* DocWorks for wixcode-crm - 2 changes detected, but 3 issue detected
changes:
Service wix-crm operation emailContact has changed summary
Service wix-crm operation emailContact has changed description

issues:
Operation appendOrCreateContact has an unknown param type wix-crm-backend.Contacts.ContactInfo (appendOrCreateContact.js (1))
Operation appendOrCreateContact has an unknown return type wix-crm-backend.Contacts.ContactIdentification (appendOrCreateContact.js (1))
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wixcode-users - 2 changes detected, but 2 issue detected
changes:
Service wix-users operation emailUser has changed summary
Service wix-users operation emailUser has changed description

issues:
Message RegistrationOptions has an unknown property type wix-crm.ContactInfo (users.js (729))
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

* DocWorks for wix-users-backend - 2 changes detected, but 5 issue detected
changes:
Service wix-users-backend operation emailUser has changed summary
Service wix-users-backend operation emailUser has changed description

issues:
Operation register has an unknown param type wix-users.RegistrationOptions (users.js (51))
Operation emailUser has an unknown param type wix-users.TriggeredEmailOptions (users.js (386))
Property currentUser is defined two or more times (user-class.js (274), users.js (472))
Message RegistrationResult has an unknown property type wix-users.User (users.js (34))
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating

Co-authored-by: Stefan (Shalom) Boroda <imnotashrimp@gmail.com>