DocWorks for wix-privatemedia-backend - 1 change detected, but 1 issue detected changes: Service wix-privatemedia-backend.Events was removed
issues:
ERROR: Unable to find the source file or directory /Users/samm/Documents/repos/elementory-dynamic-modules/wix-privatemedia-backend/.lib/src