DocWorks for wix-application - 5 changes detected, but 5 issue detected changes: Service wix-application operation openAppLightbox has changed param name from name to lightboxId Service wix-application operation openAppLightbox has changed param lightboxId doc Service wix-application operation openAppLightbox has changed return type Service wix-application operation openAppLightbox has changed return doc Service wix-application operation openAppLightbox has changed description
issues:
Operation getAppPageUrl is defined two or more times (application.js (38, 50))
ERROR: The @snippet tag - file 'velo-docs/examples/Lightbox-close.es6' not found. File: application.js line: 63
ERROR: The @snippet tag - file 'velo-docs/examples/Lightbox-close_options.es6' not found. File: application.js line: 63
ERROR: The @snippet tag - file 'velo-docs/examples/Window-openLightbox_Hello_Lightboxes.es6' not found. File: application.js line: 63
ERROR: The @snippet tag - file 'velo-docs/examples/Lightbox-scenario.es6' not found. File: application.js line: 63