DocWorks for mobile-elements - 2 changes detected, but 18 issue detected changes: Service $w.MobileElement mixes $w.Element was removed Service $w.MobileHiddenMixin was removed
issues:
Mixin $w.ContainableMixin not found (MobileContainer.js (1))
Operation onChange has an unknown param type $w.EventHandler (MobilePicker.js (254))
Property validateOnChange is defined two or more times (MobilePicker.js (213, 228))
Property validateOnStart is defined two or more times (MobilePicker.js (234, 248))
Mixin $w.LabelMixin not found (MobilePicker.js (1))
Mixin $w.ValueMixin not found (MobilePicker.js (1))
Mixin $w.Event not found (MobilePressEvent.js (7))
Mixin $w.LabelMixin not found (MobileTextInput.js (1))
Property parent has an unknown type $w.Node (MobileElement.js (77))
Operation onChange has an unknown param type $w.EventHandler (MobileFormElement.js (161))
Property validateOnBlur is defined two or more times (MobileFormElement.js (97, 114))
Property validateOnChange is defined two or more times (MobileFormElement.js (120, 135))
Property validateOnStart is defined two or more times (MobileFormElement.js (141, 155))
Mixin $w.ValueMixin not found (MobileFormElement.js (1))
Mixin $w.MobileHiddenMixin not found (MobileHiddenCollapsedMixin.js (1))
Mixin $w.CollapsedMixin not found (MobileHiddenCollapsedMixin.js (1))
ERROR: The @description tag requires a value. File: MobilePicker.js, line: 97
ERROR: The @description tag requires a value. File: MobilePicker.js, line: 117