DocWorks for doc_stores_cat_write - 11 changes detected, but 42 issue detected changes: Service wix-stores-backend.Events message MediaItem was removed Service wix-stores-backend.Events message ProductCreatedEvent member mediaItems has changed type Service wix-stores-backend operation addProductMedia has changed param media type Service wix-stores-backend operation addProductMediaToChoices has changed param media type Service wix-stores-backend operation removeProductMediaFromChoices has changed param mediaChoices type Service wix-stores-backend message PagingOptions has a new link [getProductVariants()]($w.ProductPage.html#getProductVariants) Service wix-stores-backend message PagingOptions link [getProductVariants()](#$w.ProductPage.htmlgetProductVariants) was removed Service wix-stores-backend message Product member mediaItems has changed type Service wix-stores-backend message ProductOptionsAvailability member mediaItems was removed Service wix-stores-backend message ProductOptionsAvailability has a new member undefined Service wix-stores-backend message ProductOptionsChoiceMedia member mediaItems has changed type
issues:
Operation getProductOptionsAvailability is defined two or more times (inventory.js (176), products.js (191))
Operation getProductVariants is defined two or more times (inventory.js (338), products.js (353))
Operation createProduct is defined two or more times (inventory.js (354), products.js (369))
Operation deleteProduct is defined two or more times (inventory.js (377), products.js (392))
Operation updateProductFields is defined two or more times (inventory.js (390), products.js (405))
Operation deleteProductOptions is defined two or more times (inventory.js (407), products.js (422))
Operation addProductsToCollection is defined two or more times (inventory.js (420), products.js (435))
Operation removeProductsFromCollection is defined two or more times (inventory.js (440), products.js (455))
Operation updateVariantData is defined two or more times (inventory.js (461), products.js (476))
Operation resetVariantData is defined two or more times (inventory.js (487), products.js (502))
Operation addProductMedia is defined two or more times (inventory.js (504), products.js (519))
Operation addProductMediaToChoices is defined two or more times (inventory.js (521), products.js (536))
Operation removeProductMedia is defined two or more times (inventory.js (536), products.js (551))
Operation removeProductMediaFromChoices is defined two or more times (inventory.js (559), products.js (574))
Message MediaItem is defined two or more times (carts.js (130), events.js (216))
Message Product has an unknown property type $w.Gallery.VideoItem (inventory.js (3))
Message Product is defined two or more times (inventory.js (3), products.js (18))
Message ProductVariants is defined two or more times (inventory.js (38), products.js (53))
Message ProductCustomTextFields is defined two or more times (inventory.js (47), products.js (62))
Message ProductAdditionalInfoSection is defined two or more times (inventory.js (57), products.js (72))
Message ProductRibbon is defined two or more times (inventory.js (67), products.js (82))
Message ProductInfo is defined two or more times (inventory.js (75), products.js (90))
Message ProductDiscount is defined two or more times (inventory.js (92), products.js (107))
Message ProductOptions is defined two or more times (inventory.js (106), products.js (121))
Message ProductOption is defined two or more times (inventory.js (115), products.js (130))
Message ProductOptionsChoice is defined two or more times (inventory.js (126), products.js (141))
Message ProductOptionsChoiceMedia has an unknown property type $w.Gallery.VideoItem (inventory.js (137))
Message ProductOptionsChoiceMedia is defined two or more times (inventory.js (137), products.js (152))
Message ProductOptionsAvailability is defined two or more times (inventory.js (147), products.js (162))
Message ProductOptionsAvailabilitySelectedVariant is defined two or more times (inventory.js (159), products.js (174))
Message ProductChoices is defined two or more times (inventory.js (211), products.js (226))
Message ProductVariantOptions is defined two or more times (inventory.js (220), products.js (235))
Message PagingOptions is defined two or more times (inventory.js (231), products.js (246))
Message Variants is defined two or more times (inventory.js (240), products.js (255))
Message VariantItem is defined two or more times (inventory.js (249), products.js (264))
Message VariantInfo is defined two or more times (inventory.js (258), products.js (273))
Message MediaChoices is defined two or more times (inventory.js (274), products.js (289))
Message Media is defined two or more times (inventory.js (281), products.js (296))
Message Choice is defined two or more times (inventory.js (303), products.js (318))
Message ProductVariantItem is defined two or more times (inventory.js (310), products.js (325))
Message ProductVariantInfo is defined two or more times (inventory.js (322), products.js (337))
ERROR: Unable to parse a tag's type expression for source file /Users/martab/Repositories/elementory-dynamic-modules/wix-stores-backend/corvid-docs/api/inventory.js with tag title "property" and text "{(wix-stores-backend~MediaItem[[]|$w.Gallery~VideoItem[])} mediaItems List of product media items.": Invalid type expression "(wix-stores-backend~MediaItem[[]|$w.Gallery~VideoItem[])": Expected "!", "#", "$", "(", ")", "-", ".", "/", "0", ":", "<", "=", "?", "@", "[]", "\\", "_", "|", "~", "‌", "‍", Unicode combining mark, Unicode decimal number, Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode punctuation connector, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but "[" found.