Typedef desc (#40)
* DocWorks for js-wixcode-sdk - 94 changes detected, but 12 issue detected
changes:
Service $w.Background message BackgroundOptions member src has changed doc
Service $w.Background message BackgroundOptions has changed description
Service $w.Document message BackgroundOptions member src has changed doc
Service $w.Document message BackgroundOptions has changed description
Service $w.EffectOptions message ArcEffectOptions member duration has changed doc
Service $w.EffectOptions message ArcEffectOptions member delay has changed doc
Service $w.EffectOptions message ArcEffectOptions member direction has changed doc
Service $w.EffectOptions message ArcEffectOptions has changed description
Service $w.EffectOptions message BounceEffectOptions member duration has changed doc
Service $w.EffectOptions message BounceEffectOptions member delay has changed doc
Service $w.EffectOptions message BounceEffectOptions member direction has changed doc
Service $w.EffectOptions message BounceEffectOptions member intensity has changed doc
Service $w.EffectOptions message BounceEffectOptions has changed description
Service $w.EffectOptions message FadeEffectOptions member duration has changed doc
Service $w.EffectOptions message FadeEffectOptions member delay has changed doc
Service $w.EffectOptions message FadeEffectOptions has changed description
Service $w.EffectOptions message FlipEffectOptions member duration has changed doc
Service $w.EffectOptions message FlipEffectOptions member delay has changed doc
Service $w.EffectOptions message FlipEffectOptions member direction has changed doc
Service $w.EffectOptions message FlipEffectOptions has changed description
Service $w.EffectOptions message FloatEffectOptions member duration has changed doc
Service $w.EffectOptions message FloatEffectOptions member delay has changed doc
Service $w.EffectOptions message FloatEffectOptions member direction has changed doc
Service $w.EffectOptions message FloatEffectOptions has changed description
Service $w.EffectOptions message FlyEffectOptions member duration has changed doc
Service $w.EffectOptions message FlyEffectOptions member delay has changed doc
Service $w.EffectOptions message FlyEffectOptions member direction has changed doc
Service $w.EffectOptions message FlyEffectOptions has changed description
Service $w.EffectOptions message FoldEffectOptions member duration has changed doc
Service $w.EffectOptions message FoldEffectOptions member delay has changed doc
Service $w.EffectOptions message FoldEffectOptions member direction has changed doc
Service $w.EffectOptions message FoldEffectOptions has changed description
Service $w.EffectOptions message GlideEffectOptions member duration has changed doc
Service $w.EffectOptions message GlideEffectOptions member delay has changed doc
Service $w.EffectOptions message GlideEffectOptions member angle has changed doc
Service $w.EffectOptions message GlideEffectOptions member distance has changed doc
Service $w.EffectOptions message GlideEffectOptions has changed description
Service $w.EffectOptions message PuffEffectOptions member duration has changed doc
Service $w.EffectOptions message PuffEffectOptions member delay has changed doc
Service $w.EffectOptions message PuffEffectOptions has changed description
Service $w.EffectOptions message RollEffectOptions member duration has changed doc
Service $w.EffectOptions message RollEffectOptions member delay has changed doc
Service $w.EffectOptions message RollEffectOptions member direction has changed doc
Service $w.EffectOptions message RollEffectOptions has changed description
Service $w.EffectOptions message SlideEffectOptions member duration has changed doc
Service $w.EffectOptions message SlideEffectOptions member delay has changed doc
Service $w.EffectOptions message SlideEffectOptions member direction has changed doc
Service $w.EffectOptions message SlideEffectOptions has changed description
Service $w.EffectOptions message SpinEffectOptions member duration has changed doc
Service $w.EffectOptions message SpinEffectOptions member delay has changed doc
Service $w.EffectOptions message SpinEffectOptions member direction has changed doc
Service $w.EffectOptions message SpinEffectOptions member cycles has changed doc
Service $w.EffectOptions message SpinEffectOptions has changed description
Service $w.EffectOptions message TurnEffectOptions member duration has changed doc
Service $w.EffectOptions message TurnEffectOptions member delay has changed doc
Service $w.EffectOptions message TurnEffectOptions member direction has changed doc
Service $w.EffectOptions message TurnEffectOptions has changed description
Service $w.EffectOptions message ZoomEffectOptions member duration has changed doc
Service $w.EffectOptions message ZoomEffectOptions member delay has changed doc
Service $w.EffectOptions message ZoomEffectOptions has changed description
Service $w.GoogleMap has a new property center
Service $w.GoogleMap has a new property zoom
Service $w.GoogleMap has a new property markers
Service $w.HiddenMixin operation show has changed description
Service $w.QuickActionBarItemClickedEvent message QuickActionBarItem member itemType has changed doc
Service $w.QuickActionBarItemClickedEvent message QuickActionBarItem has changed description
Service $w.Slideshow operation onChange has changed extra.notes
Service $w.TextInputMixin operation onInput was removed
Service $w.TextInputMixin operation onKeyPress has changed extra.notes
Service $w.UploadButton property fileType has changed description
Service $w.ValidatableMixin message ValidityState has changed description
Service npm-modules has changed description
Service site-monitoring.LogEntry message LogEntryOperation has changed description
Service site-monitoring.LogEntry message LogEntryOperation has changed extra.notes
Service wix-site operation getSiteStructure has changed description
Service wix-site message Prefix member type has changed doc
Service wix-site message Prefix has changed description
Service wix-site message SiteStructure member pages has changed doc
Service wix-site message SiteStructure has changed description
Service wix-site message StructurePage has changed description
Service wix-storage.Storage has changed summary
Service wix-storage.Storage operation setItem has changed extra.notes
Service wix-storage has changed summary
Service wix-storage has changed description
Service wix-window.trackingParameters message CustomEvent has changed description
Service wix-window operation copyToClipboard param toCopy was removed
Service wix-window operation copyToClipboard has changed return doc
Service wix-window operation copyToClipboard has changed summary
Service wix-window operation copyToClipboard has changed description
Service wix-window operation copyToClipboard.examples[0] has changed body
Service wix-window operation trackEvent has changed description
Service $w.HoverBox is new
Service $w.VideoBox is new
Service wix-events is new

issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (143))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @description tag requires a value. File: document.es6, line: 104
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 381
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 389

* DocWorks for wixcode-seo - 3 changes detected
changes:
Service wix-seo property metaTags has changed description
Service wix-seo operation setMetaTags has changed description
Service wix-seo message MetaTag has changed description

* DocWorks for wix-captcha-backend - 2 changes detected
changes:
Service wix-captcha-backend message ErrorReport member error has changed doc
Service wix-captcha-backend message ErrorReport has changed description

* DocWorks for wix-chat-backend - 2 changes detected
changes:
Service wix-chat-backend.Events message MessagePayload has changed description
Service wix-chat-backend.Events message SendMessageEvent member payload has changed doc

* DocWorks for wix-fetch - 3 changes detected
changes:
Service wix-fetch operation fetch has changed description
Service wix-fetch operation getJSON has changed description
Service wix-fetch message WixFetchRequest has changed description

* DocWorks for wix-stores-backend - 8 changes detected, but 1 issue detected
changes:
Service wix-stores-backend message MediaItem member src has changed doc
Service wix-stores-backend message MediaItem has changed description
Service wix-stores-backend message ProductOption member choices has changed doc
Service wix-stores-backend message ProductOptionInfo member choices has changed doc
Service wix-stores-backend message ProductOptions member optionKey has changed doc
Service wix-stores-backend message ProductOptions has changed description
Service wix-stores-backend message ProductOptionsChoice has changed summary
Service wix-stores-backend message ProductOptionsChoice has changed description

issues:
Message ProductCreatedEvent has an unknown property type $w.Gallery.VideoItem (events.js (216))

* DocWorks for wix-marketing-backend - 8 changes detected
changes:
Service wix-marketing-backend.coupons operation createCoupon has changed description
Service wix-marketing-backend.coupons operation updateCouponFields has changed description
Service wix-marketing-backend.coupons message CouponInfo member buyXGetY has changed doc
Service wix-marketing-backend.coupons message CouponInfo has changed description
Service wix-marketing-backend.coupons message CouponScope member group has changed doc
Service wix-marketing-backend.coupons message CouponScope has changed description
Service wix-marketing-backend.coupons message CouponTypeBuyXGetY has changed description
Service wix-marketing-backend.coupons message ScopeGroup member entityId has changed doc

* DocWorks for wix-router-sdk - 4 changes detected, but 2 issue detected
changes:
Service wix-router.WixRouterResponse property head has changed description
Service wix-router.WixRouterResponse message HeadOptions member metaTags has changed doc
Service wix-router.WixRouterResponse message HeadOptions has changed description
Service wix-router.WixRouterResponse message MetaTag has changed description

issues:
Operation customizeQuery has an unknown param type wix-data.WixDataQuery (router.js (320))
Operation customizeQuery has an unknown return type wix-data.WixDataQuery (router.js (320))

* DocWorks for wix-captcha-backend - 2 changes detected
changes:
Service wix-captcha-backend operation authorize has changed description
Service wix-captcha-backend message ErrorReport member error has changed doc

* DocWorks for wix-stores-backend - no significant changes detected, but 1 issue detected

issues:
Message ProductCreatedEvent has an unknown property type $w.Gallery.VideoItem (events.js (216))

* DocWorks for wix-stores-backend - 2 changes detected, but 1 issue detected
changes:
Service wix-stores-backend message MediaItem member src has changed doc
Service wix-stores-backend message ProductOptions member optionKey has changed doc

issues:
Message ProductCreatedEvent has an unknown property type $w.Gallery.VideoItem (events.js (216))

* Fixes for new viewer

* Fixes for new viewer