DocWorks for wix-store-backend - 13 changes detected, but 4 issue detected changes: Service wix-stores-backend.Events operation onNewOrder.examples[0] has changed body Service wix-stores-backend.Events message CartAbandonedEvent member buyerInfo has changed type Service wix-stores-backend.Events message CartBuyerInfo was removed Service wix-stores-backend.Events message CartCompletedEvent member currency has changed doc Service wix-stores-backend.Events message CartCompletedEvent member currency was removed Service wix-stores-backend.Events message NewOrderEvent member buyerInfo has changed type Service wix-stores-backend.Events message NewOrderEvent.examples[0] has changed body Service wix-stores-backend.Events message OrderBuyerInfo.examples[0] has changed body Service wix-stores-backend.Events message OrderTotals.examples[0] has changed body Service wix-stores-backend.Events message ShippingInfo member pickupDetails has changed type Service wix-stores-backend.Events message ShippingInfo member pickupDetails has changed doc Service wix-stores-backend.Events message ShippingInfo member pickupDetails was removed Service wix-stores-backend.Events has a new message BuyerInfo
issues:
Message ProductOptionsAvailability has an unknown property type $w.ProductPage.StoreProductOptions (products.js (26))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.ImageItem (products.js (26))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.VideoItem (products.js (26))
ERROR: The @snippet tag - file 'examples/Stores-backend-Events-onCartCompleted.es6' not found. File: events.js line: 205