DocWorks for js-wixcode-sdk - 1 change detected, but 13 issue detected changes: Service $w.HiddenMixin property isVisible has changed extra.notes
issues:
Property zoom is missing a type annotation (GoogleMap.es6 (235))
Property center is defined two or more times (GoogleMap.es6 (159, 194))
Property zoom is defined two or more times (GoogleMap.es6 (211, 235))
Property markers has mismatching types for get ($w.GoogleMap.markers) and set ($w.GoogleMap) (GoogleMap.es6 (107, 142))
Operation postMessage has an unknown param type * (HtmlComponent.es6 (143))
Property data has an unknown type * (HtmlComponentMessageEvent.es6 (26))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
Callback GoogleMapClickEvent is defined two or more times (GoogleMapClickEvent.es6 (4, 10))
Property value has an unknown type * (ValueMixin.es6 (56))
Property value has an unknown type * (ValueMixin.es6 (84))
ERROR: The @description tag requires a value. File: document.es6, line: 106
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 383
ERROR: The @snippet tag - file 'examples/Window-scrollTo_without_animation' not found. File: window.es6 line: 391