DocWorks for wix-crm-backend - 5 changes detected, but 1 issue detected changes: Service wix-crm-backend.Events was removed Service wix-crm-backend.notifications was removed Service wix-crm-backend.tasks was removed Service wix-crm-backend.workflows was removed Service wix-crm-backend was removed
issues:
ERROR: Unable to find the source file or directory /Users/martab/Repositories/elementory-dynamic-modules/wix-crm-backend/dist/src