DocWorks for wix-store-backend - 28 changes detected, but 15 issue detected changes: Service wix-stores-backend operation getCurrentCart.examples[0] has changed body Service wix-stores-backend message Address.examples[0] has changed title Service wix-stores-backend message Address.examples[0] has changed body Service wix-stores-backend message Address.examples has 1 examples removed Service wix-stores-backend message AppliedCoupon.examples[0] has changed title Service wix-stores-backend message AppliedCoupon.examples[0] has changed body Service wix-stores-backend message AppliedCoupon.examples has 1 examples removed Service wix-stores-backend message BuyerInfo.examples[0] has changed title Service wix-stores-backend message BuyerInfo.examples[0] has changed body Service wix-stores-backend message BuyerInfo.examples has 1 examples removed Service wix-stores-backend message Cart member geo was removed Service wix-stores-backend message Cart.examples has 1 examples removed Service wix-stores-backend message Currency.examples[0] has changed title Service wix-stores-backend message Currency.examples[0] has changed body Service wix-stores-backend message Currency.examples has 1 examples removed Service wix-stores-backend message CustomTextField.examples has 1 examples removed Service wix-stores-backend message Geo was removed Service wix-stores-backend message LineItem.examples has 1 examples removed Service wix-stores-backend message MediaItem.examples has 1 examples removed Service wix-stores-backend message Option.examples has 1 examples removed Service wix-stores-backend message OrderTotals.examples[0] has changed title Service wix-stores-backend message OrderTotals.examples[0] has changed body Service wix-stores-backend message OrderTotals.examples has 1 examples removed Service wix-stores-backend message ShippingInfo.examples[0] has changed title Service wix-stores-backend message ShippingInfo.examples[0] has changed body Service wix-stores-backend message ShippingInfo.examples[1] has changed title Service wix-stores-backend message ShippingInfo.examples[1] has changed body Service wix-stores-backend message ShippingInfo.examples has 1 examples removed
issues:
Message ProductOptionsAvailability has an unknown property type $w.ProductPage.StoreProductOptions (products.js (26))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.ImageItem (products.js (26))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.VideoItem (products.js (26))
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 2
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 20
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 32
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 51
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 70
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 79
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 90
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 115
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 124
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 139
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 148
ERROR: The @snippet tag - file 'examples/Stores-backend-getMyCart.es6' not found. File: carts.js line: 162