DocWorks for wix-store-backend - 2 changes detected, but 1 issue detected changes: Service wix-stores-backend.Events was removed Service wix-stores-backend was removed
issues:
ERROR: Unable to find the source file or directory /home/builduser/agent00/work/e534df1eef287840/wix-stores-backend/dist/src