DocWorks for js-wixcode-sdk - 1 change detected, but 18 issue detected changes: Service $w.CommentsWidget has a new operation onCommentCountChange
issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Property locked is missing a type annotation (CommentsWidget.js (12))
Operation postMessage has an unknown param type * (HtmlComponent.js (97))
Property data has an unknown type * (HtmlComponentMessageEvent.js (16))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window-frontend.js (201))
Operation get has an unknown return type * (window-frontend.js (234))
Operation set has an unknown param type * (window.js (235))
Operation get has an unknown return type * (window.js (269))
Callback ViewChangeOperation is defined two or more times (AppointmentField.js (347), DatePicker.js (472))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Callback ViewChangeEventHandler is defined two or more times (AppointmentField.js (362), DatePicker.js (466))
Callback CommentEventCallback has an unknown param type $w.WidgetComment (CommentsWidget.js (121))
Callback CommentEventCallback is defined two or more times (CommentsWidget.js (121, 153))
Callback Validator has an unknown param type * (ValidatableMixin.js (143))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))
ERROR: The @snippet tag - file 'velo-docs/examples/[CommentsWidget-onCommentCountChange.es6
=Add an event handler for counting comments in the comment widget]' not found. File: CommentsWidget.js line: 139