DocWorks for wix-users-backend - 1 change detected, but 2 issue detected changes: Service wix-users-backend has changed extra.scopes
issues:
Property currentUser is defined two or more times (user-class.js (280), users.js (538))
ERROR: The @snippet tag - file 'velo-docs/examples/CRM-createContact_custom-fields.es6' not found. File: users.js line: 66