DocWorks for wix-crm-backend - 31 changes detected, but 2 issue detected changes: Service wix-crm-backend.tasks operation createTask.examples[0] has changed body Service wix-crm-backend.tasks operation createTask.examples has 1 new examples Service wix-crm-backend.tasks operation deleteTask was removed Service wix-crm-backend.tasks operation getTask.examples[0] has changed body Service wix-crm-backend.tasks operation getTasksList was removed Service wix-crm-backend.tasks operation setCompletedStatus was removed Service wix-crm-backend.tasks operation updateTask has changed param name from fields to taskData Service wix-crm-backend.tasks operation updateTask has changed param taskData type Service wix-crm-backend.tasks operation updateTask has changed param taskData doc Service wix-crm-backend.tasks operation updateTask param taskData was removed Service wix-crm-backend.tasks operation updateTask has changed description Service wix-crm-backend.tasks operation updateTask.examples[0] has changed body Service wix-crm-backend.tasks operation updateTask.examples has 2 new examples Service wix-crm-backend.tasks has a new operation getTaskList Service wix-crm-backend.tasks has a new operation completeTask Service wix-crm-backend.tasks has a new operation resetTask Service wix-crm-backend.tasks has a new operation removeTask Service wix-crm-backend.tasks message Task member taskId was removed Service wix-crm-backend.tasks message Task member creator was removed Service wix-crm-backend.tasks message Task member dueAt was removed Service wix-crm-backend.tasks message Task has a new member _id Service wix-crm-backend.tasks message Task has a new member dueDate Service wix-crm-backend.tasks message Task has a new member creatorType Service wix-crm-backend.tasks message Task has a new member userId Service wix-crm-backend.tasks message Task has a new member applicationId Service wix-crm-backend.tasks message Task.examples[0] has changed body Service wix-crm-backend.tasks message TaskCreator was removed Service wix-crm-backend.tasks message TaskData member dueAt was removed Service wix-crm-backend.tasks message TaskData has a new member dueDate Service wix-crm-backend.tasks message TaskData.examples has 1 new examples Service wix-crm-backend.tasks message TaskList was removed
issues:
Operation emailContact has an unknown param type wix-users.TriggeredEmailOptions (contacts.js (142))
ERROR: The @snippet tag - file 'examples/CRM-tasks-getTasksList.es6' not found. File: api.js line: 75