DocWorks  - 1 change detected, but 22 issue detected changes: Service $w.UploadButton property fileType has changed description
issues:
Property background is defined two or more times (document.es6 (74), Columns.es6 (61))
Operation onItemClicked is defined two or more times (BaseGallery.es6 (365), ProGallery.es6 (52))
Property scrolling is missing a type annotation (HtmlComponent.es6 (65))
Property dataFetcher is missing a type annotation (Table.es6 (429))
Property wrap is defined two or more times (TextBox.es6 (60, 103))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (95))
Operation logout has an unknown return type void (users.es6 (302))
Operation promptForgotPassword has an unknown return type void (users.es6 (336))
Operation scrollTo has an unknown return type void (window.es6 (236))
Operation scrollBy has an unknown return type void (window.es6 (282))
Property value is defined two or more times (DropDown.es6 (221), FormElement.es6 (28))
Operation scrollTo has an unknown return type void (Node.es6 (163))
Operation collapse has an unknown return type void (CollapsedMixin.es6 (16))
Operation expand has an unknown return type void (CollapsedMixin.es6 (111))
Operation disable has an unknown return type void (DisabledMixin.es6 (10))
Operation enable has an unknown return type void (DisabledMixin.es6 (41))
Operation hide has an unknown return type void (HiddenMixin.es6 (16))
Operation show has an unknown return type void (HiddenMixin.es6 (144))
ERROR: The @summary tag requires a value. File: window.es6, line: 447
ERROR: The @description tag requires a value. File: window.es6, line: 447
ERROR: The @summary tag requires a value. File: window.es6, line: 453
ERROR: The @description tag requires a value. File: window.es6, line: 453