DocWorks for js-wixcode-sdk - 28 changes detected, but 3 issue detected changes: Service $w.CheckboxGroup property style was removed Service $w.Element property rendered has changed description Service $w.KeyboardEvent property altKey.examples[1] has changed body Service $w.KeyboardEvent property ctrlKey.examples[1] has changed body Service $w.KeyboardEvent property key.examples[1] has changed body Service $w.KeyboardEvent property metaKey.examples[1] has changed body Service $w.KeyboardEvent property shiftKey.examples[1] has changed body Service $w.Repeater has changed description Service $w.Style has changed summary Service $w.Style property backgroundColor has changed description Service $w.Style property borderColor has changed description Service $w.Style property borderRadius has changed description Service $w.Style property borderWidth has changed description Service $w.Style property color has changed description Service $w.StyleMixin has changed description Service $w.TextInput property min has changed description Service $w.TextInputMixin operation onKeyPress.examples[1] has changed body Service $w.TextInputMixin operation onKeyPress has changed extra.notes Service $w.UploadButton property value has changed setter Service $w operation onReady has changed description Service wix-site property language has changed description Service wix-site property language has changed extra.notes Service wix-window.rendering property env has changed summary Service wix-window.rendering property env has changed description Service wix-window.rendering property renderCycle has changed summary Service wix-window.rendering property renderCycle has changed description Service wix-window.rendering property warmupData has changed summary Service wix-window.rendering property warmupData has changed description
issues:
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (101))
ERROR: The @snippet tag - file 'examples/State-name.es6' not found. File: State.es6 line: 71
ERROR: The @snippet tag - file 'examples/State-name.es6' not found. File: State.es6 line: 88