DocWorks for wix-ui-santa - 10 changes detected, but 74 issue detected changes: Service $w.Captcha mixes $w.Element was removed Service $w.Captcha has changed description Service $w.Captcha property token.examples[1] has changed body Service $w.Captcha operation onError has changed summary Service $w.Captcha operation onError.examples[0] has changed body Service $w.Captcha operation onTimeout.examples[0] has changed body Service $w.Captcha operation onVerified has changed summary Service $w.Captcha operation onVerified has changed description Service $w.Captcha operation onVerified.examples[1] has changed body Service $w.Captcha operation reset.examples[1] has changed body
issues:
Operation onChange has an unknown param type $w.EventHandler (Pagination.js (36))
Mixin $w.Element not found (Pagination.js (6))
Mixin $w.DisabledMixin not found (Pagination.js (6))
Mixin $w.HiddenCollapsedMixin not found (Pagination.js (6))
Mixin $w.ClickableMixin not found (Pagination.js (6))
Mixin $w.ViewportMixin not found (Pagination.js (6))
Mixin $w.Element not found (RatingsDisplay.js (6))
Mixin $w.HiddenCollapsedMixin not found (RatingsDisplay.js (6))
Mixin $w.ClickableMixin not found (RatingsDisplay.js (6))
Mixin $w.Element not found (Slider.js (6))
Mixin $w.ValueMixin not found (Slider.js (6))
Mixin $w.DisabledMixin not found (Slider.js (6))
Mixin $w.HiddenCollapsedMixin not found (Slider.js (6))
Mixin $w.FocusMixin not found (Slider.js (6))
Operation onPlay has an unknown param type $w.EventHandler (VideoPlayer.js (479))
Operation onPause has an unknown param type $w.EventHandler (VideoPlayer.js (518))
Operation onEnded has an unknown param type $w.EventHandler (VideoPlayer.js (557))
Operation onProgress has an unknown param type $w.EventHandler (VideoPlayer.js (594))
Mixin $w.Element not found (VideoPlayer.js (8))
Mixin $w.HiddenCollapsedMixin not found (VideoPlayer.js (8))
Mixin $w.Element not found (Switch.js (6))
Mixin $w.DisabledMixin not found (Switch.js (6))
Mixin $w.HiddenCollapsedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (Switch.js (6))
Mixin $w.ClickableMixin not found (Switch.js (6))
Mixin $w.ValueMixin not found (Switch.js (6))
Mixin $w.CheckedMixin not found (Switch.js (6))
Mixin $w.FocusMixin not found (TimePicker.js (10))
Mixin $w.DisabledMixin not found (TimePicker.js (10))
Mixin $w.HiddenCollapsedMixin not found (TimePicker.js (10))
Mixin $w.RequiredMixin not found (TimePicker.js (10))
Mixin $w.ReadOnlyMixin not found (TimePicker.js (10))
Mixin $w.FormElement not found (TimePicker.js (10))
Operation onIconMouseIn has an unknown param type $w.IconMouseInEventHandler (RatingsInput.js (25))
Mixin $w.FormElement not found (RatingsInput.js (8))
Mixin $w.DisabledMixin not found (RatingsInput.js (8))
Mixin $w.RequiredMixin not found (RatingsInput.js (8))
Mixin $w.HiddenCollapsedMixin not found (RatingsInput.js (8))
Mixin $w.FocusMixin not found (RatingsInput.js (8))
Mixin $w.ClickableMixin not found (RatingsInput.js (8))
Mixin $w.ViewportMixin not found (RatingsInput.js (8))
Mixin $w.FormElement not found (RichTextBox.js (11))
Mixin $w.DisabledMixin not found (RichTextBox.js (11))
Mixin $w.TextInputMixin not found (RichTextBox.js (11))
Mixin $w.HiddenCollapsedMixin not found (RichTextBox.js (11))
Mixin $w.FocusMixin not found (RichTextBox.js (11))
Mixin $w.ReadOnlyMixin not found (RichTextBox.js (11))
Mixin $w.ClickableMixin not found (RichTextBox.js (11))
Mixin $w.RequiredMixin not found (RichTextBox.js (11))
Mixin $w.FormElement not found (AddressInput.js (124))
Mixin $w.DisabledMixin not found (AddressInput.js (124))
Mixin $w.RequiredMixin not found (AddressInput.js (124))
Mixin $w.ReadOnlyMixin not found (AddressInput.js (124))
Mixin $w.HiddenCollapsedMixin not found (AddressInput.js (124))
Mixin $w.FocusMixin not found (AddressInput.js (124))
Mixin $w.ClickableMixin not found (AddressInput.js (124))
Operation onPlay has an unknown param type $w.EventHandler (MusicPlayer.js (586))
Operation onPause has an unknown param type $w.EventHandler (MusicPlayer.js (625))
Operation onEnded has an unknown param type $w.EventHandler (MusicPlayer.js (664))
Operation onProgress has an unknown param type $w.EventHandler (MusicPlayer.js (701))
Mixin $w.Element not found (MusicPlayer.js (9))
Mixin $w.HiddenCollapsedMixin not found (MusicPlayer.js (9))
Callback VerifiedHandler has an unknown return type Void (Captcha.js (201))
Mixin $w.FocusMixin not found (Captcha.js (6))
Property style has an unknown type $w.Style (ProgressBar.js (41))
Mixin $w.Element not found (ProgressBar.js (17))
Mixin $w.HiddenCollapsedMixin not found (ProgressBar.js (17))
Mixin $w.StyleMixin not found (ProgressBar.js (17))
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-wix.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-youtube.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-vimeo.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-twitch.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-dailymotion.es6' not found. File: VideoPlayer.js line: 654
ERROR: The @snippet tag - file 'examples/VideoPlayer-src_set-mp4.es6' not found. File: VideoPlayer.js line: 654