DocWorks for wix-store-backend - 18 changes detected, but 5 issue detected changes: Service wix-stores-backend.Events has changed description Service wix-stores-backend.Events operation onCartAbandoned has changed extra.notes Service wix-stores-backend.Events operation onCartCompleted has changed extra.notes Service wix-stores-backend.Events operation onCartCreated has changed extra.notes Service wix-stores-backend.Events operation onCartRecovered has changed extra.notes Service wix-stores-backend.Events operation onNewOrder has changed extra.notes Service wix-stores-backend operation getProductOptionsAvailability has changed param choices type Service wix-stores-backend operation getProductOptionsAvailability has changed description Service wix-stores-backend operation getProductOptionsAvailability.examples[0] has changed body Service wix-stores-backend operation getProductOptionsAvailability.examples[1] has changed body Service wix-stores-backend has a new operation getProductVariants Service wix-stores-backend message StoreProductChoices was removed Service wix-stores-backend has a new message ProductChoices Service wix-stores-backend has a new message ProductVariantOptions Service wix-stores-backend has a new message PagingOptions Service wix-stores-backend has a new message VariantList Service wix-stores-backend has a new message VariantItem Service wix-stores-backend has a new message VariantInfo
issues:
Message ProductOptionsAvailability has an unknown property type $w.ProductPage.StoreProductOptions (products.js (31))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.ImageItem (products.js (31))
Message ProductOptionsAvailability has an unknown property type $w.Gallery.VideoItem (products.js (31))
ERROR: The @snippet tag - file 'examples/Stores-backend-getAbandonedCart.es6' not found. File: abandonedCarts.js line: 6
ERROR: The @snippet tag - file 'examples/Stores-backend-getAbandonedCart.es6' not found. File: abandonedCarts.js line: 19