DocWorks for wix-members-backend - 2 changes detected, but 16 issue detected changes: Service wix-members-backend.Events message ApprovedMemberEvent member data was removed Service wix-members-backend.Events message ApprovedMemberEvent has a new member entity
issues:
Message BlockedMemberEvent has an unknown property type Members (events.js (73))
Message CreatedMemberEvent has an unknown property type Members (events.js (97))
Message DeletedMemberEvent has an unknown property type Members (events.js (121))
Message CommunityJoinedEvent has an unknown property type Members (events.js (144))
Message CommunityLeftEvent has an unknown property type Members (events.js (168))
Message MutedMemberEvent has an unknown property type Members (events.js (193))
Message UnmutedMemberEvent has an unknown property type Members (events.js (217))
Message UpdatedMemberEvent has an unknown property type Members (events.js (242))
ERROR: The @snippet tag - file 'velo-docs/examples/events/Members-backend-Events-onMemberCreated.es6' not found. File: events.js line: 80
ERROR: The @snippet tag - file 'velo-docs/examples/events/Members-backend-Events-on.es6' not found. File: events.js line: 96
ERROR: The @snippet tag - file 'velo-docs/examples/events/Members-backend-Events-on.es6' not found. File: events.js line: 120
ERROR: The @snippet tag - file 'velo-docs/examples/events/Members-backend-Events-on.es6' not found. File: events.js line: 143
ERROR: The @snippet tag - file 'velo-docs/examples/events/Members-backend-Events-on.es6' not found. File: events.js line: 166
ERROR: The @snippet tag - file 'velo-docs/examples/events/Members-backend-Events-on.es6' not found. File: events.js line: 190
ERROR: The @snippet tag - file 'velo-docs/examples/events/Members-backend-Events-on.es6' not found. File: events.js line: 214
ERROR: The @snippet tag - file 'velo-docs/examples/events/Members-backend-Events-on.es6' not found. File: events.js line: 238