DocWorks for wix-captcha-backend - 1 change detected, but 1 issue detected changes: Service wix-captcha-backend was removed
issues:
ERROR: Unable to parse /Users/talyaro/Repos/elementory-dynamic-modules/wix-captcha-backend/src/authorise-token.js: Line 4: Unexpected identifier