DocWorks for wix-users-backend - 4 changes detected, but 5 issue detected changes: Service wix-users-backend.badges has a new operation assignMembers Service wix-users-backend.badges has a new operation removeMembers Service wix-users-backend operation assignMembers was removed Service wix-users-backend operation removeMembers was removed
issues:
Operation register has an unknown param type wix-users.RegistrationOptions (users.js (40))
Operation emailUser has an unknown param type wix-users.TriggeredEmailOptions (users.js (240))
Property currentUser has an unknown type wix-users.User (users.js (299))
Message RegistrationResult has an unknown property type wix-users.User (users.js (24))
ERROR: The @snippet tag - file 'corvid-docs/examples/Users-backend-badges-assignMembers-scenario.es6' not found. File: badges.js line: 12