DocWorks for wix-crm-backend - 69 changes detected, but 24 issue detected changes: Service wix-crm-backend.invoices operation createInvoice has changed return type Service wix-crm-backend.invoices operation updateInvoice has changed param id type Service wix-crm-backend.invoices operation updateInvoice has changed return type Service wix-crm-backend.invoices has a new message IdAndVersion Service wix-crm-backend.invoices has a new message Address Service wix-crm-backend.invoices has a new message Customer Service wix-crm-backend.invoices has a new message LineItem Service wix-crm-backend.invoices has a new message LineItemTax Service wix-crm-backend.invoices has a new message Locale Service wix-crm-backend.invoices has a new message TotalPrice Service wix-crm-backend.invoices has a new message ItemizedFee Service wix-crm-backend.invoices has a new message Discount Service wix-crm-backend.invoices has a new message CalculatedTax Service wix-crm-backend.invoices has a new message MetaData Service wix-crm-backend.invoices has a new message Response Service wix-crm-backend.invoices has a new message ErrorResult Service wix-crm-backend.priceQuotes message CalculatedTax link [Invoice](wix-crm-backend.invoice.html#Invoice) was removed Service wix-crm-backend.priceQuotes message CalculatedTax.examples has 1 examples removed Service wix-crm-backend.priceQuotes message Customer link [Invoice](wix-crm-backend.invoice.html#Invoice) was removed Service wix-crm-backend.priceQuotes message Customer link [InvoiceFields](wix-crm-backend.invoice.html#InvoiceFields) was removed Service wix-crm-backend.priceQuotes message Customer link [createInvoice( )](wix-crm-backend.invoice.html#createPriceQuote) was removed Service wix-crm-backend.priceQuotes message Customer link [getInvoice( )](wix-crm-backend.invoice.html#getInvoice) was removed Service wix-crm-backend.priceQuotes message Customer link [updateInvoice( )](wix-crm-backend.invoice.html#updateInvoice) was removed Service wix-crm-backend.priceQuotes message Customer.examples[1] has changed title Service wix-crm-backend.priceQuotes message Customer.examples[1] has changed body Service wix-crm-backend.priceQuotes message Customer.examples has 2 examples removed Service wix-crm-backend.priceQuotes message Discount link [Invoice](wix-crm-backend.invoice.html#Invoice) was removed Service wix-crm-backend.priceQuotes message Discount link [InvoiceFields](wix-crm-backend.invoice.html#InvoiceFields) was removed Service wix-crm-backend.priceQuotes message Discount.examples[1] has changed title Service wix-crm-backend.priceQuotes message Discount.examples[1] has changed body Service wix-crm-backend.priceQuotes message Discount.examples has 2 examples removed Service wix-crm-backend.priceQuotes message IdAndVersion link [Invoice](wix-crm-backend.invoice.html#Invoice) was removed Service wix-crm-backend.priceQuotes message IdAndVersion link [UpdateInvoiceRequest](wix-crm-backend.invoice.html#UpdateInvoiceRequest) was removed Service wix-crm-backend.priceQuotes message IdAndVersion.examples[1] has changed title Service wix-crm-backend.priceQuotes message IdAndVersion.examples[1] has changed body Service wix-crm-backend.priceQuotes message IdAndVersion.examples has 2 examples removed Service wix-crm-backend.priceQuotes message LineItem link [InvoiceFields](wix-crm-backend.invoice.html#InvoiceFields) was removed Service wix-crm-backend.priceQuotes message LineItem.examples[1] has changed title Service wix-crm-backend.priceQuotes message LineItem.examples[1] has changed body Service wix-crm-backend.priceQuotes message LineItem.examples has 2 examples removed Service wix-crm-backend.priceQuotes message Locale link [Invoice](wix-crm-backend.invoice.html#Invoice) was removed Service wix-crm-backend.priceQuotes message Locale.examples has 1 examples removed Service wix-crm-backend.priceQuotes message MetaData link [Invoice](wix-crm-backend.invoice.html#Invoice) was removed Service wix-crm-backend.priceQuotes message MetaData link [InvoiceFields](wix-crm-backend.invoice.html#InvoiceFields) was removed Service wix-crm-backend.priceQuotes message MetaData.examples[1] has changed title Service wix-crm-backend.priceQuotes message MetaData.examples[1] has changed body Service wix-crm-backend.priceQuotes message MetaData.examples has 2 examples removed Service wix-crm-backend.priceQuotes message TotalPrice link [Invoice](wix-crm-backend.invoice.html#Invoice) was removed Service wix-crm-backend.workflows operation createCard has changed param card type Service wix-crm-backend.workflows operation createCard has changed description Service wix-crm-backend.workflows operation createCard.examples[0] has changed body Service wix-crm-backend.workflows operation createPhase has changed description Service wix-crm-backend.workflows operation deletePhase.examples[0] has changed body Service wix-crm-backend.workflows operation deleteWorkflow.examples[0] has changed body Service wix-crm-backend.workflows operation getCard.examples[0] has changed body Service wix-crm-backend.workflows operation getPhase.examples[0] has changed body Service wix-crm-backend.workflows operation listCards.examples[0] has changed body Service wix-crm-backend.workflows operation movePhase has changed description Service wix-crm-backend.workflows operation updateCardFields has changed param name from cardInfo to cardData Service wix-crm-backend.workflows operation updateCardFields has changed param cardData type Service wix-crm-backend.workflows message Card.examples[0] has changed body Service wix-crm-backend.workflows message CardInfo.examples[0] has changed title Service wix-crm-backend.workflows message CardInfo.examples[0] has changed body Service wix-crm-backend.workflows message CardInfo.examples has 1 examples removed Service wix-crm-backend.workflows message CardList.examples[0] has changed body Service wix-crm-backend.workflows message ListCardsOptions.examples[0] has changed body Service wix-crm-backend.workflows message Pagination.examples[0] has changed body Service wix-crm-backend.workflows message Phase.examples[0] has changed body Service wix-crm-backend.workflows has a new message CardData
issues:
Message FormAttachment has an unknown property type Type (events.js (61))
Operation emailContact has an unknown param type wix-users.TriggeredEmailOptions (contacts.js (90))
Operation createInvoice has an unknown param type wix-crm-backend.invoices.InvoiceFields (invoices.js (90))
Operation updateInvoice has an unknown param type wix-crm-backend.invoices.InvoiceFields (invoices.js (122))
Message Invoice has an unknown property type wix-crm-backend.quotes.IdAndVersion (invoices.js (28))
Message Invoice has an unknown property type wix-crm-backend.quotes.Locale (invoices.js (28))
Message Invoice has an unknown property type wix-crm-backend.quotes.Customer (invoices.js (28))
Message Invoice has an unknown property type wix-crm-backend.quotes.LineItem (invoices.js (28))
Message Invoice has an unknown property type wix-crm-backend.quotes.Discount (invoices.js (28))
Message Invoice has an unknown property type wix-crm-backend.quotes.CalculatedTax (invoices.js (28))
Message Invoice has an unknown property type wix-crm-backend.quotes.TotalPrice (invoices.js (28))
Message Invoice has an unknown property type wix-crm-backend.quotes.MetaData (invoices.js (28))
Message Response has an unknown property type IIdAndVersion (quotes-common-types.js (292))
Message Response has an unknown property type IIdAndVersion (quotes-common-types.js (286))
Operation getCard has an unknown return type wix-crm-backend.workflow.Card (cardsApi.js (59))
Operation updateCardFields has an unknown param type wix-crm-backend.workflows.CartData (cardsApi.js (130))
Operation getPhase has an unknown return type wix-crm-backend.workflow.Phase (phasesApi.js (55))
Operation getWorkflow has an unknown return type crm-backend.workflows.Workflow (workflowsApi.js (45))
Message Phase has an unknown property type wix-crm-backend.workflows.CardsList (typesDocs.js (9))
Message Workflow has an unknown property type wix-crm-backend.workflows.PhasesList (typesDocs.js (17))
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-createInvoice.es6' not found. File: quotes-common-types.js line: 39
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-getInvoice.es6' not found. File: quotes-common-types.js line: 39
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-createInvoice.es6' not found. File: quotes-common-types.js line: 131
ERROR: The @snippet tag - file 'examples/CRM-priceQuotes-getInvoice.es6' not found. File: quotes-common-types.js line: 131