DocWorks for wix-store-backend - 2 changes detected, but 34 issue detected changes: Service wix-stores-backend.Events is new Service wix-stores-backend is new
issues:
Message CartCompletedEvent has an unknown property type wix-stores-backend.ShippingInfo (events.js (183))
Message ProductCreatedEvent has an unknown property type $w.Gallery.VideoItem (events.js (216))
Message Cart has an unknown property type wix-stores-backend.ShippingInfo (carts.js (1))
Message AppliedCoupon is defined two or more times (carts.js (32), orders.js (392))
Message BuyerInfo is defined two or more times (carts.js (52), orders.js (91))
Message Option is defined two or more times (carts.js (120), orders.js (281))
Message CustomTextField is defined two or more times (carts.js (131), orders.js (300))
Message MediaItem is defined two or more times (orders.js (289), products.js (66))
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 20
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 65
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 91
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 111
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 140
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 148
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 162
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 170
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 190
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 207
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 225
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 236
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 244
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 253
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 269
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 281
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 289
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 300
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 308
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 343
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 356
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 365
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 373
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 382
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 392
ERROR: The @snippet tag - file 'corvid-docs/examples/Stores-backend-createOrder.es6' not found. File: orders.js line: 401