case sensitive
* DocWorks for wix-media-manager-backend - no significant changes detected, but 1 issue detected

issues:
Operation upload has an unknown param type Buffer (upload.js (1))

* DocWorks for wix-crm-backend - 2 changes detected, but 3 issue detected
changes:
Service wix-crm-backend.Contacts.ContactsQueryBuilder operation hasSome has changed description
Service wix-crm-backend.Contacts.ContactsQueryBuilder operation startsWith has changed description

issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

* DocWorks for wix-pricing-plans-backend - 3 changes detected, but 3 issue detected
changes:
Service wix-pricing-plans-backend.PublicPlansQueryBuilder operation contains has changed description
Service wix-pricing-plans-backend.PublicPlansQueryBuilder operation endsWith has changed description
Service wix-pricing-plans-backend.PublicPlansQueryBuilder operation startsWith has changed description

issues:
Message OrderCycleStartedEventData is defined two or more times (events.js (210, 210))
Operation eq has an unknown param type * (plan-queries.js (43))
Operation ne has an unknown param type * (plan-queries.js (73))

* DocWorks for wix-groups-backend - 3 changes detected, but 10 issue detected
changes:
Service wix-groups-backend.Groups.GroupsQueryBuilder operation contains has changed description
Service wix-groups-backend.Groups.GroupsQueryBuilder operation endsWith has changed description
Service wix-groups-backend.Groups.GroupsQueryBuilder operation startsWith has changed description

issues:
Operation eq has an unknown param type * (createRequests.js (216))
Operation ne has an unknown param type * (createRequests.js (237))
Operation eq has an unknown param type * (groups.js (277))
Operation ne has an unknown param type * (groups.js (299))
Operation eq has an unknown param type * (joinRequests.js (213))
Operation ne has an unknown param type * (joinRequests.js (235))
Operation eq has an unknown param type * (members.js (278))
Operation ne has an unknown param type * (members.js (300))
Operation eq has an unknown param type * (members.js (743))
Operation ne has an unknown param type * (members.js (765))

* DocWorks for wix-events-backend - 1 change detected, but 2 issue detected
changes:
Service wix-events-backend.WixEvents.EventsQueryBuilder operation contains has changed description

issues:
Operation eq has an unknown param type * (event-query.js (34))
Operation ne has an unknown param type * (event-query.js (63))

* DocWorks for wix-events-backend - 1 change detected, but 2 issue detected
changes:
Service wix-events-backend.WixEvents.EventsQueryBuilder operation contains has changed description

issues:
Operation eq has an unknown param type * (event-query.js (34))
Operation ne has an unknown param type * (event-query.js (63))

* DocWorks for wix-events-backend - 1 change detected, but 2 issue detected
changes:
Service wix-events-backend.WixEvents.EventsQueryBuilder operation contains has changed description

issues:
Operation eq has an unknown param type * (event-query.js (34))
Operation ne has an unknown param type * (event-query.js (63))

* DocWorks for wix-events-backend - 1 change detected, but 2 issue detected
changes:
Service wix-events-backend.WixEvents.EventsQueryBuilder operation contains has changed description

issues:
Operation eq has an unknown param type * (event-query.js (34))
Operation ne has an unknown param type * (event-query.js (63))

* DocWorks for wix-events-backend - 1 change detected, but 2 issue detected
changes:
Service wix-events-backend.WixEvents.EventsQueryBuilder operation contains has changed description

issues:
Operation eq has an unknown param type * (event-query.js (34))
Operation ne has an unknown param type * (event-query.js (63))

* DocWorks for wix-pricing-plans - no significant changes detected

* DocWorks for wix-bookings-backend - no significant changes detected, but 3 issue detected

issues:
Operation eq has an unknown param type * (SessionQueryBuilder.js (121))
Operation ne has an unknown param type * (SessionQueryBuilder.js (146))
Operation eq has an unknown param type * (WixBookingsQueryBuilder.js (50))

* DocWorks for wix-crm-backend - 1 change detected, but 3 issue detected
changes:
Service wix-crm-backend.Contacts.ContactsQueryBuilder operation startsWith has changed description

issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

* DocWorks for wix-crm-backend - no significant changes detected, but 3 issue detected

issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

* DocWorks for wix-groups-backend - 3 changes detected, but 10 issue detected
changes:
Service wix-groups-backend.Groups.GroupsQueryBuilder operation contains has changed description
Service wix-groups-backend.Groups.GroupsQueryBuilder operation endsWith has changed description
Service wix-groups-backend.Groups.GroupsQueryBuilder operation startsWith has changed description

issues:
Operation eq has an unknown param type * (createRequests.js (216))
Operation ne has an unknown param type * (createRequests.js (237))
Operation eq has an unknown param type * (groups.js (277))
Operation ne has an unknown param type * (groups.js (299))
Operation eq has an unknown param type * (joinRequests.js (213))
Operation ne has an unknown param type * (joinRequests.js (235))
Operation eq has an unknown param type * (members.js (278))
Operation ne has an unknown param type * (members.js (300))
Operation eq has an unknown param type * (members.js (743))
Operation ne has an unknown param type * (members.js (765))

* DocWorks for wix-pricing-plans-backend - 3 changes detected, but 3 issue detected
changes:
Service wix-pricing-plans-backend.PublicPlansQueryBuilder operation contains has changed description
Service wix-pricing-plans-backend.PublicPlansQueryBuilder operation endsWith has changed description
Service wix-pricing-plans-backend.PublicPlansQueryBuilder operation startsWith has changed description

issues:
Message OrderCycleStartedEventData is defined two or more times (events.js (210, 210))
Operation eq has an unknown param type * (plan-queries.js (43))
Operation ne has an unknown param type * (plan-queries.js (73))

* DocWorks for wix-events-backend - 1 change detected, but 2 issue detected
changes:
Service wix-events-backend.WixEvents.EventsQueryBuilder operation contains has changed description

issues:
Operation eq has an unknown param type * (event-query.js (34))
Operation ne has an unknown param type * (event-query.js (63))

---------

Co-authored-by: sibrooke <simonbr@wix.com>
Co-authored-by: simonbr <106070006+sibrooke@users.noreply.github.com>