DocWorks  - 143 changes detected, but 22 issue detected changes: Service $w.Box property style was removed Service $w.Checkbox property required has changed description Service $w.CollapsedMixin property collapsed has changed description Service $w.ContainableMixin has changed summary Service $w.DisabledMixin property enabled has changed description Service $w.FocusMixin operation blur has changed description Service $w.FocusMixin operation focus has changed description Service $w.Footer property style was removed Service $w.Gallery message GalleryItem was removed Service $w.Gallery message ImageItem member description has changed doc Service $w.Gallery message ImageItem member settings has changed type Service $w.Gallery message ImageItem member settings.quality was removed Service $w.Gallery message ImageItem member settings.amount was removed Service $w.Gallery message ImageItem member settings.radius was removed Service $w.Gallery message ImageItem member settings.threshold was removed Service $w.Gallery message TextItem member style has changed type Service $w.Gallery message TextItem member style has changed doc Service $w.Gallery message TextItem member style.layoutRatio was removed Service $w.Gallery message TextItem member style.fillColor was removed Service $w.Gallery message TextItem member style.opacity was removed Service $w.Gallery message TextItem member style.boxPadding was removed Service $w.Gallery message TextItem member style.verticalAlignment was removed Service $w.Gallery message VideoItem member description has changed doc Service $w.Gallery has a new message ImageItemSettings Service $w.Gallery has a new message TextItemStyle Service $w.Header property style was removed Service $w.HiddenMixin property hidden has changed description Service $w.HiddenMixin property isVisible has changed description Service $w.HiddenMixin message ArcEffectOptions was removed Service $w.HiddenMixin message BounceEffectOptions was removed Service $w.HiddenMixin message DropEffectOptions was removed Service $w.HiddenMixin message ExpandEffectOptions was removed Service $w.HiddenMixin message FadeEffectOptions was removed Service $w.HiddenMixin message FlipEffectOptions was removed Service $w.HiddenMixin message FloatEffectOptions was removed Service $w.HiddenMixin message FlyEffectOptions was removed Service $w.HiddenMixin message FoldEffectOptions was removed Service $w.HiddenMixin message GlideEffectOptions was removed Service $w.HiddenMixin message RevealEffectOptions was removed Service $w.HiddenMixin message SlideEffectOptions was removed Service $w.HiddenMixin message SpinEffectOptions was removed Service $w.HiddenMixin message TurnEffectOptions was removed Service $w.HtmlComponent operation onMessage has changed summary Service $w.HtmlComponent operation onMessage has changed description Service $w.HtmlComponent operation postMessage has changed description Service $w.LinkableMixin property link has changed description Service $w.MouseEvent property clientX has changed description Service $w.MouseEvent property clientY has changed description Service $w.MouseEvent property offsetX has changed description Service $w.MouseEvent property offsetY has changed description Service $w.MouseEvent property pageX has changed description Service $w.MouseEvent property pageY has changed description Service $w.MouseEvent property screenX has changed description Service $w.MouseEvent property screenY has changed description Service $w.Pagination property currentPage has changed description Service $w.Pagination property totalPages has changed description Service $w.PlayableMixin operation pause has changed description Service $w.PlayableMixin operation play has changed description Service $w.Repeater property data has changed description Service $w.Repeater operation forEachItem has changed description Service $w.Repeater operation forItems has changed description Service $w.Repeater operation onItemReady has changed description Service $w.RequiredMixin property required has changed description Service $w.Shape was removed Service $w.Slideshow operation onChange has changed description Service $w.Table property dataFetcher has changed summary Service $w.Table property rows has changed description Service $w.Table message PaginationParam was removed Service $w.TextBox property inputType was removed Service $w.TextBox property wrap has changed summary Service $w.TextBox property wrap has changed description Service $w.ToggleSwitch was removed Service $w.UploadButton has changed description Service $w.UploadButton operation startUpload has changed description Service $w.ValidatableMixin operation resetValidityIndication has changed description Service $w.ValidatableMixin operation updateValidityIndication has changed summary Service $w operation $w has changed param name from getWixSelector to selector Service $w operation $w has changed description Service wix-crm operation createContact has changed param name from handler to contactInfo Service wix-crm operation createContact has changed param contactInfo type Service wix-crm operation createContact has changed param contactInfo doc Service wix-crm operation createContact has changed return type Service wix-crm operation createContact has changed return doc Service wix-crm operation createContact has changed summary Service wix-crm operation createContact has changed description Service wix-crm operation emailContact has changed description Service wix-crm message ContactInfo member lastName has changed doc Service wix-crm message ContactInfo member lastName was removed Service wix-crm message ContactInfo member addresses was removed Service wix-location operation to has changed description Service wix-users-backend was removed Service wix-users operation emailUser has changed description Service wix-users operation onLogin has changed description Service wix-users operation register has changed description Service wix-users has a new operation applySessionToken Service wix-users message RegistrationResult member status has changed doc Service wix-users message RegistrationResult member approvalToken has changed doc Service wix-users message RegistrationResult has a new link [register](#register Service wix-users message TransactionalEmailOptions was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents has changed type Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].id was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].sku was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].name was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].category was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].price was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].currency was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].brand was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].variant was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].list was removed Service wix-window.trackingParameters message AddProductImpressionEvent member contents[].position was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents has changed type Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].id was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].sku was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].name was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].category was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].price was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].currency was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].brand was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].variant was removed Service wix-window.trackingParameters message InitiateCheckoutEvent member contents[].quantity was removed Service wix-window.trackingParameters message PurchaseEvent member contents has changed type Service wix-window.trackingParameters message PurchaseEvent member contents[].id was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].name was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].category was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].price was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].currency was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].brand was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].variant was removed Service wix-window.trackingParameters message PurchaseEvent member contents[].quantity was removed Service wix-window.trackingParameters has a new message AddProductImpressionEventContents Service wix-window.trackingParameters has a new message InitiateCheckoutEventContents Service wix-window.trackingParameters has a new message PurchaseEventContents Service wix-window operation scrollTo has changed description Service wix-window message AddPaymentInfoEvent was removed Service wix-window message AddProductImpressionEvent was removed Service wix-window message AddToCartEvent was removed Service wix-window message ClickProductEvent was removed Service wix-window message CustomEvent was removed Service wix-window message InitiateCheckoutEvent was removed Service wix-window message PurchaseEvent was removed Service wix-window message RemoveFromCartEvent was removed Service wix-window message ViewContentEvent was removed Service wix-pay is new
issues:
Property background is defined two or more times (document.es6 (69), Columns.es6 (55))
Property scrolling is missing a type annotation (HtmlComponent.es6 (76))
Property dataFetcher is missing a type annotation (Table.es6 (475))
Operation emailContact has an unknown param type wix-crm.TriggeredEmailOptions (crm.es6 (95))
Operation emailContact has an unknown return type void (crm.es6 (95))
Operation routerSitemap has an unknown return type wix-router.WixRouterSitemapEntry (site.es6 (98))
Operation promptForgotPassword has an unknown return type void (users.es6 (362))
Operation emailUser has an unknown return type void (users.es6 (469))
Operation scrollTo has an unknown return type void (window.es6 (321))
Operation scrollBy has an unknown return type void (window.es6 (371))
Operation openModal has an unknown return type void (window.es6 (796))
Callback ReadyHandler has an unknown return type void (wixCode.es6 (77))
Property value is defined two or more times (DropDown.es6 (245), FormElement.es6 (20))
Operation scrollTo has an unknown return type void (Node.es6 (161))
Operation collapse has an unknown return type void (CollapsedMixin.es6 (16))
Operation expand has an unknown return type void (CollapsedMixin.es6 (111))
Operation disable has an unknown return type void (DisabledMixin.es6 (10))
Operation enable has an unknown return type void (DisabledMixin.es6 (41))
Operation hide has an unknown return type void (HiddenMixin.es6 (38))
Operation show has an unknown return type void (HiddenMixin.es6 (187))
ERROR: The @description tag requires a value. File: BaseGallery.es6, line: 143
ERROR: The @description tag requires a value. File: BaseGallery.es6, line: 176