DocWorks for wixcode-stores - 7 changes detected, but 2 issue detected changes: Service wix-stores operation onCartChanged has changed param name from function to handler Service wix-stores operation onCartChanged has changed param handler type Service wix-stores operation onCartChanged has changed param handler doc Service wix-stores operation onCartChanged has changed summary Service wix-stores operation onCartChanged has changed description Service wix-stores callback callback was removed Service wix-stores has a new callback CartChangedHandler
issues:
Callback CartChangedHandler has an unknown param type wix-stores-backend.Cart (stores.js (224))
ERROR: The @snippet tag - file 'corvid-docs/examples/Users-onLogin.es6' not found. File: stores.js line: 225