DocWorks for blocks-elements - 9 changes detected, but 5 issue detected changes: Service $w.AvatarGroup property divider was removed Service $w.AvatarGroup property lastName was removed Service $w.AvatarGroup property rel was removed Service $w.AvatarGroup property size was removed Service $w.AvatarGroup property skin was removed Service $w.AvatarGroup property src was removed Service $w.AvatarGroup property stretched was removed Service $w.AvatarGroup operation onClick was removed Service $w.AvatarGroup message icon was removed
issues:
Mixin $w.HiddenCollapsedMixin not found (Avatar.js (1))
Mixin $w.Element not found (Avatar.js (1))
Mixin $w.HiddenCollapsedMixin not found (AvatarGroup.js (1))
Mixin $w.Element not found (AvatarGroup.js (1))
ERROR: The @snippet tag - file 'velo-docs/examples/AvatarGroup-size_get.es6' not found. File: AvatarGroup.js line: 27